//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "comment_thread_notification")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub notification_id: Uuid,
    pub recipient_id: i32,
    pub comment_thread_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::comment_thread::Entity",
        from = "Column::CommentThreadId",
        to = "super::comment_thread::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    CommentThread,
    #[sea_orm(
        belongs_to = "super::notification::Entity",
        from = "(Column::NotificationId, Column::RecipientId)",
        to = "(super::notification::Column::Id, super::notification::Column::RecipientId)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Notification,
}

impl Related<super::comment_thread::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommentThread.def()
    }
}

impl Related<super::notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notification.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
