//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "comment_created_notification_event")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub notification_event_id: i64,
    #[sea_orm(column_type = "Text")]
    pub content: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::notification_event::Entity",
        from = "Column::NotificationEventId",
        to = "super::notification_event::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    NotificationEvent,
}

impl Related<super::notification_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationEvent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
