//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "notification_entry")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub notification_id: Uuid,
    pub recipient_id: i32,
    pub event_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub seq: i64,
    pub inbox_seq: i64,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::notification::Entity",
        from = "(Column::NotificationId, Column::RecipientId)",
        to = "(super::notification::Column::Id, super::notification::Column::RecipientId)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Notification,
    #[sea_orm(
        belongs_to = "super::notification_event::Entity",
        from = "Column::EventId",
        to = "super::notification_event::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    NotificationEvent,
}

impl Related<super::notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notification.def()
    }
}

impl Related<super::notification_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationEvent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
