//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "song_relation_type")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::song_relation::Entity")]
    SongRelation,
    #[sea_orm(has_many = "super::song_relation_history::Entity")]
    SongRelationHistory,
}

impl Related<super::song_relation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SongRelation.def()
    }
}

impl Related<super::song_relation_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SongRelationHistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
