//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "song_relation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub first_id: i32,
    pub second_id: i32,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub relation_type_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::song::Entity",
        from = "Column::FirstId",
        to = "super::song::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Song2,
    #[sea_orm(
        belongs_to = "super::song::Entity",
        from = "Column::SecondId",
        to = "super::song::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Song1,
    #[sea_orm(
        belongs_to = "super::song_relation_type::Entity",
        from = "Column::RelationTypeId",
        to = "super::song_relation_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SongRelationType,
}

impl Related<super::song_relation_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SongRelationType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
