//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::EntityType;

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "user_collection_item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_collection_id: i32,
    pub position: i32,
    pub entity_id: Option<i32>,
    pub entity_type: EntityType,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_collection::Entity",
        from = "Column::UserCollectionId",
        to = "super::user_collection::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    UserCollection,
}

impl Related<super::user_collection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserCollection.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
