//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub password: String,
    pub avatar_id: Option<i32>,
    pub last_login: DateTimeWithTimeZone,
    pub profile_banner_id: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub bio: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub settings: Json,
    #[sea_orm(column_type = "Text")]
    pub email: String,
    pub email_verified: bool,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::artist_tag_vote::Entity")]
    ArtistTagVote,
    #[sea_orm(has_many = "super::comment::Entity")]
    Comment,
    #[sea_orm(has_many = "super::correction_revision::Entity")]
    CorrectionRevision,
    #[sea_orm(has_many = "super::correction_subscription::Entity")]
    CorrectionSubscription,
    #[sea_orm(has_many = "super::correction_user::Entity")]
    CorrectionUser,
    #[sea_orm(
        belongs_to = "super::image::Entity",
        from = "Column::AvatarId",
        to = "super::image::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Image2,
    #[sea_orm(
        belongs_to = "super::image::Entity",
        from = "Column::ProfileBannerId",
        to = "super::image::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Image1,
    #[sea_orm(has_many = "super::image_queue_subscription::Entity")]
    ImageQueueSubscription,
    #[sea_orm(has_many = "super::notification::Entity")]
    Notification,
    #[sea_orm(has_one = "super::notification_inbox_state::Entity")]
    NotificationInboxState,
    #[sea_orm(has_many = "super::release_tag_vote::Entity")]
    ReleaseTagVote,
    #[sea_orm(has_many = "super::song_tag_vote::Entity")]
    SongTagVote,
    #[sea_orm(has_many = "super::user_collection::Entity")]
    UserCollection,
    #[sea_orm(has_many = "super::user_collection_follow::Entity")]
    UserCollectionFollow,
    #[sea_orm(has_one = "super::user_email_verification::Entity")]
    UserEmailVerification,
    #[sea_orm(has_many = "super::user_role::Entity")]
    UserRole,
}

impl Related<super::artist_tag_vote::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistTagVote.def()
    }
}

impl Related<super::comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comment.def()
    }
}

impl Related<super::correction_revision::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CorrectionRevision.def()
    }
}

impl Related<super::correction_subscription::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CorrectionSubscription.def()
    }
}

impl Related<super::correction_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CorrectionUser.def()
    }
}

impl Related<super::image_queue_subscription::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImageQueueSubscription.def()
    }
}

impl Related<super::notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notification.def()
    }
}

impl Related<super::notification_inbox_state::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationInboxState.def()
    }
}

impl Related<super::release_tag_vote::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseTagVote.def()
    }
}

impl Related<super::song_tag_vote::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SongTagVote.def()
    }
}

impl Related<super::user_collection_follow::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserCollectionFollow.def()
    }
}

impl Related<super::user_email_verification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserEmailVerification.def()
    }
}

impl Related<super::user_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRole.def()
    }
}

impl Related<super::image_queue::Entity> for Entity {
    fn to() -> RelationDef {
        super::image_queue_subscription::Relation::ImageQueue.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::image_queue_subscription::Relation::User.def().rev())
    }
}

impl Related<super::role::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_role::Relation::Role.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_role::Relation::User.def().rev())
    }
}

impl Related<super::user_collection::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_collection_follow::Relation::UserCollection.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_collection_follow::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
