default_install_hook_types = ["pre-push"]
default_stages = ["pre-push"]
fail_fast = true

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-merge-conflict", stages = ["pre-push"] },
  { id = "check-case-conflict", stages = ["pre-push"] },
  { id = "detect-private-key", stages = ["pre-push"] },
  { id = "check-added-large-files", stages = ["pre-push"] },
  { id = "check-json", stages = ["pre-push"] },
  { id = "check-toml", stages = ["pre-push"] },
  { id = "check-yaml", stages = ["pre-push"] },
]
