[package]
edition = "2024"
name    = "thcdb-infra-storage"
publish = false
version = "0.1.0"

[lints]
workspace = true

[lib]
name = "infra_storage"
path = "src/lib.rs"

[dependencies]
async-stream.workspace = true
futures-util           = "0.3"
log                    = { workspace = true, features = [ "kv" ] }
tempfile               = "3.27.0"
tokio.workspace        = true

[dev-dependencies]
anyhow.workspace = true
