CREATE TABLE "public"."song_relation_type" (
  "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" TEXT NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("name")
);

INSERT INTO "public"."song_relation_type" ("id", "name")
VALUES
  (1, 'Original'),
  (2, 'Arrange'),
  (3, 'Cover'),
  (4, 'Remix'),
  (5, 'Live'),
  (6, 'Instrumental');

ALTER TABLE "public"."song_relation"
  DROP COLUMN "relation_type";

ALTER TABLE
  "public"."song_relation"
  ADD COLUMN "relation_type_id" INTEGER NOT NULL REFERENCES "public"."song_relation_type" ("id");

CREATE INDEX idx_song_relation_relation_type_id ON "public"."song_relation" ("relation_type_id");

CREATE TABLE "public"."song_relation_history" (
  "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "history_id" INTEGER NOT NULL REFERENCES "public"."song_history" ("id"),
  "related_song_id" INTEGER NOT NULL REFERENCES "public"."song" ("id"),
  "relation_type_id" INTEGER NOT NULL REFERENCES "public"."song_relation_type" ("id"),
  "description" TEXT NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX idx_song_relation_history_history_id ON "public"."song_relation_history" ("history_id");

CREATE INDEX idx_song_relation_history_related_song_id ON "public"."song_relation_history" ("related_song_id");

CREATE INDEX idx_song_relation_history_relation_type_id ON "public"."song_relation_history" ("relation_type_id");
