/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Touhou Cloud DB
 * TODO
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker"
import { useMutation, useQuery } from "@tanstack/solid-query"
import type {
	DataTag,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	SolidMutationOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/solid-query"
import { HttpResponse, http } from "msw"
import type { RequestHandlerOptions } from "msw"

import type {
	AuthCredential,
	ForgotPasswordDefaultOne,
	ForgotPasswordRequest,
	ResendVerificationEmailDefaultOne,
	ResendVerificationEmailRequest,
	ResetPasswordDefaultOne,
	ResetPasswordRequest,
	SignInDefaultOne,
	SignOutDefaultOne,
	SignUpDefaultOne,
	SignUpRequest,
	VerifyEmailDefaultOne,
	VerifyEmailRequest,
} from "./touhouCloudDB.schemas"
import { UserRoleEnum } from "./touhouCloudDB.schemas"
import type {
	DataForgotPasswordResponse,
	DataResendVerificationEmailResponse,
	DataSignUpResponse,
	DataUserProfile,
	Message,
} from "./touhouCloudDB.schemas"

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308
export type HTTPStatusCode4xx =
	| 400
	| 401
	| 402
	| 403
	| 404
	| 405
	| 406
	| 407
	| 408
	| 409
	| 410
	| 411
	| 412
	| 413
	| 414
	| 415
	| 416
	| 417
	| 418
	| 419
	| 420
	| 421
	| 422
	| 423
	| 424
	| 426
	| 428
	| 429
	| 431
	| 451
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511
export type HTTPStatusCodes =
	| HTTPStatusCode1xx
	| HTTPStatusCode2xx
	| HTTPStatusCode3xx
	| HTTPStatusCode4xx
	| HTTPStatusCode5xx

export type forgotPasswordResponse200 = {
	data: DataForgotPasswordResponse
	status: 200
}

export type forgotPasswordResponse429 = {
	data: string
	status: 429
}

export type forgotPasswordResponseDefaultApplicationJson = {
	data: ForgotPasswordDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type forgotPasswordResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type forgotPasswordResponseSuccess = forgotPasswordResponse200 & {
	headers: Headers
}
export type forgotPasswordResponseError = (
	| forgotPasswordResponse429
	| forgotPasswordResponseDefaultApplicationJson
	| forgotPasswordResponseDefaultTextPlain
) & {
	headers: Headers
}

export type forgotPasswordResponse =
	| forgotPasswordResponseSuccess
	| forgotPasswordResponseError

export const getForgotPasswordUrl = () => {
	return `/api/forgot-password`
}

export const forgotPassword = async (
	forgotPasswordRequest: ForgotPasswordRequest,
	options?: RequestInit,
): Promise<forgotPasswordResponse> => {
	const res = await fetch(getForgotPasswordUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(forgotPasswordRequest),
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: forgotPasswordResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as forgotPasswordResponse
}

export const getForgotPasswordMutationOptions = <
	TError = string | ForgotPasswordDefaultOne,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof forgotPassword>>,
		TError,
		{ data: ForgotPasswordRequest },
		TContext
	>
	fetch?: RequestInit
}): SolidMutationOptions<
	Awaited<ReturnType<typeof forgotPassword>>,
	TError,
	{ data: ForgotPasswordRequest },
	TContext
> => {
	const mutationKey = ["forgotPassword"]
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation
			&& "mutationKey" in options.mutation
			&& options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof forgotPassword>>,
		{ data: ForgotPasswordRequest }
	> = (props) => {
		const { data } = props ?? {}

		return forgotPassword(data, fetchOptions)
	}

	return { mutationFn, ...mutationOptions }
}

export type ForgotPasswordMutationResult = NonNullable<
	Awaited<ReturnType<typeof forgotPassword>>
>
export type ForgotPasswordMutationBody = ForgotPasswordRequest
export type ForgotPasswordMutationError = string | ForgotPasswordDefaultOne

export const useForgotPassword = <
	TError = string | ForgotPasswordDefaultOne,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof forgotPassword>>,
			TError,
			{ data: ForgotPasswordRequest },
			TContext
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof forgotPassword>>,
	TError,
	{ data: ForgotPasswordRequest },
	TContext
> => {
	return useMutation(
		() => getForgotPasswordMutationOptions(options),
		queryClient,
	)
}
export type resendVerificationEmailResponse200 = {
	data: DataResendVerificationEmailResponse
	status: 200
}

export type resendVerificationEmailResponse429 = {
	data: string
	status: 429
}

export type resendVerificationEmailResponseDefaultApplicationJson = {
	data: ResendVerificationEmailDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type resendVerificationEmailResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type resendVerificationEmailResponseSuccess =
	resendVerificationEmailResponse200 & {
		headers: Headers
	}
export type resendVerificationEmailResponseError = (
	| resendVerificationEmailResponse429
	| resendVerificationEmailResponseDefaultApplicationJson
	| resendVerificationEmailResponseDefaultTextPlain
) & {
	headers: Headers
}

export type resendVerificationEmailResponse =
	| resendVerificationEmailResponseSuccess
	| resendVerificationEmailResponseError

export const getResendVerificationEmailUrl = () => {
	return `/api/resend-verification-email`
}

export const resendVerificationEmail = async (
	resendVerificationEmailRequest: ResendVerificationEmailRequest,
	options?: RequestInit,
): Promise<resendVerificationEmailResponse> => {
	const res = await fetch(getResendVerificationEmailUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(resendVerificationEmailRequest),
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: resendVerificationEmailResponse["data"] = body
		? JSON.parse(body)
		: {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as resendVerificationEmailResponse
}

export const getResendVerificationEmailMutationOptions = <
	TError = string | ResendVerificationEmailDefaultOne,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof resendVerificationEmail>>,
		TError,
		{ data: ResendVerificationEmailRequest },
		TContext
	>
	fetch?: RequestInit
}): SolidMutationOptions<
	Awaited<ReturnType<typeof resendVerificationEmail>>,
	TError,
	{ data: ResendVerificationEmailRequest },
	TContext
> => {
	const mutationKey = ["resendVerificationEmail"]
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation
			&& "mutationKey" in options.mutation
			&& options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof resendVerificationEmail>>,
		{ data: ResendVerificationEmailRequest }
	> = (props) => {
		const { data } = props ?? {}

		return resendVerificationEmail(data, fetchOptions)
	}

	return { mutationFn, ...mutationOptions }
}

export type ResendVerificationEmailMutationResult = NonNullable<
	Awaited<ReturnType<typeof resendVerificationEmail>>
>
export type ResendVerificationEmailMutationBody = ResendVerificationEmailRequest
export type ResendVerificationEmailMutationError =
	| string
	| ResendVerificationEmailDefaultOne

export const useResendVerificationEmail = <
	TError = string | ResendVerificationEmailDefaultOne,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof resendVerificationEmail>>,
			TError,
			{ data: ResendVerificationEmailRequest },
			TContext
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof resendVerificationEmail>>,
	TError,
	{ data: ResendVerificationEmailRequest },
	TContext
> => {
	return useMutation(
		() => getResendVerificationEmailMutationOptions(options),
		queryClient,
	)
}
export type resetPasswordResponse200 = {
	data: Message
	status: 200
}

export type resetPasswordResponse429 = {
	data: string
	status: 429
}

export type resetPasswordResponseDefaultApplicationJson = {
	data: ResetPasswordDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type resetPasswordResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type resetPasswordResponseSuccess = resetPasswordResponse200 & {
	headers: Headers
}
export type resetPasswordResponseError = (
	| resetPasswordResponse429
	| resetPasswordResponseDefaultApplicationJson
	| resetPasswordResponseDefaultTextPlain
) & {
	headers: Headers
}

export type resetPasswordResponse =
	| resetPasswordResponseSuccess
	| resetPasswordResponseError

export const getResetPasswordUrl = () => {
	return `/api/reset-password`
}

export const resetPassword = async (
	resetPasswordRequest: ResetPasswordRequest,
	options?: RequestInit,
): Promise<resetPasswordResponse> => {
	const res = await fetch(getResetPasswordUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(resetPasswordRequest),
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: resetPasswordResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as resetPasswordResponse
}

export const getResetPasswordMutationOptions = <
	TError = string | ResetPasswordDefaultOne,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof resetPassword>>,
		TError,
		{ data: ResetPasswordRequest },
		TContext
	>
	fetch?: RequestInit
}): SolidMutationOptions<
	Awaited<ReturnType<typeof resetPassword>>,
	TError,
	{ data: ResetPasswordRequest },
	TContext
> => {
	const mutationKey = ["resetPassword"]
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation
			&& "mutationKey" in options.mutation
			&& options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof resetPassword>>,
		{ data: ResetPasswordRequest }
	> = (props) => {
		const { data } = props ?? {}

		return resetPassword(data, fetchOptions)
	}

	return { mutationFn, ...mutationOptions }
}

export type ResetPasswordMutationResult = NonNullable<
	Awaited<ReturnType<typeof resetPassword>>
>
export type ResetPasswordMutationBody = ResetPasswordRequest
export type ResetPasswordMutationError = string | ResetPasswordDefaultOne

export const useResetPassword = <
	TError = string | ResetPasswordDefaultOne,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof resetPassword>>,
			TError,
			{ data: ResetPasswordRequest },
			TContext
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof resetPassword>>,
	TError,
	{ data: ResetPasswordRequest },
	TContext
> => {
	return useMutation(
		() => getResetPasswordMutationOptions(options),
		queryClient,
	)
}
export type signInResponse200 = {
	data: DataUserProfile
	status: 200
}

export type signInResponse429 = {
	data: string
	status: 429
}

export type signInResponseDefaultApplicationJson = {
	data: SignInDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type signInResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type signInResponseSuccess = signInResponse200 & {
	headers: Headers
}
export type signInResponseError = (
	| signInResponse429
	| signInResponseDefaultApplicationJson
	| signInResponseDefaultTextPlain
) & {
	headers: Headers
}

export type signInResponse = signInResponseSuccess | signInResponseError

export const getSignInUrl = () => {
	return `/api/sign-in`
}

export const signIn = async (
	authCredential: AuthCredential,
	options?: RequestInit,
): Promise<signInResponse> => {
	const res = await fetch(getSignInUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(authCredential),
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: signInResponse["data"] = body ? JSON.parse(body) : {}
	return { data, status: res.status, headers: res.headers } as signInResponse
}

export const getSignInMutationOptions = <
	TError = string | SignInDefaultOne,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof signIn>>,
		TError,
		{ data: AuthCredential },
		TContext
	>
	fetch?: RequestInit
}): SolidMutationOptions<
	Awaited<ReturnType<typeof signIn>>,
	TError,
	{ data: AuthCredential },
	TContext
> => {
	const mutationKey = ["signIn"]
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation
			&& "mutationKey" in options.mutation
			&& options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof signIn>>,
		{ data: AuthCredential }
	> = (props) => {
		const { data } = props ?? {}

		return signIn(data, fetchOptions)
	}

	return { mutationFn, ...mutationOptions }
}

export type SignInMutationResult = NonNullable<
	Awaited<ReturnType<typeof signIn>>
>
export type SignInMutationBody = AuthCredential
export type SignInMutationError = string | SignInDefaultOne

export const useSignIn = <
	TError = string | SignInDefaultOne,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof signIn>>,
			TError,
			{ data: AuthCredential },
			TContext
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof signIn>>,
	TError,
	{ data: AuthCredential },
	TContext
> => {
	return useMutation(() => getSignInMutationOptions(options), queryClient)
}
export type signOutResponse200 = {
	data: Message
	status: 200
}

export type signOutResponse429 = {
	data: string
	status: 429
}

export type signOutResponseDefaultApplicationJson = {
	data: SignOutDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type signOutResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type signOutResponseSuccess = signOutResponse200 & {
	headers: Headers
}
export type signOutResponseError = (
	| signOutResponse429
	| signOutResponseDefaultApplicationJson
	| signOutResponseDefaultTextPlain
) & {
	headers: Headers
}

export type signOutResponse = signOutResponseSuccess | signOutResponseError

export const getSignOutUrl = () => {
	return `/api/sign-out`
}

export const signOut = async (
	options?: RequestInit,
): Promise<signOutResponse> => {
	const res = await fetch(getSignOutUrl(), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: signOutResponse["data"] = body ? JSON.parse(body) : {}
	return { data, status: res.status, headers: res.headers } as signOutResponse
}

export const getSignOutQueryKey = () => {
	return [`/api/sign-out`] as const
}

export const getSignOutQueryOptions = <
	TData = Awaited<ReturnType<typeof signOut>>,
	TError = string | SignOutDefaultOne,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof signOut>>, TError, TData>
	>
	fetch?: RequestInit
}) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getSignOutQueryKey()

	const queryFn: QueryFunction<Awaited<ReturnType<typeof signOut>>> = ({
		signal,
	}) => signOut({ signal, ...fetchOptions })

	return { queryKey, queryFn, ...queryOptions }
}

export type SignOutQueryResult = NonNullable<
	Awaited<ReturnType<typeof signOut>>
>
export type SignOutQueryError = string | SignOutDefaultOne

export function useSignOut<
	TData = Awaited<ReturnType<typeof signOut>>,
	TError = string | SignOutDefaultOne,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof signOut>>, TError, TData>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getSignOutQueryOptions(options)

	const query = useQuery(() => getSignOutQueryOptions(options), queryClient)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export type signUpResponse200 = {
	data: DataSignUpResponse
	status: 200
}

export type signUpResponse429 = {
	data: string
	status: 429
}

export type signUpResponseDefaultApplicationJson = {
	data: SignUpDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type signUpResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type signUpResponseSuccess = signUpResponse200 & {
	headers: Headers
}
export type signUpResponseError = (
	| signUpResponse429
	| signUpResponseDefaultApplicationJson
	| signUpResponseDefaultTextPlain
) & {
	headers: Headers
}

export type signUpResponse = signUpResponseSuccess | signUpResponseError

export const getSignUpUrl = () => {
	return `/api/sign-up`
}

export const signUp = async (
	signUpRequest: SignUpRequest,
	options?: RequestInit,
): Promise<signUpResponse> => {
	const res = await fetch(getSignUpUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(signUpRequest),
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: signUpResponse["data"] = body ? JSON.parse(body) : {}
	return { data, status: res.status, headers: res.headers } as signUpResponse
}

export const getSignUpMutationOptions = <
	TError = string | SignUpDefaultOne,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof signUp>>,
		TError,
		{ data: SignUpRequest },
		TContext
	>
	fetch?: RequestInit
}): SolidMutationOptions<
	Awaited<ReturnType<typeof signUp>>,
	TError,
	{ data: SignUpRequest },
	TContext
> => {
	const mutationKey = ["signUp"]
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation
			&& "mutationKey" in options.mutation
			&& options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof signUp>>,
		{ data: SignUpRequest }
	> = (props) => {
		const { data } = props ?? {}

		return signUp(data, fetchOptions)
	}

	return { mutationFn, ...mutationOptions }
}

export type SignUpMutationResult = NonNullable<
	Awaited<ReturnType<typeof signUp>>
>
export type SignUpMutationBody = SignUpRequest
export type SignUpMutationError = string | SignUpDefaultOne

export const useSignUp = <
	TError = string | SignUpDefaultOne,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof signUp>>,
			TError,
			{ data: SignUpRequest },
			TContext
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof signUp>>,
	TError,
	{ data: SignUpRequest },
	TContext
> => {
	return useMutation(() => getSignUpMutationOptions(options), queryClient)
}
export type verifyEmailResponse200 = {
	data: DataUserProfile
	status: 200
}

export type verifyEmailResponse429 = {
	data: string
	status: 429
}

export type verifyEmailResponseDefaultApplicationJson = {
	data: VerifyEmailDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type verifyEmailResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type verifyEmailResponseSuccess = verifyEmailResponse200 & {
	headers: Headers
}
export type verifyEmailResponseError = (
	| verifyEmailResponse429
	| verifyEmailResponseDefaultApplicationJson
	| verifyEmailResponseDefaultTextPlain
) & {
	headers: Headers
}

export type verifyEmailResponse =
	| verifyEmailResponseSuccess
	| verifyEmailResponseError

export const getVerifyEmailUrl = () => {
	return `/api/verify-email`
}

export const verifyEmail = async (
	verifyEmailRequest: VerifyEmailRequest,
	options?: RequestInit,
): Promise<verifyEmailResponse> => {
	const res = await fetch(getVerifyEmailUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(verifyEmailRequest),
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: verifyEmailResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as verifyEmailResponse
}

export const getVerifyEmailMutationOptions = <
	TError = string | VerifyEmailDefaultOne,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof verifyEmail>>,
		TError,
		{ data: VerifyEmailRequest },
		TContext
	>
	fetch?: RequestInit
}): SolidMutationOptions<
	Awaited<ReturnType<typeof verifyEmail>>,
	TError,
	{ data: VerifyEmailRequest },
	TContext
> => {
	const mutationKey = ["verifyEmail"]
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation
			&& "mutationKey" in options.mutation
			&& options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof verifyEmail>>,
		{ data: VerifyEmailRequest }
	> = (props) => {
		const { data } = props ?? {}

		return verifyEmail(data, fetchOptions)
	}

	return { mutationFn, ...mutationOptions }
}

export type VerifyEmailMutationResult = NonNullable<
	Awaited<ReturnType<typeof verifyEmail>>
>
export type VerifyEmailMutationBody = VerifyEmailRequest
export type VerifyEmailMutationError = string | VerifyEmailDefaultOne

export const useVerifyEmail = <
	TError = string | VerifyEmailDefaultOne,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof verifyEmail>>,
			TError,
			{ data: VerifyEmailRequest },
			TContext
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof verifyEmail>>,
	TError,
	{ data: VerifyEmailRequest },
	TContext
> => {
	return useMutation(() => getVerifyEmailMutationOptions(options), queryClient)
}

export const getForgotPasswordResponseMock = (
	overrideResponse: Partial<Extract<DataForgotPasswordResponse, object>> = {},
): DataForgotPasswordResponse => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: {
		verification_code_expires_minutes: faker.number.int(),
		resend_cooldown_seconds: faker.number.int(),
	},
	...overrideResponse,
})

export const getResendVerificationEmailResponseMock = (
	overrideResponse: Partial<
		Extract<DataResendVerificationEmailResponse, object>
	> = {},
): DataResendVerificationEmailResponse => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: {
		verification_code_expires_minutes: faker.number.int(),
		resend_cooldown_seconds: faker.number.int(),
	},
	...overrideResponse,
})

export const getResetPasswordResponseMock = (
	overrideResponse: Partial<Extract<Message, object>> = {},
): Message => ({
	status: faker.helpers.arrayElement(["Ok"] as const),
	message: faker.string.alpha({ length: { min: 10, max: 20 } }),
	...overrideResponse,
})

export const getSignInResponseMock = (
	overrideResponse: Partial<Extract<DataUserProfile, object>> = {},
): DataUserProfile => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: {
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		avatar_url: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		banner_url: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		last_login: faker.date.past().toISOString().slice(0, 19) + "Z",
		roles: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				name: faker.helpers.arrayElement(Object.values(UserRoleEnum)),
			})),
			undefined,
		]),
		is_following: faker.helpers.arrayElement([
			faker.datatype.boolean(),
			undefined,
		]),
		bio: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		settings: faker.helpers.arrayElement([{}, undefined]),
	},
	...overrideResponse,
})

export const getSignOutResponseMock = (
	overrideResponse: Partial<Extract<Message, object>> = {},
): Message => ({
	status: faker.helpers.arrayElement(["Ok"] as const),
	message: faker.string.alpha({ length: { min: 10, max: 20 } }),
	...overrideResponse,
})

export const getSignUpResponseMock = (
	overrideResponse: Partial<Extract<DataSignUpResponse, object>> = {},
): DataSignUpResponse => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: {
		verification_code_expires_minutes: faker.number.int(),
		resend_cooldown_seconds: faker.number.int(),
		signup_expires_hours: faker.number.int(),
	},
	...overrideResponse,
})

export const getVerifyEmailResponseMock = (
	overrideResponse: Partial<Extract<DataUserProfile, object>> = {},
): DataUserProfile => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: {
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		avatar_url: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		banner_url: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		last_login: faker.date.past().toISOString().slice(0, 19) + "Z",
		roles: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				name: faker.helpers.arrayElement(Object.values(UserRoleEnum)),
			})),
			undefined,
		]),
		is_following: faker.helpers.arrayElement([
			faker.datatype.boolean(),
			undefined,
		]),
		bio: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		settings: faker.helpers.arrayElement([{}, undefined]),
	},
	...overrideResponse,
})

export const getForgotPasswordMockHandler = (
	overrideResponse?:
		| DataForgotPasswordResponse
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<DataForgotPasswordResponse> | DataForgotPasswordResponse),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/forgot-password",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getForgotPasswordResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getResendVerificationEmailMockHandler = (
	overrideResponse?:
		| DataResendVerificationEmailResponse
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) =>
				| Promise<DataResendVerificationEmailResponse>
				| DataResendVerificationEmailResponse),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/resend-verification-email",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getResendVerificationEmailResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getResetPasswordMockHandler = (
	overrideResponse?:
		| Message
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<Message> | Message),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/reset-password",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getResetPasswordResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getSignInMockHandler = (
	overrideResponse?:
		| DataUserProfile
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<DataUserProfile> | DataUserProfile),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/sign-in",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getSignInResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getSignOutMockHandler = (
	overrideResponse?:
		| Message
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<Message> | Message),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/sign-out",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getSignOutResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getSignUpMockHandler = (
	overrideResponse?:
		| DataSignUpResponse
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<DataSignUpResponse> | DataSignUpResponse),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/sign-up",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getSignUpResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getVerifyEmailMockHandler = (
	overrideResponse?:
		| DataUserProfile
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<DataUserProfile> | DataUserProfile),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/verify-email",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getVerifyEmailResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}
export const getAuthMock = () => [
	getForgotPasswordMockHandler(),
	getResendVerificationEmailMockHandler(),
	getResetPasswordMockHandler(),
	getSignInMockHandler(),
	getSignOutMockHandler(),
	getSignUpMockHandler(),
	getVerifyEmailMockHandler(),
]
