/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Touhou Cloud DB
 * TODO
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker"
import { useMutation, useQuery } from "@tanstack/solid-query"
import type {
	DataTag,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	SolidMutationOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/solid-query"
import { HttpResponse, http } from "msw"
import type { RequestHandlerOptions } from "msw"

import type {
	CreateCreditRoleDefaultOne,
	FindCreditRoleByIdDefaultOne,
	FindManyCreditRolesSummaryDefaultOne,
	FindManyCreditRolesSummaryParams,
	NewCorrectionNewCreditRole,
	UpsertCreditRoleCorrectionDefaultOne,
} from "./touhouCloudDB.schemas"
import type {
	CreditRole,
	DataCorrectionSubmissionResult,
	DataOptionCreditRole,
	DataVecCreditRoleSummary,
} from "./touhouCloudDB.schemas"

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308
export type HTTPStatusCode4xx =
	| 400
	| 401
	| 402
	| 403
	| 404
	| 405
	| 406
	| 407
	| 408
	| 409
	| 410
	| 411
	| 412
	| 413
	| 414
	| 415
	| 416
	| 417
	| 418
	| 419
	| 420
	| 421
	| 422
	| 423
	| 424
	| 426
	| 428
	| 429
	| 431
	| 451
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511
export type HTTPStatusCodes =
	| HTTPStatusCode1xx
	| HTTPStatusCode2xx
	| HTTPStatusCode3xx
	| HTTPStatusCode4xx
	| HTTPStatusCode5xx

export type createCreditRoleResponse200 = {
	data: DataCorrectionSubmissionResult
	status: 200
}

export type createCreditRoleResponse429 = {
	data: string
	status: 429
}

export type createCreditRoleResponseDefaultApplicationJson = {
	data: CreateCreditRoleDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type createCreditRoleResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type createCreditRoleResponseSuccess = createCreditRoleResponse200 & {
	headers: Headers
}
export type createCreditRoleResponseError = (
	| createCreditRoleResponse429
	| createCreditRoleResponseDefaultApplicationJson
	| createCreditRoleResponseDefaultTextPlain
) & {
	headers: Headers
}

export type createCreditRoleResponse =
	| createCreditRoleResponseSuccess
	| createCreditRoleResponseError

export const getCreateCreditRoleUrl = () => {
	return `/api/credit-role`
}

export const createCreditRole = async (
	newCorrectionNewCreditRole: NewCorrectionNewCreditRole,
	options?: RequestInit,
): Promise<createCreditRoleResponse> => {
	const res = await fetch(getCreateCreditRoleUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(newCorrectionNewCreditRole),
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: createCreditRoleResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as createCreditRoleResponse
}

export const getCreateCreditRoleMutationOptions = <
	TError = string | CreateCreditRoleDefaultOne,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createCreditRole>>,
		TError,
		{ data: NewCorrectionNewCreditRole },
		TContext
	>
	fetch?: RequestInit
}): SolidMutationOptions<
	Awaited<ReturnType<typeof createCreditRole>>,
	TError,
	{ data: NewCorrectionNewCreditRole },
	TContext
> => {
	const mutationKey = ["createCreditRole"]
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation
			&& "mutationKey" in options.mutation
			&& options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createCreditRole>>,
		{ data: NewCorrectionNewCreditRole }
	> = (props) => {
		const { data } = props ?? {}

		return createCreditRole(data, fetchOptions)
	}

	return { mutationFn, ...mutationOptions }
}

export type CreateCreditRoleMutationResult = NonNullable<
	Awaited<ReturnType<typeof createCreditRole>>
>
export type CreateCreditRoleMutationBody = NewCorrectionNewCreditRole
export type CreateCreditRoleMutationError = string | CreateCreditRoleDefaultOne

export const useCreateCreditRole = <
	TError = string | CreateCreditRoleDefaultOne,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createCreditRole>>,
			TError,
			{ data: NewCorrectionNewCreditRole },
			TContext
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createCreditRole>>,
	TError,
	{ data: NewCorrectionNewCreditRole },
	TContext
> => {
	return useMutation(
		() => getCreateCreditRoleMutationOptions(options),
		queryClient,
	)
}
export type findManyCreditRolesSummaryResponse200 = {
	data: DataVecCreditRoleSummary
	status: 200
}

export type findManyCreditRolesSummaryResponse429 = {
	data: string
	status: 429
}

export type findManyCreditRolesSummaryResponseDefaultApplicationJson = {
	data: FindManyCreditRolesSummaryDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type findManyCreditRolesSummaryResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type findManyCreditRolesSummaryResponseSuccess =
	findManyCreditRolesSummaryResponse200 & {
		headers: Headers
	}
export type findManyCreditRolesSummaryResponseError = (
	| findManyCreditRolesSummaryResponse429
	| findManyCreditRolesSummaryResponseDefaultApplicationJson
	| findManyCreditRolesSummaryResponseDefaultTextPlain
) & {
	headers: Headers
}

export type findManyCreditRolesSummaryResponse =
	| findManyCreditRolesSummaryResponseSuccess
	| findManyCreditRolesSummaryResponseError

export const getFindManyCreditRolesSummaryUrl = (
	params: FindManyCreditRolesSummaryParams,
) => {
	const normalizedParams = new URLSearchParams()

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString())
		}
	})

	const stringifiedParams = normalizedParams.toString()

	return stringifiedParams.length > 0
		? `/api/credit-role/summary?${stringifiedParams}`
		: `/api/credit-role/summary`
}

export const findManyCreditRolesSummary = async (
	params: FindManyCreditRolesSummaryParams,
	options?: RequestInit,
): Promise<findManyCreditRolesSummaryResponse> => {
	const res = await fetch(getFindManyCreditRolesSummaryUrl(params), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: findManyCreditRolesSummaryResponse["data"] = body
		? JSON.parse(body)
		: {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as findManyCreditRolesSummaryResponse
}

export const getFindManyCreditRolesSummaryQueryKey = (
	params?: FindManyCreditRolesSummaryParams,
) => {
	return [`/api/credit-role/summary`, ...(params ? [params] : [])] as const
}

export const getFindManyCreditRolesSummaryQueryOptions = <
	TData = Awaited<ReturnType<typeof findManyCreditRolesSummary>>,
	TError = string | FindManyCreditRolesSummaryDefaultOne,
>(
	params: FindManyCreditRolesSummaryParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof findManyCreditRolesSummary>>,
				TError,
				TData
			>
		>
		fetch?: RequestInit
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getFindManyCreditRolesSummaryQueryKey(params)

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof findManyCreditRolesSummary>>
	> = ({ signal }) =>
		findManyCreditRolesSummary(params, { signal, ...fetchOptions })

	return { queryKey, queryFn, ...queryOptions }
}

export type FindManyCreditRolesSummaryQueryResult = NonNullable<
	Awaited<ReturnType<typeof findManyCreditRolesSummary>>
>
export type FindManyCreditRolesSummaryQueryError =
	| string
	| FindManyCreditRolesSummaryDefaultOne

export function useFindManyCreditRolesSummary<
	TData = Awaited<ReturnType<typeof findManyCreditRolesSummary>>,
	TError = string | FindManyCreditRolesSummaryDefaultOne,
>(
	params: FindManyCreditRolesSummaryParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof findManyCreditRolesSummary>>,
				TError,
				TData
			>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getFindManyCreditRolesSummaryQueryOptions(
		params,
		options,
	)

	const query = useQuery(
		() => getFindManyCreditRolesSummaryQueryOptions(params, options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export type findCreditRoleByIdResponse200 = {
	data: DataOptionCreditRole
	status: 200
}

export type findCreditRoleByIdResponse429 = {
	data: string
	status: 429
}

export type findCreditRoleByIdResponseDefaultApplicationJson = {
	data: FindCreditRoleByIdDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type findCreditRoleByIdResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type findCreditRoleByIdResponseSuccess =
	findCreditRoleByIdResponse200 & {
		headers: Headers
	}
export type findCreditRoleByIdResponseError = (
	| findCreditRoleByIdResponse429
	| findCreditRoleByIdResponseDefaultApplicationJson
	| findCreditRoleByIdResponseDefaultTextPlain
) & {
	headers: Headers
}

export type findCreditRoleByIdResponse =
	| findCreditRoleByIdResponseSuccess
	| findCreditRoleByIdResponseError

export const getFindCreditRoleByIdUrl = (id: number) => {
	return `/api/credit-role/${id}`
}

export const findCreditRoleById = async (
	id: number,
	options?: RequestInit,
): Promise<findCreditRoleByIdResponse> => {
	const res = await fetch(getFindCreditRoleByIdUrl(id), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: findCreditRoleByIdResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as findCreditRoleByIdResponse
}

export const getFindCreditRoleByIdQueryKey = (id: number) => {
	return [`/api/credit-role/${id}`] as const
}

export const getFindCreditRoleByIdQueryOptions = <
	TData = Awaited<ReturnType<typeof findCreditRoleById>>,
	TError = string | FindCreditRoleByIdDefaultOne,
>(
	id: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof findCreditRoleById>>,
				TError,
				TData
			>
		>
		fetch?: RequestInit
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getFindCreditRoleByIdQueryKey(id)

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof findCreditRoleById>>
	> = ({ signal }) => findCreditRoleById(id, { signal, ...fetchOptions })

	return { queryKey, queryFn, enabled: !!id, ...queryOptions }
}

export type FindCreditRoleByIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof findCreditRoleById>>
>
export type FindCreditRoleByIdQueryError = string | FindCreditRoleByIdDefaultOne

export function useFindCreditRoleById<
	TData = Awaited<ReturnType<typeof findCreditRoleById>>,
	TError = string | FindCreditRoleByIdDefaultOne,
>(
	id: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof findCreditRoleById>>,
				TError,
				TData
			>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getFindCreditRoleByIdQueryOptions(id, options)

	const query = useQuery(
		() => getFindCreditRoleByIdQueryOptions(id, options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export type upsertCreditRoleCorrectionResponse200 = {
	data: DataCorrectionSubmissionResult
	status: 200
}

export type upsertCreditRoleCorrectionResponse429 = {
	data: string
	status: 429
}

export type upsertCreditRoleCorrectionResponseDefaultApplicationJson = {
	data: UpsertCreditRoleCorrectionDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type upsertCreditRoleCorrectionResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type upsertCreditRoleCorrectionResponseSuccess =
	upsertCreditRoleCorrectionResponse200 & {
		headers: Headers
	}
export type upsertCreditRoleCorrectionResponseError = (
	| upsertCreditRoleCorrectionResponse429
	| upsertCreditRoleCorrectionResponseDefaultApplicationJson
	| upsertCreditRoleCorrectionResponseDefaultTextPlain
) & {
	headers: Headers
}

export type upsertCreditRoleCorrectionResponse =
	| upsertCreditRoleCorrectionResponseSuccess
	| upsertCreditRoleCorrectionResponseError

export const getUpsertCreditRoleCorrectionUrl = (id: number) => {
	return `/api/credit-role/${id}`
}

export const upsertCreditRoleCorrection = async (
	id: number,
	newCorrectionNewCreditRole: NewCorrectionNewCreditRole,
	options?: RequestInit,
): Promise<upsertCreditRoleCorrectionResponse> => {
	const res = await fetch(getUpsertCreditRoleCorrectionUrl(id), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(newCorrectionNewCreditRole),
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: upsertCreditRoleCorrectionResponse["data"] = body
		? JSON.parse(body)
		: {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as upsertCreditRoleCorrectionResponse
}

export const getUpsertCreditRoleCorrectionMutationOptions = <
	TError = string | UpsertCreditRoleCorrectionDefaultOne,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof upsertCreditRoleCorrection>>,
		TError,
		{ id: number; data: NewCorrectionNewCreditRole },
		TContext
	>
	fetch?: RequestInit
}): SolidMutationOptions<
	Awaited<ReturnType<typeof upsertCreditRoleCorrection>>,
	TError,
	{ id: number; data: NewCorrectionNewCreditRole },
	TContext
> => {
	const mutationKey = ["upsertCreditRoleCorrection"]
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation
			&& "mutationKey" in options.mutation
			&& options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof upsertCreditRoleCorrection>>,
		{ id: number; data: NewCorrectionNewCreditRole }
	> = (props) => {
		const { id, data } = props ?? {}

		return upsertCreditRoleCorrection(id, data, fetchOptions)
	}

	return { mutationFn, ...mutationOptions }
}

export type UpsertCreditRoleCorrectionMutationResult = NonNullable<
	Awaited<ReturnType<typeof upsertCreditRoleCorrection>>
>
export type UpsertCreditRoleCorrectionMutationBody = NewCorrectionNewCreditRole
export type UpsertCreditRoleCorrectionMutationError =
	| string
	| UpsertCreditRoleCorrectionDefaultOne

export const useUpsertCreditRoleCorrection = <
	TError = string | UpsertCreditRoleCorrectionDefaultOne,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof upsertCreditRoleCorrection>>,
			TError,
			{ id: number; data: NewCorrectionNewCreditRole },
			TContext
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof upsertCreditRoleCorrection>>,
	TError,
	{ id: number; data: NewCorrectionNewCreditRole },
	TContext
> => {
	return useMutation(
		() => getUpsertCreditRoleCorrectionMutationOptions(options),
		queryClient,
	)
}

export const getCreateCreditRoleResponseMock = (
	overrideResponse: Partial<
		Extract<DataCorrectionSubmissionResult, object>
	> = {},
): DataCorrectionSubmissionResult => ({
	status: faker.helpers.arrayElement(["Ok"] as const),
	data: { correction_id: faker.number.int(), entity_id: faker.number.int() },
	...overrideResponse,
})

export const getFindManyCreditRolesSummaryResponseMock = (
	overrideResponse: Partial<Extract<DataVecCreditRoleSummary, object>> = {},
): DataVecCreditRoleSummary => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int(),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		short_description: faker.string.alpha({ length: { min: 10, max: 20 } }),
	})),
	...overrideResponse,
})

export const getFindCreditRoleByIdResponseCreditRoleMock = (
	overrideResponse: Partial<CreditRole> = {},
): CreditRole => ({
	...{
		id: faker.number.int(),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		short_description: faker.string.alpha({ length: { min: 10, max: 20 } }),
		description: faker.string.alpha({ length: { min: 10, max: 20 } }),
	},
	...overrideResponse,
})

export const getFindCreditRoleByIdResponseMock = (
	overrideResponse: Partial<Extract<DataOptionCreditRole, object>> = {},
): DataOptionCreditRole => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: faker.helpers.arrayElement([
		null,
		{ ...getFindCreditRoleByIdResponseCreditRoleMock() },
	]),
	...overrideResponse,
})

export const getUpsertCreditRoleCorrectionResponseMock = (
	overrideResponse: Partial<
		Extract<DataCorrectionSubmissionResult, object>
	> = {},
): DataCorrectionSubmissionResult => ({
	status: faker.helpers.arrayElement(["Ok"] as const),
	data: { correction_id: faker.number.int(), entity_id: faker.number.int() },
	...overrideResponse,
})

export const getCreateCreditRoleMockHandler = (
	overrideResponse?:
		| DataCorrectionSubmissionResult
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) =>
				| Promise<DataCorrectionSubmissionResult>
				| DataCorrectionSubmissionResult),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/credit-role",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getCreateCreditRoleResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getFindManyCreditRolesSummaryMockHandler = (
	overrideResponse?:
		| DataVecCreditRoleSummary
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<DataVecCreditRoleSummary> | DataVecCreditRoleSummary),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/credit-role/summary",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getFindManyCreditRolesSummaryResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getFindCreditRoleByIdMockHandler = (
	overrideResponse?:
		| DataOptionCreditRole
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<DataOptionCreditRole> | DataOptionCreditRole),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/credit-role/:id",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getFindCreditRoleByIdResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getUpsertCreditRoleCorrectionMockHandler = (
	overrideResponse?:
		| DataCorrectionSubmissionResult
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) =>
				| Promise<DataCorrectionSubmissionResult>
				| DataCorrectionSubmissionResult),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/credit-role/:id",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getUpsertCreditRoleCorrectionResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}
export const getCreditRoleMock = () => [
	getCreateCreditRoleMockHandler(),
	getFindManyCreditRolesSummaryMockHandler(),
	getFindCreditRoleByIdMockHandler(),
	getUpsertCreditRoleCorrectionMockHandler(),
]
