/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Touhou Cloud DB
 * TODO
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker"
import { useMutation, useQuery } from "@tanstack/solid-query"
import type {
	DataTag,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	SolidMutationOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/solid-query"
import { HttpResponse, http } from "msw"
import type { RequestHandlerOptions } from "msw"

import type {
	HandleImageQueueDefaultOne,
	HandleImageQueueParams,
	ImageQueueDetailDefaultOne,
	PendingImageQueueCountDefaultOne,
	PendingImageQueueDefaultOne,
	PendingImageQueueParams,
	UserImageQueueDefaultOne,
	UserImageQueueParams,
} from "./touhouCloudDB.schemas"
import {
	ArtistImageType,
	ImageQueueStatus,
	ReleaseImageType,
} from "./touhouCloudDB.schemas"
import type {
	ArtistImageQueueTarget,
	DataImageQueueDetail,
	DataPaginatedPendingImageQueueItem,
	DataPaginatedUserImageQueueItem,
	DataPendingImageQueueCount,
	ImageSummary,
	Message,
	ReleaseImageQueueTarget,
	UserSummary,
} from "./touhouCloudDB.schemas"

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308
export type HTTPStatusCode4xx =
	| 400
	| 401
	| 402
	| 403
	| 404
	| 405
	| 406
	| 407
	| 408
	| 409
	| 410
	| 411
	| 412
	| 413
	| 414
	| 415
	| 416
	| 417
	| 418
	| 419
	| 420
	| 421
	| 422
	| 423
	| 424
	| 426
	| 428
	| 429
	| 431
	| 451
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511
export type HTTPStatusCodes =
	| HTTPStatusCode1xx
	| HTTPStatusCode2xx
	| HTTPStatusCode3xx
	| HTTPStatusCode4xx
	| HTTPStatusCode5xx

export type pendingImageQueueResponse200 = {
	data: DataPaginatedPendingImageQueueItem
	status: 200
}

export type pendingImageQueueResponse429 = {
	data: string
	status: 429
}

export type pendingImageQueueResponseDefaultApplicationJson = {
	data: PendingImageQueueDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type pendingImageQueueResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type pendingImageQueueResponseSuccess = pendingImageQueueResponse200 & {
	headers: Headers
}
export type pendingImageQueueResponseError = (
	| pendingImageQueueResponse429
	| pendingImageQueueResponseDefaultApplicationJson
	| pendingImageQueueResponseDefaultTextPlain
) & {
	headers: Headers
}

export type pendingImageQueueResponse =
	| pendingImageQueueResponseSuccess
	| pendingImageQueueResponseError

export const getPendingImageQueueUrl = (params?: PendingImageQueueParams) => {
	const normalizedParams = new URLSearchParams()

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString())
		}
	})

	const stringifiedParams = normalizedParams.toString()

	return stringifiedParams.length > 0
		? `/api/image-queue?${stringifiedParams}`
		: `/api/image-queue`
}

export const pendingImageQueue = async (
	params?: PendingImageQueueParams,
	options?: RequestInit,
): Promise<pendingImageQueueResponse> => {
	const res = await fetch(getPendingImageQueueUrl(params), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: pendingImageQueueResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as pendingImageQueueResponse
}

export const getPendingImageQueueQueryKey = (
	params?: PendingImageQueueParams,
) => {
	return [`/api/image-queue`, ...(params ? [params] : [])] as const
}

export const getPendingImageQueueQueryOptions = <
	TData = Awaited<ReturnType<typeof pendingImageQueue>>,
	TError = string | PendingImageQueueDefaultOne,
>(
	params?: PendingImageQueueParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof pendingImageQueue>>,
				TError,
				TData
			>
		>
		fetch?: RequestInit
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getPendingImageQueueQueryKey(params)

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof pendingImageQueue>>
	> = ({ signal }) => pendingImageQueue(params, { signal, ...fetchOptions })

	return { queryKey, queryFn, ...queryOptions }
}

export type PendingImageQueueQueryResult = NonNullable<
	Awaited<ReturnType<typeof pendingImageQueue>>
>
export type PendingImageQueueQueryError = string | PendingImageQueueDefaultOne

export function usePendingImageQueue<
	TData = Awaited<ReturnType<typeof pendingImageQueue>>,
	TError = string | PendingImageQueueDefaultOne,
>(
	params?: PendingImageQueueParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof pendingImageQueue>>,
				TError,
				TData
			>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getPendingImageQueueQueryOptions(params, options)

	const query = useQuery(
		() => getPendingImageQueueQueryOptions(params, options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export type pendingImageQueueCountResponse200 = {
	data: DataPendingImageQueueCount
	status: 200
}

export type pendingImageQueueCountResponse429 = {
	data: string
	status: 429
}

export type pendingImageQueueCountResponseDefaultApplicationJson = {
	data: PendingImageQueueCountDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type pendingImageQueueCountResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type pendingImageQueueCountResponseSuccess =
	pendingImageQueueCountResponse200 & {
		headers: Headers
	}
export type pendingImageQueueCountResponseError = (
	| pendingImageQueueCountResponse429
	| pendingImageQueueCountResponseDefaultApplicationJson
	| pendingImageQueueCountResponseDefaultTextPlain
) & {
	headers: Headers
}

export type pendingImageQueueCountResponse =
	| pendingImageQueueCountResponseSuccess
	| pendingImageQueueCountResponseError

export const getPendingImageQueueCountUrl = () => {
	return `/api/image-queue/pending-count`
}

export const pendingImageQueueCount = async (
	options?: RequestInit,
): Promise<pendingImageQueueCountResponse> => {
	const res = await fetch(getPendingImageQueueCountUrl(), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: pendingImageQueueCountResponse["data"] = body
		? JSON.parse(body)
		: {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as pendingImageQueueCountResponse
}

export const getPendingImageQueueCountQueryKey = () => {
	return [`/api/image-queue/pending-count`] as const
}

export const getPendingImageQueueCountQueryOptions = <
	TData = Awaited<ReturnType<typeof pendingImageQueueCount>>,
	TError = string | PendingImageQueueCountDefaultOne,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof pendingImageQueueCount>>,
			TError,
			TData
		>
	>
	fetch?: RequestInit
}) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getPendingImageQueueCountQueryKey()

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof pendingImageQueueCount>>
	> = ({ signal }) => pendingImageQueueCount({ signal, ...fetchOptions })

	return { queryKey, queryFn, ...queryOptions }
}

export type PendingImageQueueCountQueryResult = NonNullable<
	Awaited<ReturnType<typeof pendingImageQueueCount>>
>
export type PendingImageQueueCountQueryError =
	| string
	| PendingImageQueueCountDefaultOne

export function usePendingImageQueueCount<
	TData = Awaited<ReturnType<typeof pendingImageQueueCount>>,
	TError = string | PendingImageQueueCountDefaultOne,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof pendingImageQueueCount>>,
				TError,
				TData
			>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getPendingImageQueueCountQueryOptions(options)

	const query = useQuery(
		() => getPendingImageQueueCountQueryOptions(options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export type imageQueueDetailResponse200 = {
	data: DataImageQueueDetail
	status: 200
}

export type imageQueueDetailResponse429 = {
	data: string
	status: 429
}

export type imageQueueDetailResponseDefaultApplicationJson = {
	data: ImageQueueDetailDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type imageQueueDetailResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type imageQueueDetailResponseSuccess = imageQueueDetailResponse200 & {
	headers: Headers
}
export type imageQueueDetailResponseError = (
	| imageQueueDetailResponse429
	| imageQueueDetailResponseDefaultApplicationJson
	| imageQueueDetailResponseDefaultTextPlain
) & {
	headers: Headers
}

export type imageQueueDetailResponse =
	| imageQueueDetailResponseSuccess
	| imageQueueDetailResponseError

export const getImageQueueDetailUrl = (id: number) => {
	return `/api/image-queue/${id}`
}

export const imageQueueDetail = async (
	id: number,
	options?: RequestInit,
): Promise<imageQueueDetailResponse> => {
	const res = await fetch(getImageQueueDetailUrl(id), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: imageQueueDetailResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as imageQueueDetailResponse
}

export const getImageQueueDetailQueryKey = (id: number) => {
	return [`/api/image-queue/${id}`] as const
}

export const getImageQueueDetailQueryOptions = <
	TData = Awaited<ReturnType<typeof imageQueueDetail>>,
	TError = string | ImageQueueDetailDefaultOne,
>(
	id: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof imageQueueDetail>>,
				TError,
				TData
			>
		>
		fetch?: RequestInit
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getImageQueueDetailQueryKey(id)

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof imageQueueDetail>>
	> = ({ signal }) => imageQueueDetail(id, { signal, ...fetchOptions })

	return { queryKey, queryFn, enabled: !!id, ...queryOptions }
}

export type ImageQueueDetailQueryResult = NonNullable<
	Awaited<ReturnType<typeof imageQueueDetail>>
>
export type ImageQueueDetailQueryError = string | ImageQueueDetailDefaultOne

export function useImageQueueDetail<
	TData = Awaited<ReturnType<typeof imageQueueDetail>>,
	TError = string | ImageQueueDetailDefaultOne,
>(
	id: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof imageQueueDetail>>,
				TError,
				TData
			>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getImageQueueDetailQueryOptions(id, options)

	const query = useQuery(
		() => getImageQueueDetailQueryOptions(id, options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export type handleImageQueueResponse200 = {
	data: Message
	status: 200
}

export type handleImageQueueResponse429 = {
	data: string
	status: 429
}

export type handleImageQueueResponseDefaultApplicationJson = {
	data: HandleImageQueueDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type handleImageQueueResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type handleImageQueueResponseSuccess = handleImageQueueResponse200 & {
	headers: Headers
}
export type handleImageQueueResponseError = (
	| handleImageQueueResponse429
	| handleImageQueueResponseDefaultApplicationJson
	| handleImageQueueResponseDefaultTextPlain
) & {
	headers: Headers
}

export type handleImageQueueResponse =
	| handleImageQueueResponseSuccess
	| handleImageQueueResponseError

export const getHandleImageQueueUrl = (
	id: number,
	params: HandleImageQueueParams,
) => {
	const normalizedParams = new URLSearchParams()

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString())
		}
	})

	const stringifiedParams = normalizedParams.toString()

	return stringifiedParams.length > 0
		? `/api/image-queue/${id}?${stringifiedParams}`
		: `/api/image-queue/${id}`
}

export const handleImageQueue = async (
	id: number,
	params: HandleImageQueueParams,
	options?: RequestInit,
): Promise<handleImageQueueResponse> => {
	const res = await fetch(getHandleImageQueueUrl(id, params), {
		...options,
		method: "POST",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: handleImageQueueResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as handleImageQueueResponse
}

export const getHandleImageQueueMutationOptions = <
	TError = string | HandleImageQueueDefaultOne,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof handleImageQueue>>,
		TError,
		{ id: number; params: HandleImageQueueParams },
		TContext
	>
	fetch?: RequestInit
}): SolidMutationOptions<
	Awaited<ReturnType<typeof handleImageQueue>>,
	TError,
	{ id: number; params: HandleImageQueueParams },
	TContext
> => {
	const mutationKey = ["handleImageQueue"]
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation
			&& "mutationKey" in options.mutation
			&& options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof handleImageQueue>>,
		{ id: number; params: HandleImageQueueParams }
	> = (props) => {
		const { id, params } = props ?? {}

		return handleImageQueue(id, params, fetchOptions)
	}

	return { mutationFn, ...mutationOptions }
}

export type HandleImageQueueMutationResult = NonNullable<
	Awaited<ReturnType<typeof handleImageQueue>>
>

export type HandleImageQueueMutationError = string | HandleImageQueueDefaultOne

export const useHandleImageQueue = <
	TError = string | HandleImageQueueDefaultOne,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof handleImageQueue>>,
			TError,
			{ id: number; params: HandleImageQueueParams },
			TContext
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof handleImageQueue>>,
	TError,
	{ id: number; params: HandleImageQueueParams },
	TContext
> => {
	return useMutation(
		() => getHandleImageQueueMutationOptions(options),
		queryClient,
	)
}
export type userImageQueueResponse200 = {
	data: DataPaginatedUserImageQueueItem
	status: 200
}

export type userImageQueueResponse429 = {
	data: string
	status: 429
}

export type userImageQueueResponseDefaultApplicationJson = {
	data: UserImageQueueDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type userImageQueueResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type userImageQueueResponseSuccess = userImageQueueResponse200 & {
	headers: Headers
}
export type userImageQueueResponseError = (
	| userImageQueueResponse429
	| userImageQueueResponseDefaultApplicationJson
	| userImageQueueResponseDefaultTextPlain
) & {
	headers: Headers
}

export type userImageQueueResponse =
	| userImageQueueResponseSuccess
	| userImageQueueResponseError

export const getUserImageQueueUrl = (
	id: number,
	params?: UserImageQueueParams,
) => {
	const normalizedParams = new URLSearchParams()

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString())
		}
	})

	const stringifiedParams = normalizedParams.toString()

	return stringifiedParams.length > 0
		? `/api/user/${id}/image-queue?${stringifiedParams}`
		: `/api/user/${id}/image-queue`
}

export const userImageQueue = async (
	id: number,
	params?: UserImageQueueParams,
	options?: RequestInit,
): Promise<userImageQueueResponse> => {
	const res = await fetch(getUserImageQueueUrl(id, params), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: userImageQueueResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as userImageQueueResponse
}

export const getUserImageQueueQueryKey = (
	id: number,
	params?: UserImageQueueParams,
) => {
	return [`/api/user/${id}/image-queue`, ...(params ? [params] : [])] as const
}

export const getUserImageQueueQueryOptions = <
	TData = Awaited<ReturnType<typeof userImageQueue>>,
	TError = string | UserImageQueueDefaultOne,
>(
	id: number,
	params?: UserImageQueueParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof userImageQueue>>, TError, TData>
		>
		fetch?: RequestInit
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getUserImageQueueQueryKey(id, params)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof userImageQueue>>> = ({
		signal,
	}) => userImageQueue(id, params, { signal, ...fetchOptions })

	return { queryKey, queryFn, enabled: !!id, ...queryOptions }
}

export type UserImageQueueQueryResult = NonNullable<
	Awaited<ReturnType<typeof userImageQueue>>
>
export type UserImageQueueQueryError = string | UserImageQueueDefaultOne

export function useUserImageQueue<
	TData = Awaited<ReturnType<typeof userImageQueue>>,
	TError = string | UserImageQueueDefaultOne,
>(
	id: number,
	params?: UserImageQueueParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof userImageQueue>>, TError, TData>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getUserImageQueueQueryOptions(id, params, options)

	const query = useQuery(
		() => getUserImageQueueQueryOptions(id, params, options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export const getPendingImageQueueResponseMock = (
	overrideResponse: Partial<
		Extract<DataPaginatedPendingImageQueueItem, object>
	> = {},
): DataPaginatedPendingImageQueueItem => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: {
		items: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int(),
			image_id: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
			status: faker.helpers.arrayElement(Object.values(ImageQueueStatus)),
			created_at: faker.date.past().toISOString().slice(0, 19) + "Z",
			created_by: {
				id: faker.number.int(),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			},
		})),
		next_cursor: faker.helpers.arrayElement([
			faker.helpers.arrayElement([faker.number.int(), null]),
			undefined,
		]),
	},
	...overrideResponse,
})

export const getPendingImageQueueCountResponseMock = (
	overrideResponse: Partial<Extract<DataPendingImageQueueCount, object>> = {},
): DataPendingImageQueueCount => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: faker.number.int({ min: 0 }),
	...overrideResponse,
})

export const getImageQueueDetailResponseUserSummaryMock = (
	overrideResponse: Partial<UserSummary> = {},
): UserSummary => ({
	...{
		id: faker.number.int(),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	},
	...overrideResponse,
})

export const getImageQueueDetailResponseImageSummaryMock = (
	overrideResponse: Partial<ImageSummary> = {},
): ImageSummary => ({
	...{
		id: faker.number.int(),
		filename: faker.string.alpha({ length: { min: 10, max: 20 } }),
		directory: faker.string.alpha({ length: { min: 10, max: 20 } }),
		uploaded_at: faker.date.past().toISOString().slice(0, 19) + "Z",
		uploaded_by: {
			id: faker.number.int(),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		},
	},
	...overrideResponse,
})

export const getImageQueueDetailResponseArtistImageQueueTargetMock = (
	overrideResponse: Partial<ArtistImageQueueTarget> = {},
): ArtistImageQueueTarget => ({
	...{
		artist_id: faker.number.int(),
		type: faker.helpers.arrayElement(Object.values(ArtistImageType)),
	},
	...overrideResponse,
})

export const getImageQueueDetailResponseReleaseImageQueueTargetMock = (
	overrideResponse: Partial<ReleaseImageQueueTarget> = {},
): ReleaseImageQueueTarget => ({
	...{
		release_id: faker.number.int(),
		type: faker.helpers.arrayElement(Object.values(ReleaseImageType)),
	},
	...overrideResponse,
})

export const getImageQueueDetailResponseMock = (
	overrideResponse: Partial<Extract<DataImageQueueDetail, object>> = {},
): DataImageQueueDetail => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: {
		id: faker.number.int(),
		image_id: faker.helpers.arrayElement([
			faker.helpers.arrayElement([faker.number.int(), null]),
			undefined,
		]),
		status: faker.helpers.arrayElement(Object.values(ImageQueueStatus)),
		created_at: faker.date.past().toISOString().slice(0, 19) + "Z",
		created_by: {
			id: faker.number.int(),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		},
		handled_at: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.date.past().toISOString().slice(0, 19) + "Z",
				null,
			]),
			undefined,
		]),
		handled_by: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				null,
				{ ...getImageQueueDetailResponseUserSummaryMock() },
			]),
			undefined,
		]),
		reverted_at: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.date.past().toISOString().slice(0, 19) + "Z",
				null,
			]),
			undefined,
		]),
		reverted_by: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				null,
				{ ...getImageQueueDetailResponseUserSummaryMock() },
			]),
			undefined,
		]),
		image: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				null,
				{ ...getImageQueueDetailResponseImageSummaryMock() },
			]),
			undefined,
		]),
		artist: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				null,
				{ ...getImageQueueDetailResponseArtistImageQueueTargetMock() },
			]),
			undefined,
		]),
		release: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				null,
				{ ...getImageQueueDetailResponseReleaseImageQueueTargetMock() },
			]),
			undefined,
		]),
	},
	...overrideResponse,
})

export const getHandleImageQueueResponseMock = (
	overrideResponse: Partial<Extract<Message, object>> = {},
): Message => ({
	status: faker.helpers.arrayElement(["Ok"] as const),
	message: faker.string.alpha({ length: { min: 10, max: 20 } }),
	...overrideResponse,
})

export const getUserImageQueueResponseUserSummaryMock = (
	overrideResponse: Partial<UserSummary> = {},
): UserSummary => ({
	...{
		id: faker.number.int(),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	},
	...overrideResponse,
})

export const getUserImageQueueResponseMock = (
	overrideResponse: Partial<
		Extract<DataPaginatedUserImageQueueItem, object>
	> = {},
): DataPaginatedUserImageQueueItem => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: {
		items: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int(),
			image_id: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
			status: faker.helpers.arrayElement(Object.values(ImageQueueStatus)),
			created_at: faker.date.past().toISOString().slice(0, 19) + "Z",
			handled_at: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.date.past().toISOString().slice(0, 19) + "Z",
					null,
				]),
				undefined,
			]),
			handled_by: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					null,
					{ ...getUserImageQueueResponseUserSummaryMock() },
				]),
				undefined,
			]),
			reverted_at: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.date.past().toISOString().slice(0, 19) + "Z",
					null,
				]),
				undefined,
			]),
			reverted_by: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					null,
					{ ...getUserImageQueueResponseUserSummaryMock() },
				]),
				undefined,
			]),
		})),
		next_cursor: faker.helpers.arrayElement([
			faker.helpers.arrayElement([faker.number.int(), null]),
			undefined,
		]),
	},
	...overrideResponse,
})

export const getPendingImageQueueMockHandler = (
	overrideResponse?:
		| DataPaginatedPendingImageQueueItem
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) =>
				| Promise<DataPaginatedPendingImageQueueItem>
				| DataPaginatedPendingImageQueueItem),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/image-queue",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getPendingImageQueueResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getPendingImageQueueCountMockHandler = (
	overrideResponse?:
		| DataPendingImageQueueCount
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<DataPendingImageQueueCount> | DataPendingImageQueueCount),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/image-queue/pending-count",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getPendingImageQueueCountResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getImageQueueDetailMockHandler = (
	overrideResponse?:
		| DataImageQueueDetail
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<DataImageQueueDetail> | DataImageQueueDetail),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/image-queue/:id",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getImageQueueDetailResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getHandleImageQueueMockHandler = (
	overrideResponse?:
		| Message
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<Message> | Message),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/image-queue/:id",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getHandleImageQueueResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getUserImageQueueMockHandler = (
	overrideResponse?:
		| DataPaginatedUserImageQueueItem
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) =>
				| Promise<DataPaginatedUserImageQueueItem>
				| DataPaginatedUserImageQueueItem),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/user/:id/image-queue",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getUserImageQueueResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}
export const getImageQueueMock = () => [
	getPendingImageQueueMockHandler(),
	getPendingImageQueueCountMockHandler(),
	getImageQueueDetailMockHandler(),
	getHandleImageQueueMockHandler(),
	getUserImageQueueMockHandler(),
]
