/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Touhou Cloud DB
 * TODO
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker"
import { useMutation, useQuery } from "@tanstack/solid-query"
import type {
	DataTag,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	SolidMutationOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/solid-query"
import { HttpResponse, http } from "msw"
import type { RequestHandlerOptions } from "msw"

import type {
	CreateReleaseDefaultOne,
	ExploreRelease400,
	ExploreRelease500,
	ExploreReleaseDefaultOne,
	ExploreReleaseParams,
	FindReleaseByIdDefaultOne,
	FindReleaseByKeywordDefaultOne,
	FindReleaseByKeywordParams,
	GetReleaseCoverArtMetadataDefaultOne,
	NewCorrectionNewRelease,
	ReleaseCoverArtFormData,
	UpdateReleaseDefaultOne,
	UploadReleaseCoverArtDefaultOne,
} from "./touhouCloudDB.schemas"
import { DatePrecision, ReleaseType } from "./touhouCloudDB.schemas"
import type {
	DataCorrectionSubmissionResult,
	DataI32,
	DataOptionCurrentImageMetadata,
	DataOptionRelease,
	DataPageRelease,
	DataVecRelease,
	DateWithPrecision,
	Release,
	SimpleLabel,
} from "./touhouCloudDB.schemas"

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308
export type HTTPStatusCode4xx =
	| 400
	| 401
	| 402
	| 403
	| 404
	| 405
	| 406
	| 407
	| 408
	| 409
	| 410
	| 411
	| 412
	| 413
	| 414
	| 415
	| 416
	| 417
	| 418
	| 419
	| 420
	| 421
	| 422
	| 423
	| 424
	| 426
	| 428
	| 429
	| 431
	| 451
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511
export type HTTPStatusCodes =
	| HTTPStatusCode1xx
	| HTTPStatusCode2xx
	| HTTPStatusCode3xx
	| HTTPStatusCode4xx
	| HTTPStatusCode5xx

export type findReleaseByKeywordResponse200 = {
	data: DataVecRelease
	status: 200
}

export type findReleaseByKeywordResponse429 = {
	data: string
	status: 429
}

export type findReleaseByKeywordResponseDefaultApplicationJson = {
	data: FindReleaseByKeywordDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type findReleaseByKeywordResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type findReleaseByKeywordResponseSuccess =
	findReleaseByKeywordResponse200 & {
		headers: Headers
	}
export type findReleaseByKeywordResponseError = (
	| findReleaseByKeywordResponse429
	| findReleaseByKeywordResponseDefaultApplicationJson
	| findReleaseByKeywordResponseDefaultTextPlain
) & {
	headers: Headers
}

export type findReleaseByKeywordResponse =
	| findReleaseByKeywordResponseSuccess
	| findReleaseByKeywordResponseError

export const getFindReleaseByKeywordUrl = (
	params: FindReleaseByKeywordParams,
) => {
	const normalizedParams = new URLSearchParams()

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString())
		}
	})

	const stringifiedParams = normalizedParams.toString()

	return stringifiedParams.length > 0
		? `/api/release?${stringifiedParams}`
		: `/api/release`
}

export const findReleaseByKeyword = async (
	params: FindReleaseByKeywordParams,
	options?: RequestInit,
): Promise<findReleaseByKeywordResponse> => {
	const res = await fetch(getFindReleaseByKeywordUrl(params), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: findReleaseByKeywordResponse["data"] = body
		? JSON.parse(body)
		: {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as findReleaseByKeywordResponse
}

export const getFindReleaseByKeywordQueryKey = (
	params?: FindReleaseByKeywordParams,
) => {
	return [`/api/release`, ...(params ? [params] : [])] as const
}

export const getFindReleaseByKeywordQueryOptions = <
	TData = Awaited<ReturnType<typeof findReleaseByKeyword>>,
	TError = string | FindReleaseByKeywordDefaultOne,
>(
	params: FindReleaseByKeywordParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof findReleaseByKeyword>>,
				TError,
				TData
			>
		>
		fetch?: RequestInit
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getFindReleaseByKeywordQueryKey(params)

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof findReleaseByKeyword>>
	> = ({ signal }) => findReleaseByKeyword(params, { signal, ...fetchOptions })

	return { queryKey, queryFn, ...queryOptions }
}

export type FindReleaseByKeywordQueryResult = NonNullable<
	Awaited<ReturnType<typeof findReleaseByKeyword>>
>
export type FindReleaseByKeywordQueryError =
	| string
	| FindReleaseByKeywordDefaultOne

export function useFindReleaseByKeyword<
	TData = Awaited<ReturnType<typeof findReleaseByKeyword>>,
	TError = string | FindReleaseByKeywordDefaultOne,
>(
	params: FindReleaseByKeywordParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof findReleaseByKeyword>>,
				TError,
				TData
			>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getFindReleaseByKeywordQueryOptions(params, options)

	const query = useQuery(
		() => getFindReleaseByKeywordQueryOptions(params, options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export type createReleaseResponse200 = {
	data: DataCorrectionSubmissionResult
	status: 200
}

export type createReleaseResponse429 = {
	data: string
	status: 429
}

export type createReleaseResponseDefaultApplicationJson = {
	data: CreateReleaseDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type createReleaseResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type createReleaseResponseSuccess = createReleaseResponse200 & {
	headers: Headers
}
export type createReleaseResponseError = (
	| createReleaseResponse429
	| createReleaseResponseDefaultApplicationJson
	| createReleaseResponseDefaultTextPlain
) & {
	headers: Headers
}

export type createReleaseResponse =
	| createReleaseResponseSuccess
	| createReleaseResponseError

export const getCreateReleaseUrl = () => {
	return `/api/release`
}

export const createRelease = async (
	newCorrectionNewRelease: NewCorrectionNewRelease,
	options?: RequestInit,
): Promise<createReleaseResponse> => {
	const res = await fetch(getCreateReleaseUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(newCorrectionNewRelease),
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: createReleaseResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as createReleaseResponse
}

export const getCreateReleaseMutationOptions = <
	TError = string | CreateReleaseDefaultOne,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createRelease>>,
		TError,
		{ data: NewCorrectionNewRelease },
		TContext
	>
	fetch?: RequestInit
}): SolidMutationOptions<
	Awaited<ReturnType<typeof createRelease>>,
	TError,
	{ data: NewCorrectionNewRelease },
	TContext
> => {
	const mutationKey = ["createRelease"]
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation
			&& "mutationKey" in options.mutation
			&& options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createRelease>>,
		{ data: NewCorrectionNewRelease }
	> = (props) => {
		const { data } = props ?? {}

		return createRelease(data, fetchOptions)
	}

	return { mutationFn, ...mutationOptions }
}

export type CreateReleaseMutationResult = NonNullable<
	Awaited<ReturnType<typeof createRelease>>
>
export type CreateReleaseMutationBody = NewCorrectionNewRelease
export type CreateReleaseMutationError = string | CreateReleaseDefaultOne

export const useCreateRelease = <
	TError = string | CreateReleaseDefaultOne,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createRelease>>,
			TError,
			{ data: NewCorrectionNewRelease },
			TContext
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createRelease>>,
	TError,
	{ data: NewCorrectionNewRelease },
	TContext
> => {
	return useMutation(
		() => getCreateReleaseMutationOptions(options),
		queryClient,
	)
}
export type exploreReleaseResponse200 = {
	data: DataPageRelease
	status: 200
}

export type exploreReleaseResponse400 = {
	data: ExploreRelease400
	status: 400
}

export type exploreReleaseResponse429 = {
	data: string
	status: 429
}

export type exploreReleaseResponse500 = {
	data: ExploreRelease500
	status: 500
}

export type exploreReleaseResponseDefaultApplicationJson = {
	data: ExploreReleaseDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 400 | 429 | 500>
}

export type exploreReleaseResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 400 | 429 | 500>
}

export type exploreReleaseResponseSuccess = exploreReleaseResponse200 & {
	headers: Headers
}
export type exploreReleaseResponseError = (
	| exploreReleaseResponse400
	| exploreReleaseResponse429
	| exploreReleaseResponse500
	| exploreReleaseResponseDefaultApplicationJson
	| exploreReleaseResponseDefaultTextPlain
) & {
	headers: Headers
}

export type exploreReleaseResponse =
	| exploreReleaseResponseSuccess
	| exploreReleaseResponseError

export const getExploreReleaseUrl = (params?: ExploreReleaseParams) => {
	const normalizedParams = new URLSearchParams()

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString())
		}
	})

	const stringifiedParams = normalizedParams.toString()

	return stringifiedParams.length > 0
		? `/api/release/explore?${stringifiedParams}`
		: `/api/release/explore`
}

export const exploreRelease = async (
	params?: ExploreReleaseParams,
	options?: RequestInit,
): Promise<exploreReleaseResponse> => {
	const res = await fetch(getExploreReleaseUrl(params), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: exploreReleaseResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as exploreReleaseResponse
}

export const getExploreReleaseQueryKey = (params?: ExploreReleaseParams) => {
	return [`/api/release/explore`, ...(params ? [params] : [])] as const
}

export const getExploreReleaseQueryOptions = <
	TData = Awaited<ReturnType<typeof exploreRelease>>,
	TError =
		| ExploreRelease400
		| string
		| ExploreRelease500
		| ExploreReleaseDefaultOne,
>(
	params?: ExploreReleaseParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof exploreRelease>>, TError, TData>
		>
		fetch?: RequestInit
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getExploreReleaseQueryKey(params)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof exploreRelease>>> = ({
		signal,
	}) => exploreRelease(params, { signal, ...fetchOptions })

	return { queryKey, queryFn, ...queryOptions }
}

export type ExploreReleaseQueryResult = NonNullable<
	Awaited<ReturnType<typeof exploreRelease>>
>
export type ExploreReleaseQueryError =
	| ExploreRelease400
	| string
	| ExploreRelease500
	| ExploreReleaseDefaultOne

export function useExploreRelease<
	TData = Awaited<ReturnType<typeof exploreRelease>>,
	TError =
		| ExploreRelease400
		| string
		| ExploreRelease500
		| ExploreReleaseDefaultOne,
>(
	params?: ExploreReleaseParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof exploreRelease>>, TError, TData>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getExploreReleaseQueryOptions(params, options)

	const query = useQuery(
		() => getExploreReleaseQueryOptions(params, options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export type findReleaseByIdResponse200 = {
	data: DataOptionRelease
	status: 200
}

export type findReleaseByIdResponse429 = {
	data: string
	status: 429
}

export type findReleaseByIdResponseDefaultApplicationJson = {
	data: FindReleaseByIdDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type findReleaseByIdResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type findReleaseByIdResponseSuccess = findReleaseByIdResponse200 & {
	headers: Headers
}
export type findReleaseByIdResponseError = (
	| findReleaseByIdResponse429
	| findReleaseByIdResponseDefaultApplicationJson
	| findReleaseByIdResponseDefaultTextPlain
) & {
	headers: Headers
}

export type findReleaseByIdResponse =
	| findReleaseByIdResponseSuccess
	| findReleaseByIdResponseError

export const getFindReleaseByIdUrl = (id: number) => {
	return `/api/release/${id}`
}

export const findReleaseById = async (
	id: number,
	options?: RequestInit,
): Promise<findReleaseByIdResponse> => {
	const res = await fetch(getFindReleaseByIdUrl(id), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: findReleaseByIdResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as findReleaseByIdResponse
}

export const getFindReleaseByIdQueryKey = (id: number) => {
	return [`/api/release/${id}`] as const
}

export const getFindReleaseByIdQueryOptions = <
	TData = Awaited<ReturnType<typeof findReleaseById>>,
	TError = string | FindReleaseByIdDefaultOne,
>(
	id: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof findReleaseById>>,
				TError,
				TData
			>
		>
		fetch?: RequestInit
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getFindReleaseByIdQueryKey(id)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof findReleaseById>>> = ({
		signal,
	}) => findReleaseById(id, { signal, ...fetchOptions })

	return { queryKey, queryFn, enabled: !!id, ...queryOptions }
}

export type FindReleaseByIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof findReleaseById>>
>
export type FindReleaseByIdQueryError = string | FindReleaseByIdDefaultOne

export function useFindReleaseById<
	TData = Awaited<ReturnType<typeof findReleaseById>>,
	TError = string | FindReleaseByIdDefaultOne,
>(
	id: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof findReleaseById>>,
				TError,
				TData
			>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getFindReleaseByIdQueryOptions(id, options)

	const query = useQuery(
		() => getFindReleaseByIdQueryOptions(id, options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export type updateReleaseResponse200 = {
	data: DataCorrectionSubmissionResult
	status: 200
}

export type updateReleaseResponse429 = {
	data: string
	status: 429
}

export type updateReleaseResponseDefaultApplicationJson = {
	data: UpdateReleaseDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type updateReleaseResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type updateReleaseResponseSuccess = updateReleaseResponse200 & {
	headers: Headers
}
export type updateReleaseResponseError = (
	| updateReleaseResponse429
	| updateReleaseResponseDefaultApplicationJson
	| updateReleaseResponseDefaultTextPlain
) & {
	headers: Headers
}

export type updateReleaseResponse =
	| updateReleaseResponseSuccess
	| updateReleaseResponseError

export const getUpdateReleaseUrl = (id: number) => {
	return `/api/release/${id}`
}

export const updateRelease = async (
	id: number,
	newCorrectionNewRelease: NewCorrectionNewRelease,
	options?: RequestInit,
): Promise<updateReleaseResponse> => {
	const res = await fetch(getUpdateReleaseUrl(id), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(newCorrectionNewRelease),
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: updateReleaseResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as updateReleaseResponse
}

export const getUpdateReleaseMutationOptions = <
	TError = string | UpdateReleaseDefaultOne,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateRelease>>,
		TError,
		{ id: number; data: NewCorrectionNewRelease },
		TContext
	>
	fetch?: RequestInit
}): SolidMutationOptions<
	Awaited<ReturnType<typeof updateRelease>>,
	TError,
	{ id: number; data: NewCorrectionNewRelease },
	TContext
> => {
	const mutationKey = ["updateRelease"]
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation
			&& "mutationKey" in options.mutation
			&& options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateRelease>>,
		{ id: number; data: NewCorrectionNewRelease }
	> = (props) => {
		const { id, data } = props ?? {}

		return updateRelease(id, data, fetchOptions)
	}

	return { mutationFn, ...mutationOptions }
}

export type UpdateReleaseMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateRelease>>
>
export type UpdateReleaseMutationBody = NewCorrectionNewRelease
export type UpdateReleaseMutationError = string | UpdateReleaseDefaultOne

export const useUpdateRelease = <
	TError = string | UpdateReleaseDefaultOne,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateRelease>>,
			TError,
			{ id: number; data: NewCorrectionNewRelease },
			TContext
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateRelease>>,
	TError,
	{ id: number; data: NewCorrectionNewRelease },
	TContext
> => {
	return useMutation(
		() => getUpdateReleaseMutationOptions(options),
		queryClient,
	)
}
export type getReleaseCoverArtMetadataResponse200 = {
	data: DataOptionCurrentImageMetadata
	status: 200
}

export type getReleaseCoverArtMetadataResponse429 = {
	data: string
	status: 429
}

export type getReleaseCoverArtMetadataResponseDefaultApplicationJson = {
	data: GetReleaseCoverArtMetadataDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type getReleaseCoverArtMetadataResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type getReleaseCoverArtMetadataResponseSuccess =
	getReleaseCoverArtMetadataResponse200 & {
		headers: Headers
	}
export type getReleaseCoverArtMetadataResponseError = (
	| getReleaseCoverArtMetadataResponse429
	| getReleaseCoverArtMetadataResponseDefaultApplicationJson
	| getReleaseCoverArtMetadataResponseDefaultTextPlain
) & {
	headers: Headers
}

export type getReleaseCoverArtMetadataResponse =
	| getReleaseCoverArtMetadataResponseSuccess
	| getReleaseCoverArtMetadataResponseError

export const getGetReleaseCoverArtMetadataUrl = (id: number) => {
	return `/api/release/${id}/cover-art`
}

export const getReleaseCoverArtMetadata = async (
	id: number,
	options?: RequestInit,
): Promise<getReleaseCoverArtMetadataResponse> => {
	const res = await fetch(getGetReleaseCoverArtMetadataUrl(id), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: getReleaseCoverArtMetadataResponse["data"] = body
		? JSON.parse(body)
		: {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getReleaseCoverArtMetadataResponse
}

export const getGetReleaseCoverArtMetadataQueryKey = (id: number) => {
	return [`/api/release/${id}/cover-art`] as const
}

export const getGetReleaseCoverArtMetadataQueryOptions = <
	TData = Awaited<ReturnType<typeof getReleaseCoverArtMetadata>>,
	TError = string | GetReleaseCoverArtMetadataDefaultOne,
>(
	id: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getReleaseCoverArtMetadata>>,
				TError,
				TData
			>
		>
		fetch?: RequestInit
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getGetReleaseCoverArtMetadataQueryKey(id)

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getReleaseCoverArtMetadata>>
	> = ({ signal }) =>
		getReleaseCoverArtMetadata(id, { signal, ...fetchOptions })

	return { queryKey, queryFn, enabled: !!id, ...queryOptions }
}

export type GetReleaseCoverArtMetadataQueryResult = NonNullable<
	Awaited<ReturnType<typeof getReleaseCoverArtMetadata>>
>
export type GetReleaseCoverArtMetadataQueryError =
	| string
	| GetReleaseCoverArtMetadataDefaultOne

export function useGetReleaseCoverArtMetadata<
	TData = Awaited<ReturnType<typeof getReleaseCoverArtMetadata>>,
	TError = string | GetReleaseCoverArtMetadataDefaultOne,
>(
	id: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getReleaseCoverArtMetadata>>,
				TError,
				TData
			>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getGetReleaseCoverArtMetadataQueryOptions(id, options)

	const query = useQuery(
		() => getGetReleaseCoverArtMetadataQueryOptions(id, options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export type uploadReleaseCoverArtResponse200 = {
	data: DataI32
	status: 200
}

export type uploadReleaseCoverArtResponse429 = {
	data: string
	status: 429
}

export type uploadReleaseCoverArtResponseDefaultApplicationJson = {
	data: UploadReleaseCoverArtDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type uploadReleaseCoverArtResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type uploadReleaseCoverArtResponseSuccess =
	uploadReleaseCoverArtResponse200 & {
		headers: Headers
	}
export type uploadReleaseCoverArtResponseError = (
	| uploadReleaseCoverArtResponse429
	| uploadReleaseCoverArtResponseDefaultApplicationJson
	| uploadReleaseCoverArtResponseDefaultTextPlain
) & {
	headers: Headers
}

export type uploadReleaseCoverArtResponse =
	| uploadReleaseCoverArtResponseSuccess
	| uploadReleaseCoverArtResponseError

export const getUploadReleaseCoverArtUrl = (id: number) => {
	return `/api/release/${id}/cover-art`
}

export const uploadReleaseCoverArt = async (
	id: number,
	releaseCoverArtFormData: ReleaseCoverArtFormData,
	options?: RequestInit,
): Promise<uploadReleaseCoverArtResponse> => {
	const formData = new FormData()
	formData.append(`data`, releaseCoverArtFormData.data)

	const res = await fetch(getUploadReleaseCoverArtUrl(id), {
		...options,
		method: "POST",
		body: formData,
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: uploadReleaseCoverArtResponse["data"] = body
		? JSON.parse(body)
		: {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as uploadReleaseCoverArtResponse
}

export const getUploadReleaseCoverArtMutationOptions = <
	TError = string | UploadReleaseCoverArtDefaultOne,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof uploadReleaseCoverArt>>,
		TError,
		{ id: number; data: ReleaseCoverArtFormData },
		TContext
	>
	fetch?: RequestInit
}): SolidMutationOptions<
	Awaited<ReturnType<typeof uploadReleaseCoverArt>>,
	TError,
	{ id: number; data: ReleaseCoverArtFormData },
	TContext
> => {
	const mutationKey = ["uploadReleaseCoverArt"]
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation
			&& "mutationKey" in options.mutation
			&& options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof uploadReleaseCoverArt>>,
		{ id: number; data: ReleaseCoverArtFormData }
	> = (props) => {
		const { id, data } = props ?? {}

		return uploadReleaseCoverArt(id, data, fetchOptions)
	}

	return { mutationFn, ...mutationOptions }
}

export type UploadReleaseCoverArtMutationResult = NonNullable<
	Awaited<ReturnType<typeof uploadReleaseCoverArt>>
>
export type UploadReleaseCoverArtMutationBody = ReleaseCoverArtFormData
export type UploadReleaseCoverArtMutationError =
	| string
	| UploadReleaseCoverArtDefaultOne

export const useUploadReleaseCoverArt = <
	TError = string | UploadReleaseCoverArtDefaultOne,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof uploadReleaseCoverArt>>,
			TError,
			{ id: number; data: ReleaseCoverArtFormData },
			TContext
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof uploadReleaseCoverArt>>,
	TError,
	{ id: number; data: ReleaseCoverArtFormData },
	TContext
> => {
	return useMutation(
		() => getUploadReleaseCoverArtMutationOptions(options),
		queryClient,
	)
}

export const getFindReleaseByKeywordResponseDateWithPrecisionMock = (
	overrideResponse: Partial<DateWithPrecision> = {},
): DateWithPrecision => ({
	...{
		value: faker.date.past().toISOString().slice(0, 10),
		precision: faker.helpers.arrayElement(Object.values(DatePrecision)),
	},
	...overrideResponse,
})

export const getFindReleaseByKeywordResponseSimpleLabelMock = (
	overrideResponse: Partial<SimpleLabel> = {},
): SimpleLabel => ({
	...{
		id: faker.number.int(),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	},
	...overrideResponse,
})

export const getFindReleaseByKeywordResponseMock = (
	overrideResponse: Partial<Extract<DataVecRelease, object>> = {},
): DataVecRelease => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int(),
		title: faker.string.alpha({ length: { min: 10, max: 20 } }),
		release_type: faker.helpers.arrayElement(Object.values(ReleaseType)),
		release_date: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				null,
				{ ...getFindReleaseByKeywordResponseDateWithPrecisionMock() },
			]),
			undefined,
		]),
		recording_date_start: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				null,
				{ ...getFindReleaseByKeywordResponseDateWithPrecisionMock() },
			]),
			undefined,
		]),
		recording_date_end: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				null,
				{ ...getFindReleaseByKeywordResponseDateWithPrecisionMock() },
			]),
			undefined,
		]),
		cover_art_url: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		artists: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			})),
			undefined,
		]),
		credits: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				artist: {
					id: faker.number.int(),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				},
				role: {
					id: faker.number.int(),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				},
				on: faker.helpers.arrayElement([
					Array.from(
						{ length: faker.number.int({ min: 1, max: 10 }) },
						(_, i) => i + 1,
					).map(() => faker.number.int()),
					undefined,
				]),
			})),
			undefined,
		]),
		catalog_nums: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				catalog_number: faker.string.alpha({ length: { min: 10, max: 20 } }),
				label: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						null,
						{ ...getFindReleaseByKeywordResponseSimpleLabelMock() },
					]),
					undefined,
				]),
			})),
			undefined,
		]),
		localized_titles: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				language: {
					id: faker.number.int(),
					code: faker.string.alpha({ length: { min: 10, max: 20 } }),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				},
				title: faker.string.alpha({ length: { min: 10, max: 20 } }),
			})),
			undefined,
		]),
		discs: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				name: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
			})),
			undefined,
		]),
		tracks: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				track_number: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				disc_id: faker.number.int(),
				display_title: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				duration: faker.helpers.arrayElement([
					faker.helpers.arrayElement([faker.number.int(), null]),
					undefined,
				]),
				song: {
					id: faker.number.int(),
					title: faker.string.alpha({ length: { min: 10, max: 20 } }),
				},
				artists: faker.helpers.arrayElement([
					Array.from(
						{ length: faker.number.int({ min: 1, max: 10 }) },
						(_, i) => i + 1,
					).map(() => ({
						id: faker.number.int(),
						name: faker.string.alpha({ length: { min: 10, max: 20 } }),
					})),
					undefined,
				]),
			})),
			undefined,
		]),
		events: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			})),
			undefined,
		]),
	})),
	...overrideResponse,
})

export const getCreateReleaseResponseMock = (
	overrideResponse: Partial<
		Extract<DataCorrectionSubmissionResult, object>
	> = {},
): DataCorrectionSubmissionResult => ({
	status: faker.helpers.arrayElement(["Ok"] as const),
	data: { correction_id: faker.number.int(), entity_id: faker.number.int() },
	...overrideResponse,
})

export const getExploreReleaseResponseDateWithPrecisionMock = (
	overrideResponse: Partial<DateWithPrecision> = {},
): DateWithPrecision => ({
	...{
		value: faker.date.past().toISOString().slice(0, 10),
		precision: faker.helpers.arrayElement(Object.values(DatePrecision)),
	},
	...overrideResponse,
})

export const getExploreReleaseResponseSimpleLabelMock = (
	overrideResponse: Partial<SimpleLabel> = {},
): SimpleLabel => ({
	...{
		id: faker.number.int(),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	},
	...overrideResponse,
})

export const getExploreReleaseResponseMock = (
	overrideResponse: Partial<Extract<DataPageRelease, object>> = {},
): DataPageRelease => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: {
		items: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int(),
			title: faker.string.alpha({ length: { min: 10, max: 20 } }),
			release_type: faker.helpers.arrayElement(Object.values(ReleaseType)),
			release_date: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					null,
					{ ...getExploreReleaseResponseDateWithPrecisionMock() },
				]),
				undefined,
			]),
			recording_date_start: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					null,
					{ ...getExploreReleaseResponseDateWithPrecisionMock() },
				]),
				undefined,
			]),
			recording_date_end: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					null,
					{ ...getExploreReleaseResponseDateWithPrecisionMock() },
				]),
				undefined,
			]),
			cover_art_url: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				undefined,
			]),
			artists: faker.helpers.arrayElement([
				Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					id: faker.number.int(),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				})),
				undefined,
			]),
			credits: faker.helpers.arrayElement([
				Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					artist: {
						id: faker.number.int(),
						name: faker.string.alpha({ length: { min: 10, max: 20 } }),
					},
					role: {
						id: faker.number.int(),
						name: faker.string.alpha({ length: { min: 10, max: 20 } }),
					},
					on: faker.helpers.arrayElement([
						Array.from(
							{ length: faker.number.int({ min: 1, max: 10 }) },
							(_, i) => i + 1,
						).map(() => faker.number.int()),
						undefined,
					]),
				})),
				undefined,
			]),
			catalog_nums: faker.helpers.arrayElement([
				Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					catalog_number: faker.string.alpha({ length: { min: 10, max: 20 } }),
					label: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							null,
							{ ...getExploreReleaseResponseSimpleLabelMock() },
						]),
						undefined,
					]),
				})),
				undefined,
			]),
			localized_titles: faker.helpers.arrayElement([
				Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					language: {
						id: faker.number.int(),
						code: faker.string.alpha({ length: { min: 10, max: 20 } }),
						name: faker.string.alpha({ length: { min: 10, max: 20 } }),
					},
					title: faker.string.alpha({ length: { min: 10, max: 20 } }),
				})),
				undefined,
			]),
			discs: faker.helpers.arrayElement([
				Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					id: faker.number.int(),
					name: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						undefined,
					]),
				})),
				undefined,
			]),
			tracks: faker.helpers.arrayElement([
				Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					id: faker.number.int(),
					track_number: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						undefined,
					]),
					disc_id: faker.number.int(),
					display_title: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						undefined,
					]),
					duration: faker.helpers.arrayElement([
						faker.helpers.arrayElement([faker.number.int(), null]),
						undefined,
					]),
					song: {
						id: faker.number.int(),
						title: faker.string.alpha({ length: { min: 10, max: 20 } }),
					},
					artists: faker.helpers.arrayElement([
						Array.from(
							{ length: faker.number.int({ min: 1, max: 10 }) },
							(_, i) => i + 1,
						).map(() => ({
							id: faker.number.int(),
							name: faker.string.alpha({ length: { min: 10, max: 20 } }),
						})),
						undefined,
					]),
				})),
				undefined,
			]),
			events: faker.helpers.arrayElement([
				Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					id: faker.number.int(),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				})),
				undefined,
			]),
		})),
		page: faker.number.int({ min: 0 }),
		page_size: faker.number.int({ min: 0 }),
		total_items: faker.number.int({ min: 0 }),
		total_pages: faker.number.int({ min: 0 }),
	},
	...overrideResponse,
})

export const getFindReleaseByIdResponseDateWithPrecisionMock = (
	overrideResponse: Partial<DateWithPrecision> = {},
): DateWithPrecision => ({
	...{
		value: faker.date.past().toISOString().slice(0, 10),
		precision: faker.helpers.arrayElement(Object.values(DatePrecision)),
	},
	...overrideResponse,
})

export const getFindReleaseByIdResponseSimpleLabelMock = (
	overrideResponse: Partial<SimpleLabel> = {},
): SimpleLabel => ({
	...{
		id: faker.number.int(),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	},
	...overrideResponse,
})

export const getFindReleaseByIdResponseReleaseMock = (
	overrideResponse: Partial<Release> = {},
): Release => ({
	...{
		id: faker.number.int(),
		title: faker.string.alpha({ length: { min: 10, max: 20 } }),
		release_type: faker.helpers.arrayElement(Object.values(ReleaseType)),
		release_date: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				null,
				{ ...getFindReleaseByIdResponseDateWithPrecisionMock() },
			]),
			undefined,
		]),
		recording_date_start: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				null,
				{ ...getFindReleaseByIdResponseDateWithPrecisionMock() },
			]),
			undefined,
		]),
		recording_date_end: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				null,
				{ ...getFindReleaseByIdResponseDateWithPrecisionMock() },
			]),
			undefined,
		]),
		cover_art_url: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		artists: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			})),
			undefined,
		]),
		credits: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				artist: {
					id: faker.number.int(),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				},
				role: {
					id: faker.number.int(),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				},
				on: faker.helpers.arrayElement([
					Array.from(
						{ length: faker.number.int({ min: 1, max: 10 }) },
						(_, i) => i + 1,
					).map(() => faker.number.int()),
					undefined,
				]),
			})),
			undefined,
		]),
		catalog_nums: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				catalog_number: faker.string.alpha({ length: { min: 10, max: 20 } }),
				label: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						null,
						{ ...getFindReleaseByIdResponseSimpleLabelMock() },
					]),
					undefined,
				]),
			})),
			undefined,
		]),
		localized_titles: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				language: {
					id: faker.number.int(),
					code: faker.string.alpha({ length: { min: 10, max: 20 } }),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				},
				title: faker.string.alpha({ length: { min: 10, max: 20 } }),
			})),
			undefined,
		]),
		discs: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				name: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
			})),
			undefined,
		]),
		tracks: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				track_number: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				disc_id: faker.number.int(),
				display_title: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				duration: faker.helpers.arrayElement([
					faker.helpers.arrayElement([faker.number.int(), null]),
					undefined,
				]),
				song: {
					id: faker.number.int(),
					title: faker.string.alpha({ length: { min: 10, max: 20 } }),
				},
				artists: faker.helpers.arrayElement([
					Array.from(
						{ length: faker.number.int({ min: 1, max: 10 }) },
						(_, i) => i + 1,
					).map(() => ({
						id: faker.number.int(),
						name: faker.string.alpha({ length: { min: 10, max: 20 } }),
					})),
					undefined,
				]),
			})),
			undefined,
		]),
		events: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			})),
			undefined,
		]),
	},
	...overrideResponse,
})

export const getFindReleaseByIdResponseMock = (
	overrideResponse: Partial<Extract<DataOptionRelease, object>> = {},
): DataOptionRelease => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: faker.helpers.arrayElement([
		null,
		{ ...getFindReleaseByIdResponseReleaseMock() },
	]),
	...overrideResponse,
})

export const getUpdateReleaseResponseMock = (
	overrideResponse: Partial<
		Extract<DataCorrectionSubmissionResult, object>
	> = {},
): DataCorrectionSubmissionResult => ({
	status: faker.helpers.arrayElement(["Ok"] as const),
	data: { correction_id: faker.number.int(), entity_id: faker.number.int() },
	...overrideResponse,
})

export const getGetReleaseCoverArtMetadataResponseMock = (
	overrideResponse: Partial<
		Extract<DataOptionCurrentImageMetadata, object>
	> = {},
): DataOptionCurrentImageMetadata => ({
	status: faker.helpers.arrayElement(["Ok"] as const),
	data: faker.helpers.arrayElement([
		null,
		{
			uploaded_at: faker.date.past().toISOString().slice(0, 19) + "Z",
			uploaded_by: {
				id: faker.number.int(),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			},
		},
	]),
	...overrideResponse,
})

export const getUploadReleaseCoverArtResponseMock = (
	overrideResponse: Partial<Extract<DataI32, object>> = {},
): DataI32 => ({
	status: faker.helpers.arrayElement(["Ok"] as const),
	data: faker.number.int(),
	...overrideResponse,
})

export const getFindReleaseByKeywordMockHandler = (
	overrideResponse?:
		| DataVecRelease
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<DataVecRelease> | DataVecRelease),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/release",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getFindReleaseByKeywordResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getCreateReleaseMockHandler = (
	overrideResponse?:
		| DataCorrectionSubmissionResult
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) =>
				| Promise<DataCorrectionSubmissionResult>
				| DataCorrectionSubmissionResult),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/release",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getCreateReleaseResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getExploreReleaseMockHandler = (
	overrideResponse?:
		| DataPageRelease
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<DataPageRelease> | DataPageRelease),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/release/explore",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getExploreReleaseResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getFindReleaseByIdMockHandler = (
	overrideResponse?:
		| DataOptionRelease
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<DataOptionRelease> | DataOptionRelease),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/release/:id",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getFindReleaseByIdResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getUpdateReleaseMockHandler = (
	overrideResponse?:
		| DataCorrectionSubmissionResult
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) =>
				| Promise<DataCorrectionSubmissionResult>
				| DataCorrectionSubmissionResult),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/release/:id",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getUpdateReleaseResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getGetReleaseCoverArtMetadataMockHandler = (
	overrideResponse?:
		| DataOptionCurrentImageMetadata
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) =>
				| Promise<DataOptionCurrentImageMetadata>
				| DataOptionCurrentImageMetadata),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/release/:id/cover-art",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getGetReleaseCoverArtMetadataResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getUploadReleaseCoverArtMockHandler = (
	overrideResponse?:
		| DataI32
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<DataI32> | DataI32),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/release/:id/cover-art",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getUploadReleaseCoverArtResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}
export const getReleaseMock = () => [
	getFindReleaseByKeywordMockHandler(),
	getCreateReleaseMockHandler(),
	getExploreReleaseMockHandler(),
	getFindReleaseByIdMockHandler(),
	getUpdateReleaseMockHandler(),
	getGetReleaseCoverArtMetadataMockHandler(),
	getUploadReleaseCoverArtMockHandler(),
]
