/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Touhou Cloud DB
 * TODO
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker"
import { useQuery } from "@tanstack/solid-query"
import type {
	DataTag,
	QueryClient,
	QueryFunction,
	QueryKey,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/solid-query"
import { HttpResponse, http } from "msw"
import type { RequestHandlerOptions } from "msw"

import type {
	SearchAllDefaultOne,
	SearchAllParams,
	SearchArtistDefaultOne,
	SearchArtistParams,
	SearchEventDefaultOne,
	SearchEventParams,
	SearchLabelDefaultOne,
	SearchLabelParams,
	SearchReleaseDefaultOne,
	SearchReleaseParams,
	SearchSongDefaultOne,
	SearchSongParams,
	SearchTagDefaultOne,
	SearchTagParams,
} from "./touhouCloudDB.schemas"
import { TagType } from "./touhouCloudDB.schemas"
import type {
	DataPaginatedSimpleArtist,
	DataPaginatedSimpleEvent,
	DataPaginatedSimpleLabel,
	DataPaginatedSimpleRelease,
	DataPaginatedSongRef,
	DataPaginatedTagRef,
	DataSearchResponse,
} from "./touhouCloudDB.schemas"

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308
export type HTTPStatusCode4xx =
	| 400
	| 401
	| 402
	| 403
	| 404
	| 405
	| 406
	| 407
	| 408
	| 409
	| 410
	| 411
	| 412
	| 413
	| 414
	| 415
	| 416
	| 417
	| 418
	| 419
	| 420
	| 421
	| 422
	| 423
	| 424
	| 426
	| 428
	| 429
	| 431
	| 451
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511
export type HTTPStatusCodes =
	| HTTPStatusCode1xx
	| HTTPStatusCode2xx
	| HTTPStatusCode3xx
	| HTTPStatusCode4xx
	| HTTPStatusCode5xx

export type searchAllResponse200 = {
	data: DataSearchResponse
	status: 200
}

export type searchAllResponse429 = {
	data: string
	status: 429
}

export type searchAllResponseDefaultApplicationJson = {
	data: SearchAllDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type searchAllResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type searchAllResponseSuccess = searchAllResponse200 & {
	headers: Headers
}
export type searchAllResponseError = (
	| searchAllResponse429
	| searchAllResponseDefaultApplicationJson
	| searchAllResponseDefaultTextPlain
) & {
	headers: Headers
}

export type searchAllResponse =
	| searchAllResponseSuccess
	| searchAllResponseError

export const getSearchAllUrl = (params: SearchAllParams) => {
	const normalizedParams = new URLSearchParams()

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString())
		}
	})

	const stringifiedParams = normalizedParams.toString()

	return stringifiedParams.length > 0
		? `/api/search?${stringifiedParams}`
		: `/api/search`
}

export const searchAll = async (
	params: SearchAllParams,
	options?: RequestInit,
): Promise<searchAllResponse> => {
	const res = await fetch(getSearchAllUrl(params), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: searchAllResponse["data"] = body ? JSON.parse(body) : {}
	return { data, status: res.status, headers: res.headers } as searchAllResponse
}

export const getSearchAllQueryKey = (params?: SearchAllParams) => {
	return [`/api/search`, ...(params ? [params] : [])] as const
}

export const getSearchAllQueryOptions = <
	TData = Awaited<ReturnType<typeof searchAll>>,
	TError = string | SearchAllDefaultOne,
>(
	params: SearchAllParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof searchAll>>, TError, TData>
		>
		fetch?: RequestInit
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getSearchAllQueryKey(params)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof searchAll>>> = ({
		signal,
	}) => searchAll(params, { signal, ...fetchOptions })

	return { queryKey, queryFn, ...queryOptions }
}

export type SearchAllQueryResult = NonNullable<
	Awaited<ReturnType<typeof searchAll>>
>
export type SearchAllQueryError = string | SearchAllDefaultOne

export function useSearchAll<
	TData = Awaited<ReturnType<typeof searchAll>>,
	TError = string | SearchAllDefaultOne,
>(
	params: SearchAllParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof searchAll>>, TError, TData>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getSearchAllQueryOptions(params, options)

	const query = useQuery(
		() => getSearchAllQueryOptions(params, options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export type searchArtistResponse200 = {
	data: DataPaginatedSimpleArtist
	status: 200
}

export type searchArtistResponse429 = {
	data: string
	status: 429
}

export type searchArtistResponseDefaultApplicationJson = {
	data: SearchArtistDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type searchArtistResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type searchArtistResponseSuccess = searchArtistResponse200 & {
	headers: Headers
}
export type searchArtistResponseError = (
	| searchArtistResponse429
	| searchArtistResponseDefaultApplicationJson
	| searchArtistResponseDefaultTextPlain
) & {
	headers: Headers
}

export type searchArtistResponse =
	| searchArtistResponseSuccess
	| searchArtistResponseError

export const getSearchArtistUrl = (params: SearchArtistParams) => {
	const normalizedParams = new URLSearchParams()

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString())
		}
	})

	const stringifiedParams = normalizedParams.toString()

	return stringifiedParams.length > 0
		? `/api/search/artist?${stringifiedParams}`
		: `/api/search/artist`
}

export const searchArtist = async (
	params: SearchArtistParams,
	options?: RequestInit,
): Promise<searchArtistResponse> => {
	const res = await fetch(getSearchArtistUrl(params), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: searchArtistResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as searchArtistResponse
}

export const getSearchArtistQueryKey = (params?: SearchArtistParams) => {
	return [`/api/search/artist`, ...(params ? [params] : [])] as const
}

export const getSearchArtistQueryOptions = <
	TData = Awaited<ReturnType<typeof searchArtist>>,
	TError = string | SearchArtistDefaultOne,
>(
	params: SearchArtistParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof searchArtist>>, TError, TData>
		>
		fetch?: RequestInit
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getSearchArtistQueryKey(params)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof searchArtist>>> = ({
		signal,
	}) => searchArtist(params, { signal, ...fetchOptions })

	return { queryKey, queryFn, ...queryOptions }
}

export type SearchArtistQueryResult = NonNullable<
	Awaited<ReturnType<typeof searchArtist>>
>
export type SearchArtistQueryError = string | SearchArtistDefaultOne

export function useSearchArtist<
	TData = Awaited<ReturnType<typeof searchArtist>>,
	TError = string | SearchArtistDefaultOne,
>(
	params: SearchArtistParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof searchArtist>>, TError, TData>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getSearchArtistQueryOptions(params, options)

	const query = useQuery(
		() => getSearchArtistQueryOptions(params, options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export type searchEventResponse200 = {
	data: DataPaginatedSimpleEvent
	status: 200
}

export type searchEventResponse429 = {
	data: string
	status: 429
}

export type searchEventResponseDefaultApplicationJson = {
	data: SearchEventDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type searchEventResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type searchEventResponseSuccess = searchEventResponse200 & {
	headers: Headers
}
export type searchEventResponseError = (
	| searchEventResponse429
	| searchEventResponseDefaultApplicationJson
	| searchEventResponseDefaultTextPlain
) & {
	headers: Headers
}

export type searchEventResponse =
	| searchEventResponseSuccess
	| searchEventResponseError

export const getSearchEventUrl = (params: SearchEventParams) => {
	const normalizedParams = new URLSearchParams()

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString())
		}
	})

	const stringifiedParams = normalizedParams.toString()

	return stringifiedParams.length > 0
		? `/api/search/event?${stringifiedParams}`
		: `/api/search/event`
}

export const searchEvent = async (
	params: SearchEventParams,
	options?: RequestInit,
): Promise<searchEventResponse> => {
	const res = await fetch(getSearchEventUrl(params), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: searchEventResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as searchEventResponse
}

export const getSearchEventQueryKey = (params?: SearchEventParams) => {
	return [`/api/search/event`, ...(params ? [params] : [])] as const
}

export const getSearchEventQueryOptions = <
	TData = Awaited<ReturnType<typeof searchEvent>>,
	TError = string | SearchEventDefaultOne,
>(
	params: SearchEventParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof searchEvent>>, TError, TData>
		>
		fetch?: RequestInit
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getSearchEventQueryKey(params)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof searchEvent>>> = ({
		signal,
	}) => searchEvent(params, { signal, ...fetchOptions })

	return { queryKey, queryFn, ...queryOptions }
}

export type SearchEventQueryResult = NonNullable<
	Awaited<ReturnType<typeof searchEvent>>
>
export type SearchEventQueryError = string | SearchEventDefaultOne

export function useSearchEvent<
	TData = Awaited<ReturnType<typeof searchEvent>>,
	TError = string | SearchEventDefaultOne,
>(
	params: SearchEventParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof searchEvent>>, TError, TData>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getSearchEventQueryOptions(params, options)

	const query = useQuery(
		() => getSearchEventQueryOptions(params, options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export type searchLabelResponse200 = {
	data: DataPaginatedSimpleLabel
	status: 200
}

export type searchLabelResponse429 = {
	data: string
	status: 429
}

export type searchLabelResponseDefaultApplicationJson = {
	data: SearchLabelDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type searchLabelResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type searchLabelResponseSuccess = searchLabelResponse200 & {
	headers: Headers
}
export type searchLabelResponseError = (
	| searchLabelResponse429
	| searchLabelResponseDefaultApplicationJson
	| searchLabelResponseDefaultTextPlain
) & {
	headers: Headers
}

export type searchLabelResponse =
	| searchLabelResponseSuccess
	| searchLabelResponseError

export const getSearchLabelUrl = (params: SearchLabelParams) => {
	const normalizedParams = new URLSearchParams()

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString())
		}
	})

	const stringifiedParams = normalizedParams.toString()

	return stringifiedParams.length > 0
		? `/api/search/label?${stringifiedParams}`
		: `/api/search/label`
}

export const searchLabel = async (
	params: SearchLabelParams,
	options?: RequestInit,
): Promise<searchLabelResponse> => {
	const res = await fetch(getSearchLabelUrl(params), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: searchLabelResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as searchLabelResponse
}

export const getSearchLabelQueryKey = (params?: SearchLabelParams) => {
	return [`/api/search/label`, ...(params ? [params] : [])] as const
}

export const getSearchLabelQueryOptions = <
	TData = Awaited<ReturnType<typeof searchLabel>>,
	TError = string | SearchLabelDefaultOne,
>(
	params: SearchLabelParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof searchLabel>>, TError, TData>
		>
		fetch?: RequestInit
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getSearchLabelQueryKey(params)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof searchLabel>>> = ({
		signal,
	}) => searchLabel(params, { signal, ...fetchOptions })

	return { queryKey, queryFn, ...queryOptions }
}

export type SearchLabelQueryResult = NonNullable<
	Awaited<ReturnType<typeof searchLabel>>
>
export type SearchLabelQueryError = string | SearchLabelDefaultOne

export function useSearchLabel<
	TData = Awaited<ReturnType<typeof searchLabel>>,
	TError = string | SearchLabelDefaultOne,
>(
	params: SearchLabelParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof searchLabel>>, TError, TData>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getSearchLabelQueryOptions(params, options)

	const query = useQuery(
		() => getSearchLabelQueryOptions(params, options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export type searchReleaseResponse200 = {
	data: DataPaginatedSimpleRelease
	status: 200
}

export type searchReleaseResponse429 = {
	data: string
	status: 429
}

export type searchReleaseResponseDefaultApplicationJson = {
	data: SearchReleaseDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type searchReleaseResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type searchReleaseResponseSuccess = searchReleaseResponse200 & {
	headers: Headers
}
export type searchReleaseResponseError = (
	| searchReleaseResponse429
	| searchReleaseResponseDefaultApplicationJson
	| searchReleaseResponseDefaultTextPlain
) & {
	headers: Headers
}

export type searchReleaseResponse =
	| searchReleaseResponseSuccess
	| searchReleaseResponseError

export const getSearchReleaseUrl = (params: SearchReleaseParams) => {
	const normalizedParams = new URLSearchParams()

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString())
		}
	})

	const stringifiedParams = normalizedParams.toString()

	return stringifiedParams.length > 0
		? `/api/search/release?${stringifiedParams}`
		: `/api/search/release`
}

export const searchRelease = async (
	params: SearchReleaseParams,
	options?: RequestInit,
): Promise<searchReleaseResponse> => {
	const res = await fetch(getSearchReleaseUrl(params), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: searchReleaseResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as searchReleaseResponse
}

export const getSearchReleaseQueryKey = (params?: SearchReleaseParams) => {
	return [`/api/search/release`, ...(params ? [params] : [])] as const
}

export const getSearchReleaseQueryOptions = <
	TData = Awaited<ReturnType<typeof searchRelease>>,
	TError = string | SearchReleaseDefaultOne,
>(
	params: SearchReleaseParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof searchRelease>>, TError, TData>
		>
		fetch?: RequestInit
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getSearchReleaseQueryKey(params)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof searchRelease>>> = ({
		signal,
	}) => searchRelease(params, { signal, ...fetchOptions })

	return { queryKey, queryFn, ...queryOptions }
}

export type SearchReleaseQueryResult = NonNullable<
	Awaited<ReturnType<typeof searchRelease>>
>
export type SearchReleaseQueryError = string | SearchReleaseDefaultOne

export function useSearchRelease<
	TData = Awaited<ReturnType<typeof searchRelease>>,
	TError = string | SearchReleaseDefaultOne,
>(
	params: SearchReleaseParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof searchRelease>>, TError, TData>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getSearchReleaseQueryOptions(params, options)

	const query = useQuery(
		() => getSearchReleaseQueryOptions(params, options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export type searchSongResponse200 = {
	data: DataPaginatedSongRef
	status: 200
}

export type searchSongResponse429 = {
	data: string
	status: 429
}

export type searchSongResponseDefaultApplicationJson = {
	data: SearchSongDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type searchSongResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type searchSongResponseSuccess = searchSongResponse200 & {
	headers: Headers
}
export type searchSongResponseError = (
	| searchSongResponse429
	| searchSongResponseDefaultApplicationJson
	| searchSongResponseDefaultTextPlain
) & {
	headers: Headers
}

export type searchSongResponse =
	| searchSongResponseSuccess
	| searchSongResponseError

export const getSearchSongUrl = (params: SearchSongParams) => {
	const normalizedParams = new URLSearchParams()

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString())
		}
	})

	const stringifiedParams = normalizedParams.toString()

	return stringifiedParams.length > 0
		? `/api/search/song?${stringifiedParams}`
		: `/api/search/song`
}

export const searchSong = async (
	params: SearchSongParams,
	options?: RequestInit,
): Promise<searchSongResponse> => {
	const res = await fetch(getSearchSongUrl(params), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: searchSongResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as searchSongResponse
}

export const getSearchSongQueryKey = (params?: SearchSongParams) => {
	return [`/api/search/song`, ...(params ? [params] : [])] as const
}

export const getSearchSongQueryOptions = <
	TData = Awaited<ReturnType<typeof searchSong>>,
	TError = string | SearchSongDefaultOne,
>(
	params: SearchSongParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof searchSong>>, TError, TData>
		>
		fetch?: RequestInit
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getSearchSongQueryKey(params)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof searchSong>>> = ({
		signal,
	}) => searchSong(params, { signal, ...fetchOptions })

	return { queryKey, queryFn, ...queryOptions }
}

export type SearchSongQueryResult = NonNullable<
	Awaited<ReturnType<typeof searchSong>>
>
export type SearchSongQueryError = string | SearchSongDefaultOne

export function useSearchSong<
	TData = Awaited<ReturnType<typeof searchSong>>,
	TError = string | SearchSongDefaultOne,
>(
	params: SearchSongParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof searchSong>>, TError, TData>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getSearchSongQueryOptions(params, options)

	const query = useQuery(
		() => getSearchSongQueryOptions(params, options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export type searchTagResponse200 = {
	data: DataPaginatedTagRef
	status: 200
}

export type searchTagResponse429 = {
	data: string
	status: 429
}

export type searchTagResponseDefaultApplicationJson = {
	data: SearchTagDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type searchTagResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type searchTagResponseSuccess = searchTagResponse200 & {
	headers: Headers
}
export type searchTagResponseError = (
	| searchTagResponse429
	| searchTagResponseDefaultApplicationJson
	| searchTagResponseDefaultTextPlain
) & {
	headers: Headers
}

export type searchTagResponse =
	| searchTagResponseSuccess
	| searchTagResponseError

export const getSearchTagUrl = (params: SearchTagParams) => {
	const normalizedParams = new URLSearchParams()

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString())
		}
	})

	const stringifiedParams = normalizedParams.toString()

	return stringifiedParams.length > 0
		? `/api/search/tag?${stringifiedParams}`
		: `/api/search/tag`
}

export const searchTag = async (
	params: SearchTagParams,
	options?: RequestInit,
): Promise<searchTagResponse> => {
	const res = await fetch(getSearchTagUrl(params), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: searchTagResponse["data"] = body ? JSON.parse(body) : {}
	return { data, status: res.status, headers: res.headers } as searchTagResponse
}

export const getSearchTagQueryKey = (params?: SearchTagParams) => {
	return [`/api/search/tag`, ...(params ? [params] : [])] as const
}

export const getSearchTagQueryOptions = <
	TData = Awaited<ReturnType<typeof searchTag>>,
	TError = string | SearchTagDefaultOne,
>(
	params: SearchTagParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof searchTag>>, TError, TData>
		>
		fetch?: RequestInit
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getSearchTagQueryKey(params)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof searchTag>>> = ({
		signal,
	}) => searchTag(params, { signal, ...fetchOptions })

	return { queryKey, queryFn, ...queryOptions }
}

export type SearchTagQueryResult = NonNullable<
	Awaited<ReturnType<typeof searchTag>>
>
export type SearchTagQueryError = string | SearchTagDefaultOne

export function useSearchTag<
	TData = Awaited<ReturnType<typeof searchTag>>,
	TError = string | SearchTagDefaultOne,
>(
	params: SearchTagParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof searchTag>>, TError, TData>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getSearchTagQueryOptions(params, options)

	const query = useQuery(
		() => getSearchTagQueryOptions(params, options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export const getSearchAllResponseMock = (
	overrideResponse: Partial<Extract<DataSearchResponse, object>> = {},
): DataSearchResponse => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: {
		artists: {
			items: Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			})),
			next_cursor: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
		},
		releases: {
			items: Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				title: faker.string.alpha({ length: { min: 10, max: 20 } }),
				cover_art_url: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
			})),
			next_cursor: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
		},
		songs: {
			items: Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				title: faker.string.alpha({ length: { min: 10, max: 20 } }),
			})),
			next_cursor: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
		},
		events: {
			items: Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			})),
			next_cursor: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
		},
		labels: {
			items: Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			})),
			next_cursor: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
		},
		tags: {
			items: Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				type: faker.helpers.arrayElement(Object.values(TagType)),
			})),
			next_cursor: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
		},
	},
	...overrideResponse,
})

export const getSearchArtistResponseMock = (
	overrideResponse: Partial<Extract<DataPaginatedSimpleArtist, object>> = {},
): DataPaginatedSimpleArtist => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: {
		items: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int(),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		})),
		next_cursor: faker.helpers.arrayElement([
			faker.helpers.arrayElement([faker.number.int(), null]),
			undefined,
		]),
	},
	...overrideResponse,
})

export const getSearchEventResponseMock = (
	overrideResponse: Partial<Extract<DataPaginatedSimpleEvent, object>> = {},
): DataPaginatedSimpleEvent => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: {
		items: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int(),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		})),
		next_cursor: faker.helpers.arrayElement([
			faker.helpers.arrayElement([faker.number.int(), null]),
			undefined,
		]),
	},
	...overrideResponse,
})

export const getSearchLabelResponseMock = (
	overrideResponse: Partial<Extract<DataPaginatedSimpleLabel, object>> = {},
): DataPaginatedSimpleLabel => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: {
		items: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int(),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		})),
		next_cursor: faker.helpers.arrayElement([
			faker.helpers.arrayElement([faker.number.int(), null]),
			undefined,
		]),
	},
	...overrideResponse,
})

export const getSearchReleaseResponseMock = (
	overrideResponse: Partial<Extract<DataPaginatedSimpleRelease, object>> = {},
): DataPaginatedSimpleRelease => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: {
		items: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int(),
			title: faker.string.alpha({ length: { min: 10, max: 20 } }),
			cover_art_url: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				undefined,
			]),
		})),
		next_cursor: faker.helpers.arrayElement([
			faker.helpers.arrayElement([faker.number.int(), null]),
			undefined,
		]),
	},
	...overrideResponse,
})

export const getSearchSongResponseMock = (
	overrideResponse: Partial<Extract<DataPaginatedSongRef, object>> = {},
): DataPaginatedSongRef => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: {
		items: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int(),
			title: faker.string.alpha({ length: { min: 10, max: 20 } }),
		})),
		next_cursor: faker.helpers.arrayElement([
			faker.helpers.arrayElement([faker.number.int(), null]),
			undefined,
		]),
	},
	...overrideResponse,
})

export const getSearchTagResponseMock = (
	overrideResponse: Partial<Extract<DataPaginatedTagRef, object>> = {},
): DataPaginatedTagRef => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: {
		items: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int(),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			type: faker.helpers.arrayElement(Object.values(TagType)),
		})),
		next_cursor: faker.helpers.arrayElement([
			faker.helpers.arrayElement([faker.number.int(), null]),
			undefined,
		]),
	},
	...overrideResponse,
})

export const getSearchAllMockHandler = (
	overrideResponse?:
		| DataSearchResponse
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<DataSearchResponse> | DataSearchResponse),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/search",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getSearchAllResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getSearchArtistMockHandler = (
	overrideResponse?:
		| DataPaginatedSimpleArtist
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<DataPaginatedSimpleArtist> | DataPaginatedSimpleArtist),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/search/artist",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getSearchArtistResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getSearchEventMockHandler = (
	overrideResponse?:
		| DataPaginatedSimpleEvent
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<DataPaginatedSimpleEvent> | DataPaginatedSimpleEvent),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/search/event",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getSearchEventResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getSearchLabelMockHandler = (
	overrideResponse?:
		| DataPaginatedSimpleLabel
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<DataPaginatedSimpleLabel> | DataPaginatedSimpleLabel),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/search/label",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getSearchLabelResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getSearchReleaseMockHandler = (
	overrideResponse?:
		| DataPaginatedSimpleRelease
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<DataPaginatedSimpleRelease> | DataPaginatedSimpleRelease),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/search/release",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getSearchReleaseResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getSearchSongMockHandler = (
	overrideResponse?:
		| DataPaginatedSongRef
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<DataPaginatedSongRef> | DataPaginatedSongRef),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/search/song",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getSearchSongResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getSearchTagMockHandler = (
	overrideResponse?:
		| DataPaginatedTagRef
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<DataPaginatedTagRef> | DataPaginatedTagRef),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/search/tag",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getSearchTagResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}
export const getSearchMock = () => [
	getSearchAllMockHandler(),
	getSearchArtistMockHandler(),
	getSearchEventMockHandler(),
	getSearchLabelMockHandler(),
	getSearchReleaseMockHandler(),
	getSearchSongMockHandler(),
	getSearchTagMockHandler(),
]
