/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Touhou Cloud DB
 * TODO
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker"
import { useMutation, useQuery } from "@tanstack/solid-query"
import type {
	DataTag,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	SolidMutationOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/solid-query"
import { HttpResponse, http } from "msw"
import type { RequestHandlerOptions } from "msw"

import type {
	CreateSongDefaultOne,
	ExploreSong400,
	ExploreSong500,
	ExploreSongDefaultOne,
	ExploreSongParams,
	FindSongByIdDefaultOne,
	FindSongByKeywordDefaultOne,
	FindSongByKeywordParams,
	NewCorrectionNewSong,
	UpdateSongDefaultOne,
} from "./touhouCloudDB.schemas"
import type {
	CreditRoleRef,
	DataCorrectionSubmissionResult,
	DataOptionSong,
	DataPageSong,
	DataVecSong,
	Song,
} from "./touhouCloudDB.schemas"

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308
export type HTTPStatusCode4xx =
	| 400
	| 401
	| 402
	| 403
	| 404
	| 405
	| 406
	| 407
	| 408
	| 409
	| 410
	| 411
	| 412
	| 413
	| 414
	| 415
	| 416
	| 417
	| 418
	| 419
	| 420
	| 421
	| 422
	| 423
	| 424
	| 426
	| 428
	| 429
	| 431
	| 451
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511
export type HTTPStatusCodes =
	| HTTPStatusCode1xx
	| HTTPStatusCode2xx
	| HTTPStatusCode3xx
	| HTTPStatusCode4xx
	| HTTPStatusCode5xx

export type findSongByKeywordResponse200 = {
	data: DataVecSong
	status: 200
}

export type findSongByKeywordResponse429 = {
	data: string
	status: 429
}

export type findSongByKeywordResponseDefaultApplicationJson = {
	data: FindSongByKeywordDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type findSongByKeywordResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type findSongByKeywordResponseSuccess = findSongByKeywordResponse200 & {
	headers: Headers
}
export type findSongByKeywordResponseError = (
	| findSongByKeywordResponse429
	| findSongByKeywordResponseDefaultApplicationJson
	| findSongByKeywordResponseDefaultTextPlain
) & {
	headers: Headers
}

export type findSongByKeywordResponse =
	| findSongByKeywordResponseSuccess
	| findSongByKeywordResponseError

export const getFindSongByKeywordUrl = (params: FindSongByKeywordParams) => {
	const normalizedParams = new URLSearchParams()

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString())
		}
	})

	const stringifiedParams = normalizedParams.toString()

	return stringifiedParams.length > 0 ? `/song?${stringifiedParams}` : `/song`
}

export const findSongByKeyword = async (
	params: FindSongByKeywordParams,
	options?: RequestInit,
): Promise<findSongByKeywordResponse> => {
	const res = await fetch(getFindSongByKeywordUrl(params), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: findSongByKeywordResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as findSongByKeywordResponse
}

export const getFindSongByKeywordQueryKey = (
	params?: FindSongByKeywordParams,
) => {
	return [`/song`, ...(params ? [params] : [])] as const
}

export const getFindSongByKeywordQueryOptions = <
	TData = Awaited<ReturnType<typeof findSongByKeyword>>,
	TError = string | FindSongByKeywordDefaultOne,
>(
	params: FindSongByKeywordParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof findSongByKeyword>>,
				TError,
				TData
			>
		>
		fetch?: RequestInit
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getFindSongByKeywordQueryKey(params)

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof findSongByKeyword>>
	> = ({ signal }) => findSongByKeyword(params, { signal, ...fetchOptions })

	return { queryKey, queryFn, ...queryOptions }
}

export type FindSongByKeywordQueryResult = NonNullable<
	Awaited<ReturnType<typeof findSongByKeyword>>
>
export type FindSongByKeywordQueryError = string | FindSongByKeywordDefaultOne

export function useFindSongByKeyword<
	TData = Awaited<ReturnType<typeof findSongByKeyword>>,
	TError = string | FindSongByKeywordDefaultOne,
>(
	params: FindSongByKeywordParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof findSongByKeyword>>,
				TError,
				TData
			>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getFindSongByKeywordQueryOptions(params, options)

	const query = useQuery(
		() => getFindSongByKeywordQueryOptions(params, options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export type createSongResponse200 = {
	data: DataCorrectionSubmissionResult
	status: 200
}

export type createSongResponse429 = {
	data: string
	status: 429
}

export type createSongResponseDefaultApplicationJson = {
	data: CreateSongDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type createSongResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type createSongResponseSuccess = createSongResponse200 & {
	headers: Headers
}
export type createSongResponseError = (
	| createSongResponse429
	| createSongResponseDefaultApplicationJson
	| createSongResponseDefaultTextPlain
) & {
	headers: Headers
}

export type createSongResponse =
	| createSongResponseSuccess
	| createSongResponseError

export const getCreateSongUrl = () => {
	return `/song`
}

export const createSong = async (
	newCorrectionNewSong: NewCorrectionNewSong,
	options?: RequestInit,
): Promise<createSongResponse> => {
	const res = await fetch(getCreateSongUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(newCorrectionNewSong),
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: createSongResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as createSongResponse
}

export const getCreateSongMutationOptions = <
	TError = string | CreateSongDefaultOne,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createSong>>,
		TError,
		{ data: NewCorrectionNewSong },
		TContext
	>
	fetch?: RequestInit
}): SolidMutationOptions<
	Awaited<ReturnType<typeof createSong>>,
	TError,
	{ data: NewCorrectionNewSong },
	TContext
> => {
	const mutationKey = ["createSong"]
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation
			&& "mutationKey" in options.mutation
			&& options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createSong>>,
		{ data: NewCorrectionNewSong }
	> = (props) => {
		const { data } = props ?? {}

		return createSong(data, fetchOptions)
	}

	return { mutationFn, ...mutationOptions }
}

export type CreateSongMutationResult = NonNullable<
	Awaited<ReturnType<typeof createSong>>
>
export type CreateSongMutationBody = NewCorrectionNewSong
export type CreateSongMutationError = string | CreateSongDefaultOne

export const useCreateSong = <
	TError = string | CreateSongDefaultOne,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createSong>>,
			TError,
			{ data: NewCorrectionNewSong },
			TContext
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createSong>>,
	TError,
	{ data: NewCorrectionNewSong },
	TContext
> => {
	return useMutation(() => getCreateSongMutationOptions(options), queryClient)
}
export type exploreSongResponse200 = {
	data: DataPageSong
	status: 200
}

export type exploreSongResponse400 = {
	data: ExploreSong400
	status: 400
}

export type exploreSongResponse429 = {
	data: string
	status: 429
}

export type exploreSongResponse500 = {
	data: ExploreSong500
	status: 500
}

export type exploreSongResponseDefaultApplicationJson = {
	data: ExploreSongDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 400 | 429 | 500>
}

export type exploreSongResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 400 | 429 | 500>
}

export type exploreSongResponseSuccess = exploreSongResponse200 & {
	headers: Headers
}
export type exploreSongResponseError = (
	| exploreSongResponse400
	| exploreSongResponse429
	| exploreSongResponse500
	| exploreSongResponseDefaultApplicationJson
	| exploreSongResponseDefaultTextPlain
) & {
	headers: Headers
}

export type exploreSongResponse =
	| exploreSongResponseSuccess
	| exploreSongResponseError

export const getExploreSongUrl = (params?: ExploreSongParams) => {
	const normalizedParams = new URLSearchParams()

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString())
		}
	})

	const stringifiedParams = normalizedParams.toString()

	return stringifiedParams.length > 0
		? `/song/explore?${stringifiedParams}`
		: `/song/explore`
}

export const exploreSong = async (
	params?: ExploreSongParams,
	options?: RequestInit,
): Promise<exploreSongResponse> => {
	const res = await fetch(getExploreSongUrl(params), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: exploreSongResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as exploreSongResponse
}

export const getExploreSongQueryKey = (params?: ExploreSongParams) => {
	return [`/song/explore`, ...(params ? [params] : [])] as const
}

export const getExploreSongQueryOptions = <
	TData = Awaited<ReturnType<typeof exploreSong>>,
	TError = ExploreSong400 | string | ExploreSong500 | ExploreSongDefaultOne,
>(
	params?: ExploreSongParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof exploreSong>>, TError, TData>
		>
		fetch?: RequestInit
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getExploreSongQueryKey(params)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof exploreSong>>> = ({
		signal,
	}) => exploreSong(params, { signal, ...fetchOptions })

	return { queryKey, queryFn, ...queryOptions }
}

export type ExploreSongQueryResult = NonNullable<
	Awaited<ReturnType<typeof exploreSong>>
>
export type ExploreSongQueryError =
	| ExploreSong400
	| string
	| ExploreSong500
	| ExploreSongDefaultOne

export function useExploreSong<
	TData = Awaited<ReturnType<typeof exploreSong>>,
	TError = ExploreSong400 | string | ExploreSong500 | ExploreSongDefaultOne,
>(
	params?: ExploreSongParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof exploreSong>>, TError, TData>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getExploreSongQueryOptions(params, options)

	const query = useQuery(
		() => getExploreSongQueryOptions(params, options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export type findSongByIdResponse200 = {
	data: DataOptionSong
	status: 200
}

export type findSongByIdResponse429 = {
	data: string
	status: 429
}

export type findSongByIdResponseDefaultApplicationJson = {
	data: FindSongByIdDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type findSongByIdResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type findSongByIdResponseSuccess = findSongByIdResponse200 & {
	headers: Headers
}
export type findSongByIdResponseError = (
	| findSongByIdResponse429
	| findSongByIdResponseDefaultApplicationJson
	| findSongByIdResponseDefaultTextPlain
) & {
	headers: Headers
}

export type findSongByIdResponse =
	| findSongByIdResponseSuccess
	| findSongByIdResponseError

export const getFindSongByIdUrl = (id: number) => {
	return `/song/${id}`
}

export const findSongById = async (
	id: number,
	options?: RequestInit,
): Promise<findSongByIdResponse> => {
	const res = await fetch(getFindSongByIdUrl(id), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: findSongByIdResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as findSongByIdResponse
}

export const getFindSongByIdQueryKey = (id: number) => {
	return [`/song/${id}`] as const
}

export const getFindSongByIdQueryOptions = <
	TData = Awaited<ReturnType<typeof findSongById>>,
	TError = string | FindSongByIdDefaultOne,
>(
	id: number,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof findSongById>>, TError, TData>
		>
		fetch?: RequestInit
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getFindSongByIdQueryKey(id)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof findSongById>>> = ({
		signal,
	}) => findSongById(id, { signal, ...fetchOptions })

	return { queryKey, queryFn, enabled: !!id, ...queryOptions }
}

export type FindSongByIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof findSongById>>
>
export type FindSongByIdQueryError = string | FindSongByIdDefaultOne

export function useFindSongById<
	TData = Awaited<ReturnType<typeof findSongById>>,
	TError = string | FindSongByIdDefaultOne,
>(
	id: number,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof findSongById>>, TError, TData>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getFindSongByIdQueryOptions(id, options)

	const query = useQuery(
		() => getFindSongByIdQueryOptions(id, options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export type updateSongResponse200 = {
	data: DataCorrectionSubmissionResult
	status: 200
}

export type updateSongResponse429 = {
	data: string
	status: 429
}

export type updateSongResponseDefaultApplicationJson = {
	data: UpdateSongDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type updateSongResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type updateSongResponseSuccess = updateSongResponse200 & {
	headers: Headers
}
export type updateSongResponseError = (
	| updateSongResponse429
	| updateSongResponseDefaultApplicationJson
	| updateSongResponseDefaultTextPlain
) & {
	headers: Headers
}

export type updateSongResponse =
	| updateSongResponseSuccess
	| updateSongResponseError

export const getUpdateSongUrl = (id: number) => {
	return `/song/${id}`
}

export const updateSong = async (
	id: number,
	newCorrectionNewSong: NewCorrectionNewSong,
	options?: RequestInit,
): Promise<updateSongResponse> => {
	const res = await fetch(getUpdateSongUrl(id), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(newCorrectionNewSong),
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: updateSongResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as updateSongResponse
}

export const getUpdateSongMutationOptions = <
	TError = string | UpdateSongDefaultOne,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateSong>>,
		TError,
		{ id: number; data: NewCorrectionNewSong },
		TContext
	>
	fetch?: RequestInit
}): SolidMutationOptions<
	Awaited<ReturnType<typeof updateSong>>,
	TError,
	{ id: number; data: NewCorrectionNewSong },
	TContext
> => {
	const mutationKey = ["updateSong"]
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation
			&& "mutationKey" in options.mutation
			&& options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateSong>>,
		{ id: number; data: NewCorrectionNewSong }
	> = (props) => {
		const { id, data } = props ?? {}

		return updateSong(id, data, fetchOptions)
	}

	return { mutationFn, ...mutationOptions }
}

export type UpdateSongMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateSong>>
>
export type UpdateSongMutationBody = NewCorrectionNewSong
export type UpdateSongMutationError = string | UpdateSongDefaultOne

export const useUpdateSong = <
	TError = string | UpdateSongDefaultOne,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateSong>>,
			TError,
			{ id: number; data: NewCorrectionNewSong },
			TContext
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateSong>>,
	TError,
	{ id: number; data: NewCorrectionNewSong },
	TContext
> => {
	return useMutation(() => getUpdateSongMutationOptions(options), queryClient)
}

export const getFindSongByKeywordResponseCreditRoleRefMock = (
	overrideResponse: Partial<CreditRoleRef> = {},
): CreditRoleRef => ({
	...{
		id: faker.number.int(),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	},
	...overrideResponse,
})

export const getFindSongByKeywordResponseMock = (
	overrideResponse: Partial<Extract<DataVecSong, object>> = {},
): DataVecSong => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int(),
		title: faker.string.alpha({ length: { min: 10, max: 20 } }),
		artists: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			})),
			undefined,
		]),
		releases: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				title: faker.string.alpha({ length: { min: 10, max: 20 } }),
				cover_art_url: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
			})),
			undefined,
		]),
		credits: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				artist: {
					id: faker.number.int(),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				},
				role: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						null,
						{ ...getFindSongByKeywordResponseCreditRoleRefMock() },
					]),
					undefined,
				]),
			})),
			undefined,
		]),
		languages: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				code: faker.string.alpha({ length: { min: 10, max: 20 } }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			})),
			undefined,
		]),
		localized_titles: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				language: {
					id: faker.number.int(),
					code: faker.string.alpha({ length: { min: 10, max: 20 } }),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				},
				title: faker.string.alpha({ length: { min: 10, max: 20 } }),
			})),
			undefined,
		]),
		lyrics: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				song_id: faker.number.int(),
				content: faker.string.alpha({ length: { min: 10, max: 20 } }),
				is_main: faker.datatype.boolean(),
				language: {
					id: faker.number.int(),
					code: faker.string.alpha({ length: { min: 10, max: 20 } }),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				},
			})),
			undefined,
		]),
	})),
	...overrideResponse,
})

export const getCreateSongResponseMock = (
	overrideResponse: Partial<
		Extract<DataCorrectionSubmissionResult, object>
	> = {},
): DataCorrectionSubmissionResult => ({
	status: faker.helpers.arrayElement(["Ok"] as const),
	data: { correction_id: faker.number.int(), entity_id: faker.number.int() },
	...overrideResponse,
})

export const getExploreSongResponseCreditRoleRefMock = (
	overrideResponse: Partial<CreditRoleRef> = {},
): CreditRoleRef => ({
	...{
		id: faker.number.int(),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	},
	...overrideResponse,
})

export const getExploreSongResponseMock = (
	overrideResponse: Partial<Extract<DataPageSong, object>> = {},
): DataPageSong => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: {
		items: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int(),
			title: faker.string.alpha({ length: { min: 10, max: 20 } }),
			artists: faker.helpers.arrayElement([
				Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					id: faker.number.int(),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				})),
				undefined,
			]),
			releases: faker.helpers.arrayElement([
				Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					id: faker.number.int(),
					title: faker.string.alpha({ length: { min: 10, max: 20 } }),
					cover_art_url: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						undefined,
					]),
				})),
				undefined,
			]),
			credits: faker.helpers.arrayElement([
				Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					artist: {
						id: faker.number.int(),
						name: faker.string.alpha({ length: { min: 10, max: 20 } }),
					},
					role: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							null,
							{ ...getExploreSongResponseCreditRoleRefMock() },
						]),
						undefined,
					]),
				})),
				undefined,
			]),
			languages: faker.helpers.arrayElement([
				Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					id: faker.number.int(),
					code: faker.string.alpha({ length: { min: 10, max: 20 } }),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				})),
				undefined,
			]),
			localized_titles: faker.helpers.arrayElement([
				Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					language: {
						id: faker.number.int(),
						code: faker.string.alpha({ length: { min: 10, max: 20 } }),
						name: faker.string.alpha({ length: { min: 10, max: 20 } }),
					},
					title: faker.string.alpha({ length: { min: 10, max: 20 } }),
				})),
				undefined,
			]),
			lyrics: faker.helpers.arrayElement([
				Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					id: faker.number.int(),
					song_id: faker.number.int(),
					content: faker.string.alpha({ length: { min: 10, max: 20 } }),
					is_main: faker.datatype.boolean(),
					language: {
						id: faker.number.int(),
						code: faker.string.alpha({ length: { min: 10, max: 20 } }),
						name: faker.string.alpha({ length: { min: 10, max: 20 } }),
					},
				})),
				undefined,
			]),
		})),
		page: faker.number.int({ min: 0 }),
		page_size: faker.number.int({ min: 0 }),
		total_items: faker.number.int({ min: 0 }),
		total_pages: faker.number.int({ min: 0 }),
	},
	...overrideResponse,
})

export const getFindSongByIdResponseCreditRoleRefMock = (
	overrideResponse: Partial<CreditRoleRef> = {},
): CreditRoleRef => ({
	...{
		id: faker.number.int(),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	},
	...overrideResponse,
})

export const getFindSongByIdResponseSongMock = (
	overrideResponse: Partial<Song> = {},
): Song => ({
	...{
		id: faker.number.int(),
		title: faker.string.alpha({ length: { min: 10, max: 20 } }),
		artists: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			})),
			undefined,
		]),
		releases: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				title: faker.string.alpha({ length: { min: 10, max: 20 } }),
				cover_art_url: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
			})),
			undefined,
		]),
		credits: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				artist: {
					id: faker.number.int(),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				},
				role: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						null,
						{ ...getFindSongByIdResponseCreditRoleRefMock() },
					]),
					undefined,
				]),
			})),
			undefined,
		]),
		languages: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				code: faker.string.alpha({ length: { min: 10, max: 20 } }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			})),
			undefined,
		]),
		localized_titles: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				language: {
					id: faker.number.int(),
					code: faker.string.alpha({ length: { min: 10, max: 20 } }),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				},
				title: faker.string.alpha({ length: { min: 10, max: 20 } }),
			})),
			undefined,
		]),
		lyrics: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int(),
				song_id: faker.number.int(),
				content: faker.string.alpha({ length: { min: 10, max: 20 } }),
				is_main: faker.datatype.boolean(),
				language: {
					id: faker.number.int(),
					code: faker.string.alpha({ length: { min: 10, max: 20 } }),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				},
			})),
			undefined,
		]),
	},
	...overrideResponse,
})

export const getFindSongByIdResponseMock = (
	overrideResponse: Partial<Extract<DataOptionSong, object>> = {},
): DataOptionSong => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: faker.helpers.arrayElement([
		null,
		{ ...getFindSongByIdResponseSongMock() },
	]),
	...overrideResponse,
})

export const getUpdateSongResponseMock = (
	overrideResponse: Partial<
		Extract<DataCorrectionSubmissionResult, object>
	> = {},
): DataCorrectionSubmissionResult => ({
	status: faker.helpers.arrayElement(["Ok"] as const),
	data: { correction_id: faker.number.int(), entity_id: faker.number.int() },
	...overrideResponse,
})

export const getFindSongByKeywordMockHandler = (
	overrideResponse?:
		| DataVecSong
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<DataVecSong> | DataVecSong),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/song",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getFindSongByKeywordResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getCreateSongMockHandler = (
	overrideResponse?:
		| DataCorrectionSubmissionResult
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) =>
				| Promise<DataCorrectionSubmissionResult>
				| DataCorrectionSubmissionResult),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/song",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getCreateSongResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getExploreSongMockHandler = (
	overrideResponse?:
		| DataPageSong
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<DataPageSong> | DataPageSong),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/song/explore",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getExploreSongResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getFindSongByIdMockHandler = (
	overrideResponse?:
		| DataOptionSong
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<DataOptionSong> | DataOptionSong),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/song/:id",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getFindSongByIdResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getUpdateSongMockHandler = (
	overrideResponse?:
		| DataCorrectionSubmissionResult
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) =>
				| Promise<DataCorrectionSubmissionResult>
				| DataCorrectionSubmissionResult),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/song/:id",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getUpdateSongResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}
export const getSongMock = () => [
	getFindSongByKeywordMockHandler(),
	getCreateSongMockHandler(),
	getExploreSongMockHandler(),
	getFindSongByIdMockHandler(),
	getUpdateSongMockHandler(),
]
