/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Touhou Cloud DB
 * TODO
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker"
import { useMutation, useQuery } from "@tanstack/solid-query"
import type {
	DataTag,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	SolidMutationOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/solid-query"
import { HttpResponse, http } from "msw"
import type { RequestHandlerOptions } from "msw"

import type {
	DeleteVoteBody,
	DeleteVoteDefaultOne,
	GetTagsDefaultOne,
	GetTagsParams,
	VoteBody,
	VoteTagDefaultOne,
} from "./touhouCloudDB.schemas"
import type { DataPaginatedTagAggregate } from "./touhouCloudDB.schemas"

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308
export type HTTPStatusCode4xx =
	| 400
	| 401
	| 402
	| 403
	| 404
	| 405
	| 406
	| 407
	| 408
	| 409
	| 410
	| 411
	| 412
	| 413
	| 414
	| 415
	| 416
	| 417
	| 418
	| 419
	| 420
	| 421
	| 422
	| 423
	| 424
	| 426
	| 428
	| 429
	| 431
	| 451
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511
export type HTTPStatusCodes =
	| HTTPStatusCode1xx
	| HTTPStatusCode2xx
	| HTTPStatusCode3xx
	| HTTPStatusCode4xx
	| HTTPStatusCode5xx

export type voteTagResponse200 = {
	data: void
	status: 200
}

export type voteTagResponse404 = {
	data: void
	status: 404
}

export type voteTagResponse429 = {
	data: string
	status: 429
}

export type voteTagResponseDefaultApplicationJson = {
	data: VoteTagDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 404 | 429>
}

export type voteTagResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 404 | 429>
}

export type voteTagResponseSuccess = voteTagResponse200 & {
	headers: Headers
}
export type voteTagResponseError = (
	| voteTagResponse404
	| voteTagResponse429
	| voteTagResponseDefaultApplicationJson
	| voteTagResponseDefaultTextPlain
) & {
	headers: Headers
}

export type voteTagResponse = voteTagResponseSuccess | voteTagResponseError

export const getVoteTagUrl = (
	entityType: "artist" | "release" | "song",
	id: number,
) => {
	return `/api/${entityType}/${id}/tag-vote`
}

export const voteTag = async (
	entityType: "artist" | "release" | "song",
	id: number,
	voteBody: VoteBody,
	options?: RequestInit,
): Promise<voteTagResponse> => {
	const res = await fetch(getVoteTagUrl(entityType, id), {
		...options,
		method: "PUT",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(voteBody),
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: voteTagResponse["data"] = body ? JSON.parse(body) : {}
	return { data, status: res.status, headers: res.headers } as voteTagResponse
}

export const getVoteTagMutationOptions = <
	TError = void | string | VoteTagDefaultOne,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof voteTag>>,
		TError,
		{ entityType: "artist" | "release" | "song"; id: number; data: VoteBody },
		TContext
	>
	fetch?: RequestInit
}): SolidMutationOptions<
	Awaited<ReturnType<typeof voteTag>>,
	TError,
	{ entityType: "artist" | "release" | "song"; id: number; data: VoteBody },
	TContext
> => {
	const mutationKey = ["voteTag"]
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation
			&& "mutationKey" in options.mutation
			&& options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof voteTag>>,
		{ entityType: "artist" | "release" | "song"; id: number; data: VoteBody }
	> = (props) => {
		const { entityType, id, data } = props ?? {}

		return voteTag(entityType, id, data, fetchOptions)
	}

	return { mutationFn, ...mutationOptions }
}

export type VoteTagMutationResult = NonNullable<
	Awaited<ReturnType<typeof voteTag>>
>
export type VoteTagMutationBody = VoteBody
export type VoteTagMutationError = void | string | VoteTagDefaultOne

export const useVoteTag = <
	TError = void | string | VoteTagDefaultOne,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof voteTag>>,
			TError,
			{ entityType: "artist" | "release" | "song"; id: number; data: VoteBody },
			TContext
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof voteTag>>,
	TError,
	{ entityType: "artist" | "release" | "song"; id: number; data: VoteBody },
	TContext
> => {
	return useMutation(() => getVoteTagMutationOptions(options), queryClient)
}
export type deleteVoteResponse200 = {
	data: void
	status: 200
}

export type deleteVoteResponse429 = {
	data: string
	status: 429
}

export type deleteVoteResponseDefaultApplicationJson = {
	data: DeleteVoteDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type deleteVoteResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type deleteVoteResponseSuccess = deleteVoteResponse200 & {
	headers: Headers
}
export type deleteVoteResponseError = (
	| deleteVoteResponse429
	| deleteVoteResponseDefaultApplicationJson
	| deleteVoteResponseDefaultTextPlain
) & {
	headers: Headers
}

export type deleteVoteResponse =
	| deleteVoteResponseSuccess
	| deleteVoteResponseError

export const getDeleteVoteUrl = (
	entityType: "artist" | "release" | "song",
	id: number,
) => {
	return `/api/${entityType}/${id}/tag-vote`
}

export const deleteVote = async (
	entityType: "artist" | "release" | "song",
	id: number,
	deleteVoteBody: DeleteVoteBody,
	options?: RequestInit,
): Promise<deleteVoteResponse> => {
	const res = await fetch(getDeleteVoteUrl(entityType, id), {
		...options,
		method: "DELETE",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(deleteVoteBody),
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: deleteVoteResponse["data"] = body ? JSON.parse(body) : {}
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as deleteVoteResponse
}

export const getDeleteVoteMutationOptions = <
	TError = string | DeleteVoteDefaultOne,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteVote>>,
		TError,
		{
			entityType: "artist" | "release" | "song"
			id: number
			data: DeleteVoteBody
		},
		TContext
	>
	fetch?: RequestInit
}): SolidMutationOptions<
	Awaited<ReturnType<typeof deleteVote>>,
	TError,
	{
		entityType: "artist" | "release" | "song"
		id: number
		data: DeleteVoteBody
	},
	TContext
> => {
	const mutationKey = ["deleteVote"]
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation
			&& "mutationKey" in options.mutation
			&& options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteVote>>,
		{
			entityType: "artist" | "release" | "song"
			id: number
			data: DeleteVoteBody
		}
	> = (props) => {
		const { entityType, id, data } = props ?? {}

		return deleteVote(entityType, id, data, fetchOptions)
	}

	return { mutationFn, ...mutationOptions }
}

export type DeleteVoteMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteVote>>
>
export type DeleteVoteMutationBody = DeleteVoteBody
export type DeleteVoteMutationError = string | DeleteVoteDefaultOne

export const useDeleteVote = <
	TError = string | DeleteVoteDefaultOne,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteVote>>,
			TError,
			{
				entityType: "artist" | "release" | "song"
				id: number
				data: DeleteVoteBody
			},
			TContext
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteVote>>,
	TError,
	{
		entityType: "artist" | "release" | "song"
		id: number
		data: DeleteVoteBody
	},
	TContext
> => {
	return useMutation(() => getDeleteVoteMutationOptions(options), queryClient)
}
export type getTagsResponse200 = {
	data: DataPaginatedTagAggregate
	status: 200
}

export type getTagsResponse429 = {
	data: string
	status: 429
}

export type getTagsResponseDefaultApplicationJson = {
	data: GetTagsDefaultOne
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type getTagsResponseDefaultTextPlain = {
	data: string
	status: Exclude<HTTPStatusCodes, 200 | 429>
}

export type getTagsResponseSuccess = getTagsResponse200 & {
	headers: Headers
}
export type getTagsResponseError = (
	| getTagsResponse429
	| getTagsResponseDefaultApplicationJson
	| getTagsResponseDefaultTextPlain
) & {
	headers: Headers
}

export type getTagsResponse = getTagsResponseSuccess | getTagsResponseError

export const getGetTagsUrl = (
	entityType: "artist" | "release" | "song",
	id: number,
	params?: GetTagsParams,
) => {
	const normalizedParams = new URLSearchParams()

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString())
		}
	})

	const stringifiedParams = normalizedParams.toString()

	return stringifiedParams.length > 0
		? `/api/${entityType}/${id}/tags?${stringifiedParams}`
		: `/api/${entityType}/${id}/tags`
}

export const getTags = async (
	entityType: "artist" | "release" | "song",
	id: number,
	params?: GetTagsParams,
	options?: RequestInit,
): Promise<getTagsResponse> => {
	const res = await fetch(getGetTagsUrl(entityType, id, params), {
		...options,
		method: "GET",
	})

	const body = [204, 205, 304].includes(res.status) ? null : await res.text()

	const data: getTagsResponse["data"] = body ? JSON.parse(body) : {}
	return { data, status: res.status, headers: res.headers } as getTagsResponse
}

export const getGetTagsQueryKey = (
	entityType: "artist" | "release" | "song",
	id: number,
	params?: GetTagsParams,
) => {
	return [`/api/${entityType}/${id}/tags`, ...(params ? [params] : [])] as const
}

export const getGetTagsQueryOptions = <
	TData = Awaited<ReturnType<typeof getTags>>,
	TError = string | GetTagsDefaultOne,
>(
	entityType: "artist" | "release" | "song",
	id: number,
	params?: GetTagsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getTags>>, TError, TData>
		>
		fetch?: RequestInit
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {}

	const queryKey = getGetTagsQueryKey(entityType, id, params)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getTags>>> = ({
		signal,
	}) => getTags(entityType, id, params, { signal, ...fetchOptions })

	return { queryKey, queryFn, enabled: !!(entityType && id), ...queryOptions }
}

export type GetTagsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getTags>>
>
export type GetTagsQueryError = string | GetTagsDefaultOne

export function useGetTags<
	TData = Awaited<ReturnType<typeof getTags>>,
	TError = string | GetTagsDefaultOne,
>(
	entityType: "artist" | "release" | "song",
	id: number,
	params?: GetTagsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getTags>>, TError, TData>
		>
		fetch?: RequestInit
	},
	queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getGetTagsQueryOptions(entityType, id, params, options)

	const query = useQuery(
		() => getGetTagsQueryOptions(entityType, id, params, options),
		queryClient,
	)

	return Object.assign(query, { queryKey: queryOptions.queryKey }) as any
}

export const getGetTagsResponseMock = (
	overrideResponse: Partial<Extract<DataPaginatedTagAggregate, object>> = {},
): DataPaginatedTagAggregate => ({
	status: faker.string.alpha({ length: { min: 10, max: 20 } }),
	data: {
		items: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int(),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			count: faker.number.int(),
			relevance: faker.number.float({ fractionDigits: 2 }),
			user_vote: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
		})),
		next_cursor: faker.helpers.arrayElement([
			faker.helpers.arrayElement([faker.number.int(), null]),
			undefined,
		]),
	},
	...overrideResponse,
})

export const getVoteTagMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.put>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.put(
		"*/:entityType/:id/tag-vote",
		async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info)
			}

			return new HttpResponse(null, { status: 200 })
		},
		options,
	)
}

export const getDeleteVoteMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.delete>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.delete(
		"*/:entityType/:id/tag-vote",
		async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info)
			}

			return new HttpResponse(null, { status: 200 })
		},
		options,
	)
}

export const getGetTagsMockHandler = (
	overrideResponse?:
		| DataPaginatedTagAggregate
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<DataPaginatedTagAggregate> | DataPaginatedTagAggregate),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/:entityType/:id/tags",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getGetTagsResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}
export const getTagVoteMock = () => [
	getVoteTagMockHandler(),
	getDeleteVoteMockHandler(),
	getGetTagsMockHandler(),
]
