/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Touhou Cloud DB
 * TODO
 * OpenAPI spec version: 0.1.0
 */
export interface AlternativeName {
	id: number
	name: string
}

export type ArtistType = (typeof ArtistType)[keyof typeof ArtistType]

export const ArtistType = {
	Solo: "Solo",
	Multiple: "Multiple",
	Unknown: "Unknown",
} as const

export type DatePrecision = (typeof DatePrecision)[keyof typeof DatePrecision]

export const DatePrecision = {
	Day: "Day",
	Month: "Month",
	Year: "Year",
} as const

export interface DateWithPrecision {
	value: string
	precision: DatePrecision
}

export interface Language {
	id: number
	code: string
	name: string
}

export interface LocalizedName {
	language: Language
	name: string
}

export interface Location {
	/** @nullable */
	country?: string | null
	/** @nullable */
	province?: string | null
	/** @nullable */
	city?: string | null
}

export interface CreditRoleRef {
	id: number
	name: string
}

export interface Tenure {
	/** @nullable */
	join_year?: number | null
	/** @nullable */
	leave_year?: number | null
}

export interface Membership {
	artist_id: number
	roles?: CreditRoleRef[]
	tenure?: Tenure[]
}

export interface Artist {
	id: number
	name: string
	artist_type: ArtistType
	/**
	 * Aliases without own page
	 * @nullable
	 */
	text_aliases?: string[] | null
	start_date?: null | DateWithPrecision
	end_date?: null | DateWithPrecision
	/**
	 * Profile image of artist
	 * @nullable
	 */
	profile_image_url?: string | null
	/** List of id of artist aliases */
	aliases?: number[]
	links?: string[]
	localized_names?: LocalizedName[]
	start_location?: Location
	current_location?: Location
	/** Groups list for individuals, member list for groups, */
	memberships?: Membership[]
}

export interface ArtistCommonFilter {
	artist_type?: ArtistType[]
	exclusion?: number[]
}

export type ArtistImageType =
	(typeof ArtistImageType)[keyof typeof ArtistImageType]

export const ArtistImageType = {
	Profile: "Profile",
} as const

export interface ArtistImageQueueTarget {
	artist_id: number
	type: ArtistImageType
}

export interface ArtistReleaseArtist {
	id: number
	name: string
}

export interface AuthCredential {
	username: string
	password: string
}

export interface SimpleLabel {
	id: number
	name: string
}

export interface CatalogNumber {
	catalog_number: string
	label?: null | SimpleLabel
}

export type CorrectionStatus =
	(typeof CorrectionStatus)[keyof typeof CorrectionStatus]

export const CorrectionStatus = {
	Pending: "Pending",
	Approved: "Approved",
	Rejected: "Rejected",
} as const

export type CorrectionType =
	(typeof CorrectionType)[keyof typeof CorrectionType]

export const CorrectionType = {
	Create: "Create",
	Update: "Update",
	Delete: "Delete",
} as const

export type EntityType = (typeof EntityType)[keyof typeof EntityType]

export const EntityType = {
	Artist: "Artist",
	Label: "Label",
	Release: "Release",
	Song: "Song",
	Tag: "Tag",
	Event: "Event",
	SongLyrics: "SongLyrics",
	CreditRole: "CreditRole",
} as const

export interface Correction {
	id: number
	status: CorrectionStatus
	type: CorrectionType
	entity_id: number
	entity_type: EntityType
	created_at: string
	/** @nullable */
	handled_at?: string | null
}

export interface CorrectionDiffEntry {
	path: string
	/** @nullable */
	before?: string | null
	/** @nullable */
	after?: string | null
}

export interface CorrectionDiff {
	entity_id: number
	entity_type: EntityType
	/** @nullable */
	base_correction_id?: number | null
	/** @nullable */
	base_history_id?: number | null
	target_correction_id: number
	target_history_id: number
	changes: CorrectionDiffEntry[]
}

export interface CorrectionUserSummary {
	id: number
	name: string
}

export interface CorrectionHistoryItem {
	id: number
	type: CorrectionType
	created_at: string
	/** @nullable */
	handled_at?: string | null
	author: CorrectionUserSummary
	description: string
}

export interface CorrectionRevisionSummary {
	entity_history_id: number
	author: CorrectionUserSummary
	description: string
}

export type CorrectionSortField =
	(typeof CorrectionSortField)[keyof typeof CorrectionSortField]

export const CorrectionSortField = {
	created_at: "created_at",
	handled_at: "handled_at",
} as const

export interface CorrectionSubmissionResult {
	correction_id: number
	entity_id: number
}

export interface CreditRole {
	id: number
	name: string
	short_description: string
	description: string
}

export interface CreditRoleSummary {
	id: number
	name: string
	short_description: string
}

export type ReleaseType = (typeof ReleaseType)[keyof typeof ReleaseType]

export const ReleaseType = {
	Album: "Album",
	Ep: "Ep",
	Single: "Single",
	Compilation: "Compilation",
	Demo: "Demo",
	Other: "Other",
} as const

export type CursorResponseCreditItemsItem = {
	title: string
	artist: ArtistReleaseArtist[]
	/** @nullable */
	cover_url?: string | null
	release_date?: null | DateWithPrecision
	release_type: ReleaseType
	roles: CreditRoleRef[]
}

export interface CursorResponseCredit {
	items: CursorResponseCreditItemsItem[]
	/** @nullable */
	next_cursor?: number | null
}

export type CursorResponseDiscographyItemsItem = {
	title: string
	/** @nullable */
	cover_url?: string | null
	artist: ArtistReleaseArtist[]
	release_date?: null | DateWithPrecision
	release_type: ReleaseType
}

export interface CursorResponseDiscography {
	items: CursorResponseDiscographyItemsItem[]
	/** @nullable */
	next_cursor?: number | null
}

export type CursorResponseNotificationItemItemsItem = {
	id: number
	notification_kind: string
	target_type: string
	target_id: number
	payload: unknown
	is_read: boolean
	created_at: string
}

export interface CursorResponseNotificationItem {
	items: CursorResponseNotificationItemItemsItem[]
	/** @nullable */
	next_cursor?: number | null
}

export type ImageQueueStatus =
	(typeof ImageQueueStatus)[keyof typeof ImageQueueStatus]

export const ImageQueueStatus = {
	Pending: "Pending",
	Approved: "Approved",
	Rejected: "Rejected",
	Cancelled: "Cancelled",
	Reverted: "Reverted",
} as const

export interface UserSummary {
	id: number
	name: string
}

export type CursorResponsePendingImageQueueItemItemsItem = {
	id: number
	/** @nullable */
	image_id?: number | null
	status: ImageQueueStatus
	created_at: string
	created_by: UserSummary
}

export interface CursorResponsePendingImageQueueItem {
	items: CursorResponsePendingImageQueueItemItemsItem[]
	/** @nullable */
	next_cursor?: number | null
}

export type CursorResponseSimpleArtistItemsItem = {
	id: number
	name: string
}

export interface CursorResponseSimpleArtist {
	items: CursorResponseSimpleArtistItemsItem[]
	/** @nullable */
	next_cursor?: number | null
}

export type CursorResponseSimpleEventItemsItem = {
	id: number
	name: string
}

export interface CursorResponseSimpleEvent {
	items: CursorResponseSimpleEventItemsItem[]
	/** @nullable */
	next_cursor?: number | null
}

export type CursorResponseSimpleLabelItemsItem = {
	id: number
	name: string
}

export interface CursorResponseSimpleLabel {
	items: CursorResponseSimpleLabelItemsItem[]
	/** @nullable */
	next_cursor?: number | null
}

export type CursorResponseSimpleReleaseItemsItem = {
	id: number
	title: string
	/** @nullable */
	cover_art_url?: string | null
}

export interface CursorResponseSimpleRelease {
	items: CursorResponseSimpleReleaseItemsItem[]
	/** @nullable */
	next_cursor?: number | null
}

export type CursorResponseSongRefItemsItem = {
	id: number
	title: string
}

export interface CursorResponseSongRef {
	items: CursorResponseSongRefItemsItem[]
	/** @nullable */
	next_cursor?: number | null
}

export type CursorResponseTagAggregateItemsItem = {
	id: number
	name: string
	count: number
	relevance: number
	/** @nullable */
	user_vote?: number | null
}

export interface CursorResponseTagAggregate {
	items: CursorResponseTagAggregateItemsItem[]
	/** @nullable */
	next_cursor?: number | null
}

export type TagType = (typeof TagType)[keyof typeof TagType]

export const TagType = {
	Descriptor: "Descriptor",
	Genre: "Genre",
	Movement: "Movement",
	Scene: "Scene",
} as const

export type CursorResponseTagRefItemsItem = {
	id: number
	name: string
	type: TagType
}

export interface CursorResponseTagRef {
	items: CursorResponseTagRefItemsItem[]
	/** @nullable */
	next_cursor?: number | null
}

export type CursorResponseUserImageQueueItemItemsItem = {
	id: number
	/** @nullable */
	image_id?: number | null
	status: ImageQueueStatus
	created_at: string
	/** @nullable */
	handled_at?: string | null
	handled_by?: null | UserSummary
	/** @nullable */
	reverted_at?: string | null
	reverted_by?: null | UserSummary
}

export interface CursorResponseUserImageQueueItem {
	items: CursorResponseUserImageQueueItemItemsItem[]
	/** @nullable */
	next_cursor?: number | null
}

export type UserRoleEnum = (typeof UserRoleEnum)[keyof typeof UserRoleEnum]

export const UserRoleEnum = {
	Admin: "Admin",
	Moderator: "Moderator",
	User: "User",
} as const

export interface UserRole {
	id: number
	name: UserRoleEnum
}

export type CursorResponseUserSummaryItemsItem = {
	id: number
	name: string
	roles: UserRole[]
}

export interface CursorResponseUserSummary {
	items: CursorResponseUserSummaryItemsItem[]
	/** @nullable */
	next_cursor?: number | null
}

export interface ForgotPasswordResponse {
	verification_code_expires_minutes: number
	resend_cooldown_seconds: number
}

export interface DataForgotPasswordResponse {
	status: string
	data: ForgotPasswordResponse
}

export interface HomeMetadata {
	/** @minimum 0 */
	artists_count: number
	/** @minimum 0 */
	releases_count: number
	/** @minimum 0 */
	songs_count: number
	/** @minimum 0 */
	tags_count: number
}

export interface DataHomeMetadata {
	status: string
	data: HomeMetadata
}

export interface ImageSummary {
	id: number
	filename: string
	directory: string
	uploaded_at: string
	uploaded_by: UserSummary
}

export type ReleaseImageType =
	(typeof ReleaseImageType)[keyof typeof ReleaseImageType]

export const ReleaseImageType = {
	Cover: "Cover",
} as const

export interface ReleaseImageQueueTarget {
	release_id: number
	type: ReleaseImageType
}

export interface ImageQueueDetail {
	id: number
	/** @nullable */
	image_id?: number | null
	status: ImageQueueStatus
	created_at: string
	created_by: UserSummary
	/** @nullable */
	handled_at?: string | null
	handled_by?: null | UserSummary
	/** @nullable */
	reverted_at?: string | null
	reverted_by?: null | UserSummary
	image?: null | ImageSummary
	artist?: null | ArtistImageQueueTarget
	release?: null | ReleaseImageQueueTarget
}

export interface DataImageQueueDetail {
	status: string
	data: ImageQueueDetail
}

export interface InitDiscography {
	album: CursorResponseDiscography
	ep: CursorResponseDiscography
	compilation: CursorResponseDiscography
	single: CursorResponseDiscography
	demo: CursorResponseDiscography
	other: CursorResponseDiscography
}

export interface DataInitDiscography {
	status: string
	data: InitDiscography
}

export interface DataOptionArtist {
	status: string
	data: null | Artist
}

export interface DataOptionCreditRole {
	status: string
	data: null | CreditRole
}

export interface Event {
	id: number
	name: string
	short_description?: string
	description?: string
	location?: Location
	start_date?: null | DateWithPrecision
	end_date?: null | DateWithPrecision
	alternative_names?: AlternativeName[]
}

export interface DataOptionEvent {
	status: string
	data: null | Event
}

export interface Label {
	id: number
	name: string
	founded_date?: null | DateWithPrecision
	dissolved_date?: null | DateWithPrecision
	founders: number[]
	localized_names: LocalizedName[]
}

export interface DataOptionLabel {
	status: string
	data: null | Label
}

export interface ReleaseArtist {
	id: number
	name: string
}

export interface ReleaseCredit {
	artist: ReleaseArtist
	role: CreditRoleRef
	/** @nullable */
	on?: number[] | null
}

export interface LocalizedTitle {
	language: Language
	title: string
}

export interface ReleaseDisc {
	id: number
	/** @nullable */
	name?: string | null
}

export interface SongRef {
	id: number
	title: string
}

export interface ReleaseTrack {
	id: number
	/** @nullable */
	track_number?: string | null
	disc_id: number
	/** @nullable */
	display_title?: string | null
	/**
	 * Milliseconds of this track
	 * @nullable
	 */
	duration?: number | null
	song: SongRef
	artists?: ReleaseArtist[]
}

export interface SimpleEvent {
	id: number
	name: string
}

export interface Release {
	id: number
	title: string
	release_type: ReleaseType
	release_date?: null | DateWithPrecision
	recording_date_start?: null | DateWithPrecision
	recording_date_end?: null | DateWithPrecision
	/** @nullable */
	cover_art_url?: string | null
	artists?: ReleaseArtist[]
	credits?: ReleaseCredit[]
	catalog_nums?: CatalogNumber[]
	localized_titles?: LocalizedTitle[]
	discs?: ReleaseDisc[]
	tracks?: ReleaseTrack[]
	events?: SimpleEvent[]
}

export interface DataOptionRelease {
	status: string
	data: null | Release
}

export interface SimpleArtist {
	id: number
	name: string
}

export interface SimpleRelease {
	id: number
	title: string
	/** @nullable */
	cover_art_url?: string | null
}

export interface SongCredit {
	artist: SimpleArtist
	role?: null | CreditRoleRef
}

export interface SongLyrics {
	id: number
	song_id: number
	content: string
	is_main: boolean
	language: Language
}

export interface Song {
	id: number
	title: string
	artists?: SimpleArtist[]
	releases?: SimpleRelease[]
	credits?: SongCredit[]
	languages?: Language[]
	localized_titles?: LocalizedTitle[]
	lyrics?: SongLyrics[]
}

export interface DataOptionSong {
	status: string
	data: null | Song
}

export interface DataOptionSongLyrics {
	status: string
	data: null | SongLyrics
}

export interface TagRef {
	id: number
	name: string
	type: TagType
}

export type TagRelationType =
	(typeof TagRelationType)[keyof typeof TagRelationType]

export const TagRelationType = {
	Inherit: "Inherit",
	Derive: "Derive",
} as const

export interface TagRelation {
	tag: TagRef
	type: TagRelationType
}

export interface Tag {
	id: number
	name: string
	type: TagType
	short_description: string
	description: string
	alt_names?: AlternativeName[]
	relations?: TagRelation[]
}

export interface DataOptionTag {
	status: string
	data: null | Tag
}

export type PageResponseArtistItemsItem = {
	id: number
	name: string
	artist_type: ArtistType
	/**
	 * Aliases without own page
	 * @nullable
	 */
	text_aliases?: string[] | null
	start_date?: null | DateWithPrecision
	end_date?: null | DateWithPrecision
	/**
	 * Profile image of artist
	 * @nullable
	 */
	profile_image_url?: string | null
	/** List of id of artist aliases */
	aliases?: number[]
	links?: string[]
	localized_names?: LocalizedName[]
	start_location?: Location
	current_location?: Location
	/** Groups list for individuals, member list for groups, */
	memberships?: Membership[]
}

export interface PageResponseArtist {
	items: PageResponseArtistItemsItem[]
	/** @minimum 0 */
	page: number
	/** @minimum 0 */
	page_size: number
	/** @minimum 0 */
	total_items: number
	/** @minimum 0 */
	total_pages: number
}

export interface DataPageArtist {
	status: string
	data: PageResponseArtist
}

export type PageResponseEventItemsItem = {
	id: number
	name: string
	short_description?: string
	description?: string
	location?: Location
	start_date?: null | DateWithPrecision
	end_date?: null | DateWithPrecision
	alternative_names?: AlternativeName[]
}

export interface PageResponseEvent {
	items: PageResponseEventItemsItem[]
	/** @minimum 0 */
	page: number
	/** @minimum 0 */
	page_size: number
	/** @minimum 0 */
	total_items: number
	/** @minimum 0 */
	total_pages: number
}

export interface DataPageEvent {
	status: string
	data: PageResponseEvent
}

export type PageResponseLabelItemsItem = {
	id: number
	name: string
	founded_date?: null | DateWithPrecision
	dissolved_date?: null | DateWithPrecision
	founders: number[]
	localized_names: LocalizedName[]
}

export interface PageResponseLabel {
	items: PageResponseLabelItemsItem[]
	/** @minimum 0 */
	page: number
	/** @minimum 0 */
	page_size: number
	/** @minimum 0 */
	total_items: number
	/** @minimum 0 */
	total_pages: number
}

export interface DataPageLabel {
	status: string
	data: PageResponseLabel
}

export type PageResponseReleaseItemsItem = {
	id: number
	title: string
	release_type: ReleaseType
	release_date?: null | DateWithPrecision
	recording_date_start?: null | DateWithPrecision
	recording_date_end?: null | DateWithPrecision
	/** @nullable */
	cover_art_url?: string | null
	artists?: ReleaseArtist[]
	credits?: ReleaseCredit[]
	catalog_nums?: CatalogNumber[]
	localized_titles?: LocalizedTitle[]
	discs?: ReleaseDisc[]
	tracks?: ReleaseTrack[]
	events?: SimpleEvent[]
}

export interface PageResponseRelease {
	items: PageResponseReleaseItemsItem[]
	/** @minimum 0 */
	page: number
	/** @minimum 0 */
	page_size: number
	/** @minimum 0 */
	total_items: number
	/** @minimum 0 */
	total_pages: number
}

export interface DataPageRelease {
	status: string
	data: PageResponseRelease
}

export type PageResponseSongItemsItem = {
	id: number
	title: string
	artists?: SimpleArtist[]
	releases?: SimpleRelease[]
	credits?: SongCredit[]
	languages?: Language[]
	localized_titles?: LocalizedTitle[]
	lyrics?: SongLyrics[]
}

export interface PageResponseSong {
	items: PageResponseSongItemsItem[]
	/** @minimum 0 */
	page: number
	/** @minimum 0 */
	page_size: number
	/** @minimum 0 */
	total_items: number
	/** @minimum 0 */
	total_pages: number
}

export interface DataPageSong {
	status: string
	data: PageResponseSong
}

export type PageResponseTagItemsItem = {
	id: number
	name: string
	type: TagType
	short_description: string
	description: string
	alt_names?: AlternativeName[]
	relations?: TagRelation[]
}

export interface PageResponseTag {
	items: PageResponseTagItemsItem[]
	/** @minimum 0 */
	page: number
	/** @minimum 0 */
	page_size: number
	/** @minimum 0 */
	total_items: number
	/** @minimum 0 */
	total_pages: number
}

export interface DataPageTag {
	status: string
	data: PageResponseTag
}

export interface DataPaginatedAppearance {
	status: string
	data: CursorResponseDiscography
}

export interface DataPaginatedCredit {
	status: string
	data: CursorResponseCredit
}

export interface DataPaginatedDiscography {
	status: string
	data: CursorResponseDiscography
}

export interface DataPaginatedNotificationItem {
	status: string
	data: CursorResponseNotificationItem
}

export interface DataPaginatedPendingImageQueueItem {
	status: string
	data: CursorResponsePendingImageQueueItem
}

export interface DataPaginatedSimpleArtist {
	status: string
	data: CursorResponseSimpleArtist
}

export interface DataPaginatedSimpleEvent {
	status: string
	data: CursorResponseSimpleEvent
}

export interface DataPaginatedSimpleLabel {
	status: string
	data: CursorResponseSimpleLabel
}

export interface DataPaginatedSimpleRelease {
	status: string
	data: CursorResponseSimpleRelease
}

export interface DataPaginatedSongRef {
	status: string
	data: CursorResponseSongRef
}

export interface DataPaginatedTagAggregate {
	status: string
	data: CursorResponseTagAggregate
}

export interface DataPaginatedTagRef {
	status: string
	data: CursorResponseTagRef
}

export interface DataPaginatedUserImageQueueItem {
	status: string
	data: CursorResponseUserImageQueueItem
}

export interface DataPaginatedUserSummary {
	status: string
	data: CursorResponseUserSummary
}

export interface DataPendingImageQueueCount {
	status: string
	/** @minimum 0 */
	data: number
}

export interface ResendVerificationEmailResponse {
	verification_code_expires_minutes: number
	resend_cooldown_seconds: number
}

export interface DataResendVerificationEmailResponse {
	status: string
	data: ResendVerificationEmailResponse
}

export interface SearchResponse {
	artists: CursorResponseSimpleArtist
	releases: CursorResponseSimpleRelease
	songs: CursorResponseSongRef
	events: CursorResponseSimpleEvent
	labels: CursorResponseSimpleLabel
	tags: CursorResponseTagRef
}

export interface DataSearchResponse {
	status: string
	data: SearchResponse
}

export interface SignUpResponse {
	verification_code_expires_minutes: number
	resend_cooldown_seconds: number
	signup_expires_hours: number
}

export interface DataSignUpResponse {
	status: string
	data: SignUpResponse
}

export interface DataUnreadCount {
	status: string
	/** @minimum 0 */
	data: number
}

export interface UserProfile {
	name: string
	/**
	 * Avatar url with sub directory, eg. ab/cd/abcd..xyz.jpg
	 * @nullable
	 */
	avatar_url?: string | null
	/**
	 * Banner url with sub directory, eg. ab/cd/abcd..xyz.jpg
	 * @nullable
	 */
	banner_url?: string | null
	last_login: string
	roles?: UserRole[]
	/**
	 * Whether the querist follows the user. Return `None` if querist is not signed in or it's querist's own profile
	 * @nullable
	 */
	is_following?: boolean | null
	/** @nullable */
	bio?: string | null
	settings?: unknown
}

export interface DataUserProfile {
	status: string
	data: UserProfile
}

export interface DataUserRoles {
	status: string
	data: UserRole[]
}

export interface DataVecArtist {
	status: string
	data: Artist[]
}

export interface DataVecCreditRoleSummary {
	status: string
	data: CreditRoleSummary[]
}

export interface DataVecEvent {
	status: string
	data: Event[]
}

export interface DataVecLabel {
	status: string
	data: Label[]
}

export interface DataVecLanguage {
	status: string
	data: Language[]
}

export interface DataVecRelease {
	status: string
	data: Release[]
}

export interface DataVecSong {
	status: string
	data: Song[]
}

export interface DataVecSongLyrics {
	status: string
	data: SongLyrics[]
}

export interface DataVecTag {
	status: string
	data: Tag[]
}

export interface DataVecUserRole {
	status: string
	data: UserRoleEnum[]
}

export interface VerifyResetCodeResponse {
	key: string
	key_expires_minutes: number
	key_expires_at: string
}

export interface DataVerifyResetCodeResponse {
	status: string
	data: VerifyResetCodeResponse
}

export type DataCorrectionStatus =
	(typeof DataCorrectionStatus)[keyof typeof DataCorrectionStatus]

export const DataCorrectionStatus = {
	Ok: "Ok",
} as const

export type DataCorrectionData = {
	id: number
	status: CorrectionStatus
	type: CorrectionType
	entity_id: number
	entity_type: EntityType
	created_at: string
	/** @nullable */
	handled_at?: string | null
}

export interface DataCorrection {
	status: DataCorrectionStatus
	data: DataCorrectionData
}

export type DataCorrectionDiffStatus =
	(typeof DataCorrectionDiffStatus)[keyof typeof DataCorrectionDiffStatus]

export const DataCorrectionDiffStatus = {
	Ok: "Ok",
} as const

export type DataCorrectionDiffData = {
	entity_id: number
	entity_type: EntityType
	/** @nullable */
	base_correction_id?: number | null
	/** @nullable */
	base_history_id?: number | null
	target_correction_id: number
	target_history_id: number
	changes: CorrectionDiffEntry[]
}

export interface DataCorrectionDiff {
	status: DataCorrectionDiffStatus
	data: DataCorrectionDiffData
}

export type DataCorrectionSubmissionResultStatus =
	(typeof DataCorrectionSubmissionResultStatus)[keyof typeof DataCorrectionSubmissionResultStatus]

export const DataCorrectionSubmissionResultStatus = {
	Ok: "Ok",
} as const

export type DataCorrectionSubmissionResultData = {
	correction_id: number
	entity_id: number
}

export interface DataCorrectionSubmissionResult {
	status: DataCorrectionSubmissionResultStatus
	data: DataCorrectionSubmissionResultData
}

export type DataOptionI32Status =
	(typeof DataOptionI32Status)[keyof typeof DataOptionI32Status]

export const DataOptionI32Status = {
	Ok: "Ok",
} as const

export interface DataOptionI32 {
	status: DataOptionI32Status
	data: null | number
}

export type DataVecCorrectionHistoryItemStatus =
	(typeof DataVecCorrectionHistoryItemStatus)[keyof typeof DataVecCorrectionHistoryItemStatus]

export const DataVecCorrectionHistoryItemStatus = {
	Ok: "Ok",
} as const

export type DataVecCorrectionHistoryItemDataItem = {
	id: number
	type: CorrectionType
	created_at: string
	/** @nullable */
	handled_at?: string | null
	author: CorrectionUserSummary
	description: string
}

export interface DataVecCorrectionHistoryItem {
	status: DataVecCorrectionHistoryItemStatus
	data: DataVecCorrectionHistoryItemDataItem[]
}

export type DataVecCorrectionRevisionSummaryStatus =
	(typeof DataVecCorrectionRevisionSummaryStatus)[keyof typeof DataVecCorrectionRevisionSummaryStatus]

export const DataVecCorrectionRevisionSummaryStatus = {
	Ok: "Ok",
} as const

export type DataVecCorrectionRevisionSummaryDataItem = {
	entity_history_id: number
	author: CorrectionUserSummary
	description: string
}

export interface DataVecCorrectionRevisionSummary {
	status: DataVecCorrectionRevisionSummaryStatus
	data: DataVecCorrectionRevisionSummaryDataItem[]
}

export interface DeleteVoteBody {
	tag_id: number
}

export type EntityIdent = string

export type ErrorStatus = (typeof ErrorStatus)[keyof typeof ErrorStatus]

export const ErrorStatus = {
	Err: "Err",
} as const

export interface Error {
	status: ErrorStatus
	message: string
}

export interface ForgotPasswordRequest {
	email: string
}

export type HandleCorrectionMethod =
	(typeof HandleCorrectionMethod)[keyof typeof HandleCorrectionMethod]

export const HandleCorrectionMethod = {
	Approve: "Approve",
	Reject: "Reject",
} as const

export type HandleImageQueueMethod =
	(typeof HandleImageQueueMethod)[keyof typeof HandleImageQueueMethod]

export const HandleImageQueueMethod = {
	Approve: "Approve",
	Reject: "Reject",
	Revert: "Revert",
} as const

export type ImageQueueType =
	(typeof ImageQueueType)[keyof typeof ImageQueueType]

export const ImageQueueType = {
	artist: "artist",
	release: "release",
} as const

export type MessageStatus = (typeof MessageStatus)[keyof typeof MessageStatus]

export const MessageStatus = {
	Ok: "Ok",
} as const

export interface Message {
	status: MessageStatus
	message: string
}

export interface NewLocalizedName {
	language_id: number
	name: string
}

export interface NewMembership {
	artist_id: number
	roles: number[]
	tenure: Tenure[]
}

export interface NewArtist {
	name: EntityIdent
	artist_type: ArtistType
	/**
	 * List of id of artist aliases
	 * @nullable
	 */
	aliases?: number[] | null
	/**
	 * Aliases without own page
	 * @nullable
	 */
	text_aliases?: EntityIdent[] | null
	start_date?: null | DateWithPrecision
	end_date?: null | DateWithPrecision
	/** @nullable */
	links?: string[] | null
	/** @nullable */
	localized_names?: NewLocalizedName[] | null
	start_location?: null | Location
	current_location?: null | Location
	/**
	 * Groups list for individuals, member list for groups,
	 * @nullable
	 */
	memberships?: NewMembership[] | null
}

export interface NewCatalogNumber {
	catalog_number: string
	/** @nullable */
	label_id?: number | null
}

export type NewCorrectionNewArtistData = {
	name: EntityIdent
	artist_type: ArtistType
	/**
	 * List of id of artist aliases
	 * @nullable
	 */
	aliases?: number[] | null
	/**
	 * Aliases without own page
	 * @nullable
	 */
	text_aliases?: EntityIdent[] | null
	start_date?: null | DateWithPrecision
	end_date?: null | DateWithPrecision
	/** @nullable */
	links?: string[] | null
	/** @nullable */
	localized_names?: NewLocalizedName[] | null
	start_location?: null | Location
	current_location?: null | Location
	/**
	 * Groups list for individuals, member list for groups,
	 * @nullable
	 */
	memberships?: NewMembership[] | null
}

export interface NewCorrectionNewArtist {
	data: NewCorrectionNewArtistData
	description: string
	type: CorrectionType
}

export type NewCorrectionNewCreditRoleData = {
	name: EntityIdent
	/** @nullable */
	short_description?: string | null
	/** @nullable */
	description?: string | null
	/** @nullable */
	super_roles?: number[] | null
}

export interface NewCorrectionNewCreditRole {
	data: NewCorrectionNewCreditRoleData
	description: string
	type: CorrectionType
}

export type NewCorrectionNewEventData = {
	name: EntityIdent
	/** @nullable */
	short_description?: string | null
	/** @nullable */
	description?: string | null
	location?: null | Location
	start_date?: null | DateWithPrecision
	end_date?: null | DateWithPrecision
	/** @nullable */
	alternative_names?: string[] | null
}

export interface NewCorrectionNewEvent {
	data: NewCorrectionNewEventData
	description: string
	type: CorrectionType
}

export type NewCorrectionNewLabelData = {
	name: EntityIdent
	founded_date?: null | DateWithPrecision
	dissolved_date?: null | DateWithPrecision
	/** @nullable */
	founders?: number[] | null
	/** @nullable */
	localized_names?: NewLocalizedName[] | null
}

export interface NewCorrectionNewLabel {
	data: NewCorrectionNewLabelData
	description: string
	type: CorrectionType
}

export interface NewCredit {
	artist_id: number
	role_id: number
	/** @nullable */
	on?: number[] | null
}

export interface NewDisc {
	/** @nullable */
	name?: string | null
}

export interface NewLocalizedTitle {
	language_id: number
	title: string
}

export interface NewTrack {
	song_id: number
	/** @nullable */
	track_number?: string | null
	/** @nullable */
	display_title?: string | null
	/** @nullable */
	duration?: number | null
	/** @minimum 0 */
	disc_index: number
	artists: number[]
}

export type NewCorrectionNewReleaseData = {
	title: string
	release_type: ReleaseType
	release_date?: null | DateWithPrecision
	recording_date_start?: null | DateWithPrecision
	recording_date_end?: null | DateWithPrecision
	artists: number[]
	catalog_nums: NewCatalogNumber[]
	credits: NewCredit[]
	discs: NewDisc[]
	events: number[]
	localized_titles: NewLocalizedTitle[]
	tracks: NewTrack[]
}

export interface NewCorrectionNewRelease {
	data: NewCorrectionNewReleaseData
	description: string
	type: CorrectionType
}

export interface NewSongCredit {
	artist_id: number
	/** @nullable */
	role_id?: number | null
}

export type NewCorrectionNewSongData = {
	title: EntityIdent
	/** @nullable */
	artists?: number[] | null
	/** @nullable */
	credits?: NewSongCredit[] | null
	/** @nullable */
	languages?: number[] | null
	/** @nullable */
	localized_titles?: NewLocalizedName[] | null
}

export interface NewCorrectionNewSong {
	data: NewCorrectionNewSongData
	description: string
	type: CorrectionType
}

export type NewCorrectionNewSongLyricsData = {
	song_id: number
	language_id: number
	content: string
	is_main: boolean
}

export interface NewCorrectionNewSongLyrics {
	data: NewCorrectionNewSongLyricsData
	description: string
	type: CorrectionType
}

export interface NewTagRelation {
	related_tag_id: number
	type: TagRelationType
}

export type NewCorrectionNewTagData = {
	name: EntityIdent
	type: TagType
	/** @nullable */
	short_description?: string | null
	/** @nullable */
	description?: string | null
	/** @nullable */
	alt_names?: string[] | null
	/** @nullable */
	relations?: NewTagRelation[] | null
}

export interface NewCorrectionNewTag {
	data: NewCorrectionNewTagData
	description: string
	type: CorrectionType
}

export interface NewCreditRole {
	name: EntityIdent
	/** @nullable */
	short_description?: string | null
	/** @nullable */
	description?: string | null
	/** @nullable */
	super_roles?: number[] | null
}

export interface NewEvent {
	name: EntityIdent
	/** @nullable */
	short_description?: string | null
	/** @nullable */
	description?: string | null
	location?: null | Location
	start_date?: null | DateWithPrecision
	end_date?: null | DateWithPrecision
	/** @nullable */
	alternative_names?: string[] | null
}

export interface NewLabel {
	name: EntityIdent
	founded_date?: null | DateWithPrecision
	dissolved_date?: null | DateWithPrecision
	/** @nullable */
	founders?: number[] | null
	/** @nullable */
	localized_names?: NewLocalizedName[] | null
}

export interface NewRelease {
	title: string
	release_type: ReleaseType
	release_date?: null | DateWithPrecision
	recording_date_start?: null | DateWithPrecision
	recording_date_end?: null | DateWithPrecision
	artists: number[]
	catalog_nums: NewCatalogNumber[]
	credits: NewCredit[]
	discs: NewDisc[]
	events: number[]
	localized_titles: NewLocalizedTitle[]
	tracks: NewTrack[]
}

export interface NewSong {
	title: EntityIdent
	/** @nullable */
	artists?: number[] | null
	/** @nullable */
	credits?: NewSongCredit[] | null
	/** @nullable */
	languages?: number[] | null
	/** @nullable */
	localized_titles?: NewLocalizedName[] | null
}

export interface NewSongLyrics {
	song_id: number
	language_id: number
	content: string
	is_main: boolean
}

export interface NewTag {
	name: EntityIdent
	type: TagType
	/** @nullable */
	short_description?: string | null
	/** @nullable */
	description?: string | null
	/** @nullable */
	alt_names?: string[] | null
	/** @nullable */
	relations?: NewTagRelation[] | null
}

export interface ReleaseCoverArtFormData {
	/**
	 * @minimum 1024
	 * @maximum 10485760
	 */
	data: Blob
}

export interface ResendVerificationEmailRequest {
	email: string
}

export interface ResetPasswordRequest {
	/** @maxLength 64 */
	key: string
	password: string
}

export interface SetUserRolesRequest {
	roles: string[]
}

export interface SignUpRequest {
	username: string
	email: string
	password: string
}

export type SortDirection = (typeof SortDirection)[keyof typeof SortDirection]

export const SortDirection = {
	asc: "asc",
	desc: "desc",
} as const

export interface UploadAvatar {
	/**
	 * @minimum 1024
	 * @maximum 10485760
	 */
	data: Blob
}

export interface UploadProfileBanner {
	/**
	 * @minimum 1024
	 * @maximum 10485760
	 */
	data: Blob
}

export interface VerifyEmailRequest {
	email: string
	code: string
}

export interface VerifyResetCodeRequest {
	email: string
	/**
	 * @minLength 6
	 * @maxLength 6
	 * @pattern ^\d{6}$
	 */
	code: string
}

export type I16 = (typeof I16)[keyof typeof I16]

export const I16 = {
	Veto: "Veto",
	Low: "Low",
	Medium: "Medium",
	High: "High",
} as const

export interface VoteBody {
	tag_id: number
	score: I16
}

export type SetUserRolesDefaultOneStatus =
	(typeof SetUserRolesDefaultOneStatus)[keyof typeof SetUserRolesDefaultOneStatus]

export const SetUserRolesDefaultOneStatus = {
	Err: "Err",
} as const

export type SetUserRolesDefaultOne = {
	status: SetUserRolesDefaultOneStatus
	message: string
}

export type AdminUsersParams = {
	/**
	 * @minimum 0
	 * @nullable
	 */
	limit?: number | null
	/**
	 * @nullable
	 */
	cursor?: number | null
	/**
	 * @nullable
	 */
	keyword?: string | null
}

export type AdminUsersDefaultOneStatus =
	(typeof AdminUsersDefaultOneStatus)[keyof typeof AdminUsersDefaultOneStatus]

export const AdminUsersDefaultOneStatus = {
	Err: "Err",
} as const

export type AdminUsersDefaultOne = {
	status: AdminUsersDefaultOneStatus
	message: string
}

export type FindManyArtistParams = {
	keyword: string
	artist_type?: ArtistType[]
	exclusion?: number[]
}

export type FindManyArtistDefaultOneStatus =
	(typeof FindManyArtistDefaultOneStatus)[keyof typeof FindManyArtistDefaultOneStatus]

export const FindManyArtistDefaultOneStatus = {
	Err: "Err",
} as const

export type FindManyArtistDefaultOne = {
	status: FindManyArtistDefaultOneStatus
	message: string
}

export type CreateArtistDefaultOneStatus =
	(typeof CreateArtistDefaultOneStatus)[keyof typeof CreateArtistDefaultOneStatus]

export const CreateArtistDefaultOneStatus = {
	Err: "Err",
} as const

export type CreateArtistDefaultOne = {
	status: CreateArtistDefaultOneStatus
	message: string
}

export type ExploreArtistParams = {
	/**
	 * @nullable
	 */
	artist_type?: ArtistType[] | null
	sort_field?: null | CorrectionSortField
	sort_direction?: null | SortDirection
	/**
	 * @minimum 1
	 * @maximum 100
	 * @nullable
	 */
	limit?: number | null
	/**
	 * @minimum 1
	 * @nullable
	 */
	page?: number | null
}

export type ExploreArtist400Status =
	(typeof ExploreArtist400Status)[keyof typeof ExploreArtist400Status]

export const ExploreArtist400Status = {
	Err: "Err",
} as const

export type ExploreArtist400 = {
	status: ExploreArtist400Status
	message: string
}

export type ExploreArtist500Status =
	(typeof ExploreArtist500Status)[keyof typeof ExploreArtist500Status]

export const ExploreArtist500Status = {
	Err: "Err",
} as const

export type ExploreArtist500 = {
	status: ExploreArtist500Status
	message: string
}

export type ExploreArtistDefaultOneStatus =
	(typeof ExploreArtistDefaultOneStatus)[keyof typeof ExploreArtistDefaultOneStatus]

export const ExploreArtistDefaultOneStatus = {
	Err: "Err",
} as const

export type ExploreArtistDefaultOne = {
	status: ExploreArtistDefaultOneStatus
	message: string
}

export type FindArtistByIdParams = {
	artist_type?: ArtistType[]
	exclusion?: number[]
}

export type FindArtistByIdDefaultOneStatus =
	(typeof FindArtistByIdDefaultOneStatus)[keyof typeof FindArtistByIdDefaultOneStatus]

export const FindArtistByIdDefaultOneStatus = {
	Err: "Err",
} as const

export type FindArtistByIdDefaultOne = {
	status: FindArtistByIdDefaultOneStatus
	message: string
}

export type UpsertArtistCorrectionDefaultOneStatus =
	(typeof UpsertArtistCorrectionDefaultOneStatus)[keyof typeof UpsertArtistCorrectionDefaultOneStatus]

export const UpsertArtistCorrectionDefaultOneStatus = {
	Err: "Err",
} as const

export type UpsertArtistCorrectionDefaultOne = {
	status: UpsertArtistCorrectionDefaultOneStatus
	message: string
}

export type FindArtistAppearancesParams = {
	cursor: number
	/**
	 * @minimum 0
	 */
	limit: number
}

export type FindArtistAppearancesDefaultOneStatus =
	(typeof FindArtistAppearancesDefaultOneStatus)[keyof typeof FindArtistAppearancesDefaultOneStatus]

export const FindArtistAppearancesDefaultOneStatus = {
	Err: "Err",
} as const

export type FindArtistAppearancesDefaultOne = {
	status: FindArtistAppearancesDefaultOneStatus
	message: string
}

export type GetArtistCreditsParams = {
	cursor: number
	/**
	 * @minimum 0
	 */
	limit: number
}

export type GetArtistCreditsDefaultOneStatus =
	(typeof GetArtistCreditsDefaultOneStatus)[keyof typeof GetArtistCreditsDefaultOneStatus]

export const GetArtistCreditsDefaultOneStatus = {
	Err: "Err",
} as const

export type GetArtistCreditsDefaultOne = {
	status: GetArtistCreditsDefaultOneStatus
	message: string
}

export type FindArtistDiscographiesByTypeParams = {
	release_type: ReleaseType
	cursor: number
	/**
	 * @minimum 0
	 */
	limit: number
}

export type FindArtistDiscographiesByTypeDefaultOneStatus =
	(typeof FindArtistDiscographiesByTypeDefaultOneStatus)[keyof typeof FindArtistDiscographiesByTypeDefaultOneStatus]

export const FindArtistDiscographiesByTypeDefaultOneStatus = {
	Err: "Err",
} as const

export type FindArtistDiscographiesByTypeDefaultOne = {
	status: FindArtistDiscographiesByTypeDefaultOneStatus
	message: string
}

export type FindArtistDiscographiesInitParams = {
	/**
	 * @minimum 0
	 */
	limit: number
}

export type FindArtistDiscographiesInitDefaultOneStatus =
	(typeof FindArtistDiscographiesInitDefaultOneStatus)[keyof typeof FindArtistDiscographiesInitDefaultOneStatus]

export const FindArtistDiscographiesInitDefaultOneStatus = {
	Err: "Err",
} as const

export type FindArtistDiscographiesInitDefaultOne = {
	status: FindArtistDiscographiesInitDefaultOneStatus
	message: string
}

export type UploadArtistProfileImageDefaultOneStatus =
	(typeof UploadArtistProfileImageDefaultOneStatus)[keyof typeof UploadArtistProfileImageDefaultOneStatus]

export const UploadArtistProfileImageDefaultOneStatus = {
	Err: "Err",
} as const

export type UploadArtistProfileImageDefaultOne = {
	status: UploadArtistProfileImageDefaultOneStatus
	message: string
}

export type UploadAvatarDefaultOneStatus =
	(typeof UploadAvatarDefaultOneStatus)[keyof typeof UploadAvatarDefaultOneStatus]

export const UploadAvatarDefaultOneStatus = {
	Err: "Err",
} as const

export type UploadAvatarDefaultOne = {
	status: UploadAvatarDefaultOneStatus
	message: string
}

export type CompareCorrectionsDefaultOneStatus =
	(typeof CompareCorrectionsDefaultOneStatus)[keyof typeof CompareCorrectionsDefaultOneStatus]

export const CompareCorrectionsDefaultOneStatus = {
	Err: "Err",
} as const

export type CompareCorrectionsDefaultOne = {
	status: CompareCorrectionsDefaultOneStatus
	message: string
}

export type GetCorrectionDefaultOneStatus =
	(typeof GetCorrectionDefaultOneStatus)[keyof typeof GetCorrectionDefaultOneStatus]

export const GetCorrectionDefaultOneStatus = {
	Err: "Err",
} as const

export type GetCorrectionDefaultOne = {
	status: GetCorrectionDefaultOneStatus
	message: string
}

export type HandleCorrectionParams = {
	method: HandleCorrectionMethod
}

export type HandleCorrectionDefaultOneStatus =
	(typeof HandleCorrectionDefaultOneStatus)[keyof typeof HandleCorrectionDefaultOneStatus]

export const HandleCorrectionDefaultOneStatus = {
	Err: "Err",
} as const

export type HandleCorrectionDefaultOne = {
	status: HandleCorrectionDefaultOneStatus
	message: string
}

export type GetCorrectionDiffDefaultOneStatus =
	(typeof GetCorrectionDiffDefaultOneStatus)[keyof typeof GetCorrectionDiffDefaultOneStatus]

export const GetCorrectionDiffDefaultOneStatus = {
	Err: "Err",
} as const

export type GetCorrectionDiffDefaultOne = {
	status: GetCorrectionDiffDefaultOneStatus
	message: string
}

export type GetCorrectionRevisionsDefaultOneStatus =
	(typeof GetCorrectionRevisionsDefaultOneStatus)[keyof typeof GetCorrectionRevisionsDefaultOneStatus]

export const GetCorrectionRevisionsDefaultOneStatus = {
	Err: "Err",
} as const

export type GetCorrectionRevisionsDefaultOne = {
	status: GetCorrectionRevisionsDefaultOneStatus
	message: string
}

export type CreateCreditRoleDefaultOneStatus =
	(typeof CreateCreditRoleDefaultOneStatus)[keyof typeof CreateCreditRoleDefaultOneStatus]

export const CreateCreditRoleDefaultOneStatus = {
	Err: "Err",
} as const

export type CreateCreditRoleDefaultOne = {
	status: CreateCreditRoleDefaultOneStatus
	message: string
}

export type FindManyCreditRolesSummaryParams = {
	keyword: string
}

export type FindManyCreditRolesSummaryDefaultOneStatus =
	(typeof FindManyCreditRolesSummaryDefaultOneStatus)[keyof typeof FindManyCreditRolesSummaryDefaultOneStatus]

export const FindManyCreditRolesSummaryDefaultOneStatus = {
	Err: "Err",
} as const

export type FindManyCreditRolesSummaryDefaultOne = {
	status: FindManyCreditRolesSummaryDefaultOneStatus
	message: string
}

export type FindCreditRoleByIdDefaultOneStatus =
	(typeof FindCreditRoleByIdDefaultOneStatus)[keyof typeof FindCreditRoleByIdDefaultOneStatus]

export const FindCreditRoleByIdDefaultOneStatus = {
	Err: "Err",
} as const

export type FindCreditRoleByIdDefaultOne = {
	status: FindCreditRoleByIdDefaultOneStatus
	message: string
}

export type UpsertCreditRoleCorrectionDefaultOneStatus =
	(typeof UpsertCreditRoleCorrectionDefaultOneStatus)[keyof typeof UpsertCreditRoleCorrectionDefaultOneStatus]

export const UpsertCreditRoleCorrectionDefaultOneStatus = {
	Err: "Err",
} as const

export type UpsertCreditRoleCorrectionDefaultOne = {
	status: UpsertCreditRoleCorrectionDefaultOneStatus
	message: string
}

export type FindEventByKeywordParams = {
	keyword: string
}

export type FindEventByKeywordDefaultOneStatus =
	(typeof FindEventByKeywordDefaultOneStatus)[keyof typeof FindEventByKeywordDefaultOneStatus]

export const FindEventByKeywordDefaultOneStatus = {
	Err: "Err",
} as const

export type FindEventByKeywordDefaultOne = {
	status: FindEventByKeywordDefaultOneStatus
	message: string
}

export type CreateEventDefaultOneStatus =
	(typeof CreateEventDefaultOneStatus)[keyof typeof CreateEventDefaultOneStatus]

export const CreateEventDefaultOneStatus = {
	Err: "Err",
} as const

export type CreateEventDefaultOne = {
	status: CreateEventDefaultOneStatus
	message: string
}

export type ExploreEventParams = {
	/**
	 * @nullable
	 */
	start_date_from?: string | null
	/**
	 * @nullable
	 */
	start_date_to?: string | null
	sort_field?: null | CorrectionSortField
	sort_direction?: null | SortDirection
	/**
	 * @minimum 1
	 * @maximum 100
	 * @nullable
	 */
	limit?: number | null
	/**
	 * @minimum 1
	 * @nullable
	 */
	page?: number | null
}

export type ExploreEvent400Status =
	(typeof ExploreEvent400Status)[keyof typeof ExploreEvent400Status]

export const ExploreEvent400Status = {
	Err: "Err",
} as const

export type ExploreEvent400 = {
	status: ExploreEvent400Status
	message: string
}

export type ExploreEvent500Status =
	(typeof ExploreEvent500Status)[keyof typeof ExploreEvent500Status]

export const ExploreEvent500Status = {
	Err: "Err",
} as const

export type ExploreEvent500 = {
	status: ExploreEvent500Status
	message: string
}

export type ExploreEventDefaultOneStatus =
	(typeof ExploreEventDefaultOneStatus)[keyof typeof ExploreEventDefaultOneStatus]

export const ExploreEventDefaultOneStatus = {
	Err: "Err",
} as const

export type ExploreEventDefaultOne = {
	status: ExploreEventDefaultOneStatus
	message: string
}

export type FindEventByIdDefaultOneStatus =
	(typeof FindEventByIdDefaultOneStatus)[keyof typeof FindEventByIdDefaultOneStatus]

export const FindEventByIdDefaultOneStatus = {
	Err: "Err",
} as const

export type FindEventByIdDefaultOne = {
	status: FindEventByIdDefaultOneStatus
	message: string
}

export type UpsertEventCorrectionDefaultOneStatus =
	(typeof UpsertEventCorrectionDefaultOneStatus)[keyof typeof UpsertEventCorrectionDefaultOneStatus]

export const UpsertEventCorrectionDefaultOneStatus = {
	Err: "Err",
} as const

export type UpsertEventCorrectionDefaultOne = {
	status: UpsertEventCorrectionDefaultOneStatus
	message: string
}

export type ForgotPasswordDefaultOneStatus =
	(typeof ForgotPasswordDefaultOneStatus)[keyof typeof ForgotPasswordDefaultOneStatus]

export const ForgotPasswordDefaultOneStatus = {
	Err: "Err",
} as const

export type ForgotPasswordDefaultOne = {
	status: ForgotPasswordDefaultOneStatus
	message: string
}

export type HealthCheckDefaultOneStatus =
	(typeof HealthCheckDefaultOneStatus)[keyof typeof HealthCheckDefaultOneStatus]

export const HealthCheckDefaultOneStatus = {
	Err: "Err",
} as const

export type HealthCheckDefaultOne = {
	status: HealthCheckDefaultOneStatus
	message: string
}

export type HomeMetadataDefaultOneStatus =
	(typeof HomeMetadataDefaultOneStatus)[keyof typeof HomeMetadataDefaultOneStatus]

export const HomeMetadataDefaultOneStatus = {
	Err: "Err",
} as const

export type HomeMetadataDefaultOne = {
	status: HomeMetadataDefaultOneStatus
	message: string
}

export type PendingImageQueueParams = {
	/**
	 * @minimum 1
	 * @maximum 100
	 * @nullable
	 */
	limit?: number | null
	/**
	 * @nullable
	 */
	cursor?: number | null
	type?: null | ImageQueueType
	status?: null | ImageQueueStatus
}

export type PendingImageQueueDefaultOneStatus =
	(typeof PendingImageQueueDefaultOneStatus)[keyof typeof PendingImageQueueDefaultOneStatus]

export const PendingImageQueueDefaultOneStatus = {
	Err: "Err",
} as const

export type PendingImageQueueDefaultOne = {
	status: PendingImageQueueDefaultOneStatus
	message: string
}

export type PendingImageQueueCountDefaultOneStatus =
	(typeof PendingImageQueueCountDefaultOneStatus)[keyof typeof PendingImageQueueCountDefaultOneStatus]

export const PendingImageQueueCountDefaultOneStatus = {
	Err: "Err",
} as const

export type PendingImageQueueCountDefaultOne = {
	status: PendingImageQueueCountDefaultOneStatus
	message: string
}

export type ImageQueueDetailDefaultOneStatus =
	(typeof ImageQueueDetailDefaultOneStatus)[keyof typeof ImageQueueDetailDefaultOneStatus]

export const ImageQueueDetailDefaultOneStatus = {
	Err: "Err",
} as const

export type ImageQueueDetailDefaultOne = {
	status: ImageQueueDetailDefaultOneStatus
	message: string
}

export type HandleImageQueueParams = {
	method: HandleImageQueueMethod
}

export type HandleImageQueueDefaultOneStatus =
	(typeof HandleImageQueueDefaultOneStatus)[keyof typeof HandleImageQueueDefaultOneStatus]

export const HandleImageQueueDefaultOneStatus = {
	Err: "Err",
} as const

export type HandleImageQueueDefaultOne = {
	status: HandleImageQueueDefaultOneStatus
	message: string
}

export type FindLabelByKeywordParams = {
	keyword: string
}

export type FindLabelByKeywordDefaultOneStatus =
	(typeof FindLabelByKeywordDefaultOneStatus)[keyof typeof FindLabelByKeywordDefaultOneStatus]

export const FindLabelByKeywordDefaultOneStatus = {
	Err: "Err",
} as const

export type FindLabelByKeywordDefaultOne = {
	status: FindLabelByKeywordDefaultOneStatus
	message: string
}

export type CreateLabelDefaultOneStatus =
	(typeof CreateLabelDefaultOneStatus)[keyof typeof CreateLabelDefaultOneStatus]

export const CreateLabelDefaultOneStatus = {
	Err: "Err",
} as const

export type CreateLabelDefaultOne = {
	status: CreateLabelDefaultOneStatus
	message: string
}

export type ExploreLabelParams = {
	/**
	 * @nullable
	 */
	founded_date_from?: string | null
	/**
	 * @nullable
	 */
	founded_date_to?: string | null
	/**
	 * @nullable
	 */
	is_dissolved?: boolean | null
	sort_field?: null | CorrectionSortField
	sort_direction?: null | SortDirection
	/**
	 * @minimum 1
	 * @maximum 100
	 * @nullable
	 */
	limit?: number | null
	/**
	 * @minimum 1
	 * @nullable
	 */
	page?: number | null
}

export type ExploreLabel400Status =
	(typeof ExploreLabel400Status)[keyof typeof ExploreLabel400Status]

export const ExploreLabel400Status = {
	Err: "Err",
} as const

export type ExploreLabel400 = {
	status: ExploreLabel400Status
	message: string
}

export type ExploreLabel500Status =
	(typeof ExploreLabel500Status)[keyof typeof ExploreLabel500Status]

export const ExploreLabel500Status = {
	Err: "Err",
} as const

export type ExploreLabel500 = {
	status: ExploreLabel500Status
	message: string
}

export type ExploreLabelDefaultOneStatus =
	(typeof ExploreLabelDefaultOneStatus)[keyof typeof ExploreLabelDefaultOneStatus]

export const ExploreLabelDefaultOneStatus = {
	Err: "Err",
} as const

export type ExploreLabelDefaultOne = {
	status: ExploreLabelDefaultOneStatus
	message: string
}

export type FindLabelByIdDefaultOneStatus =
	(typeof FindLabelByIdDefaultOneStatus)[keyof typeof FindLabelByIdDefaultOneStatus]

export const FindLabelByIdDefaultOneStatus = {
	Err: "Err",
} as const

export type FindLabelByIdDefaultOne = {
	status: FindLabelByIdDefaultOneStatus
	message: string
}

export type UpsertLabelCorrectionDefaultOneStatus =
	(typeof UpsertLabelCorrectionDefaultOneStatus)[keyof typeof UpsertLabelCorrectionDefaultOneStatus]

export const UpsertLabelCorrectionDefaultOneStatus = {
	Err: "Err",
} as const

export type UpsertLabelCorrectionDefaultOne = {
	status: UpsertLabelCorrectionDefaultOneStatus
	message: string
}

export type LanguageListDefaultOneStatus =
	(typeof LanguageListDefaultOneStatus)[keyof typeof LanguageListDefaultOneStatus]

export const LanguageListDefaultOneStatus = {
	Err: "Err",
} as const

export type LanguageListDefaultOne = {
	status: LanguageListDefaultOneStatus
	message: string
}

export type NotificationListParams = {
	/**
	 * @minimum 1
	 * @maximum 100
	 * @nullable
	 */
	limit?: number | null
	/**
	 * @nullable
	 */
	cursor?: number | null
}

export type NotificationListDefaultOneStatus =
	(typeof NotificationListDefaultOneStatus)[keyof typeof NotificationListDefaultOneStatus]

export const NotificationListDefaultOneStatus = {
	Err: "Err",
} as const

export type NotificationListDefaultOne = {
	status: NotificationListDefaultOneStatus
	message: string
}

export type NotificationReadAllDefaultOneStatus =
	(typeof NotificationReadAllDefaultOneStatus)[keyof typeof NotificationReadAllDefaultOneStatus]

export const NotificationReadAllDefaultOneStatus = {
	Err: "Err",
} as const

export type NotificationReadAllDefaultOne = {
	status: NotificationReadAllDefaultOneStatus
	message: string
}

export type NotificationUnreadCountDefaultOneStatus =
	(typeof NotificationUnreadCountDefaultOneStatus)[keyof typeof NotificationUnreadCountDefaultOneStatus]

export const NotificationUnreadCountDefaultOneStatus = {
	Err: "Err",
} as const

export type NotificationUnreadCountDefaultOne = {
	status: NotificationUnreadCountDefaultOneStatus
	message: string
}

export type NotificationMarkReadDefaultOneStatus =
	(typeof NotificationMarkReadDefaultOneStatus)[keyof typeof NotificationMarkReadDefaultOneStatus]

export const NotificationMarkReadDefaultOneStatus = {
	Err: "Err",
} as const

export type NotificationMarkReadDefaultOne = {
	status: NotificationMarkReadDefaultOneStatus
	message: string
}

export type ProfileDefaultOneStatus =
	(typeof ProfileDefaultOneStatus)[keyof typeof ProfileDefaultOneStatus]

export const ProfileDefaultOneStatus = {
	Err: "Err",
} as const

export type ProfileDefaultOne = {
	status: ProfileDefaultOneStatus
	message: string
}

export type UploadProfileBannerDefaultOneStatus =
	(typeof UploadProfileBannerDefaultOneStatus)[keyof typeof UploadProfileBannerDefaultOneStatus]

export const UploadProfileBannerDefaultOneStatus = {
	Err: "Err",
} as const

export type UploadProfileBannerDefaultOne = {
	status: UploadProfileBannerDefaultOneStatus
	message: string
}

export type UpdateBioDefaultOneStatus =
	(typeof UpdateBioDefaultOneStatus)[keyof typeof UpdateBioDefaultOneStatus]

export const UpdateBioDefaultOneStatus = {
	Err: "Err",
} as const

export type UpdateBioDefaultOne = {
	status: UpdateBioDefaultOneStatus
	message: string
}

export type ProfileWithNameDefaultOneStatus =
	(typeof ProfileWithNameDefaultOneStatus)[keyof typeof ProfileWithNameDefaultOneStatus]

export const ProfileWithNameDefaultOneStatus = {
	Err: "Err",
} as const

export type ProfileWithNameDefaultOne = {
	status: ProfileWithNameDefaultOneStatus
	message: string
}

export type FindReleaseByKeywordParams = {
	keyword: string
}

export type FindReleaseByKeywordDefaultOneStatus =
	(typeof FindReleaseByKeywordDefaultOneStatus)[keyof typeof FindReleaseByKeywordDefaultOneStatus]

export const FindReleaseByKeywordDefaultOneStatus = {
	Err: "Err",
} as const

export type FindReleaseByKeywordDefaultOne = {
	status: FindReleaseByKeywordDefaultOneStatus
	message: string
}

export type CreateReleaseDefaultOneStatus =
	(typeof CreateReleaseDefaultOneStatus)[keyof typeof CreateReleaseDefaultOneStatus]

export const CreateReleaseDefaultOneStatus = {
	Err: "Err",
} as const

export type CreateReleaseDefaultOne = {
	status: CreateReleaseDefaultOneStatus
	message: string
}

export type ExploreReleaseParams = {
	/**
	 * @nullable
	 */
	release_type?: ReleaseType[] | null
	sort_field?: null | CorrectionSortField
	sort_direction?: null | SortDirection
	/**
	 * @minimum 1
	 * @maximum 100
	 * @nullable
	 */
	limit?: number | null
	/**
	 * @minimum 1
	 * @nullable
	 */
	page?: number | null
}

export type ExploreRelease400Status =
	(typeof ExploreRelease400Status)[keyof typeof ExploreRelease400Status]

export const ExploreRelease400Status = {
	Err: "Err",
} as const

export type ExploreRelease400 = {
	status: ExploreRelease400Status
	message: string
}

export type ExploreRelease500Status =
	(typeof ExploreRelease500Status)[keyof typeof ExploreRelease500Status]

export const ExploreRelease500Status = {
	Err: "Err",
} as const

export type ExploreRelease500 = {
	status: ExploreRelease500Status
	message: string
}

export type ExploreReleaseDefaultOneStatus =
	(typeof ExploreReleaseDefaultOneStatus)[keyof typeof ExploreReleaseDefaultOneStatus]

export const ExploreReleaseDefaultOneStatus = {
	Err: "Err",
} as const

export type ExploreReleaseDefaultOne = {
	status: ExploreReleaseDefaultOneStatus
	message: string
}

export type FindReleaseByIdDefaultOneStatus =
	(typeof FindReleaseByIdDefaultOneStatus)[keyof typeof FindReleaseByIdDefaultOneStatus]

export const FindReleaseByIdDefaultOneStatus = {
	Err: "Err",
} as const

export type FindReleaseByIdDefaultOne = {
	status: FindReleaseByIdDefaultOneStatus
	message: string
}

export type UpdateReleaseDefaultOneStatus =
	(typeof UpdateReleaseDefaultOneStatus)[keyof typeof UpdateReleaseDefaultOneStatus]

export const UpdateReleaseDefaultOneStatus = {
	Err: "Err",
} as const

export type UpdateReleaseDefaultOne = {
	status: UpdateReleaseDefaultOneStatus
	message: string
}

export type UploadReleaseCoverArtDefaultOneStatus =
	(typeof UploadReleaseCoverArtDefaultOneStatus)[keyof typeof UploadReleaseCoverArtDefaultOneStatus]

export const UploadReleaseCoverArtDefaultOneStatus = {
	Err: "Err",
} as const

export type UploadReleaseCoverArtDefaultOne = {
	status: UploadReleaseCoverArtDefaultOneStatus
	message: string
}

export type ResendVerificationEmailDefaultOneStatus =
	(typeof ResendVerificationEmailDefaultOneStatus)[keyof typeof ResendVerificationEmailDefaultOneStatus]

export const ResendVerificationEmailDefaultOneStatus = {
	Err: "Err",
} as const

export type ResendVerificationEmailDefaultOne = {
	status: ResendVerificationEmailDefaultOneStatus
	message: string
}

export type ResetPasswordDefaultOneStatus =
	(typeof ResetPasswordDefaultOneStatus)[keyof typeof ResetPasswordDefaultOneStatus]

export const ResetPasswordDefaultOneStatus = {
	Err: "Err",
} as const

export type ResetPasswordDefaultOne = {
	status: ResetPasswordDefaultOneStatus
	message: string
}

export type SearchAllParams = {
	search_term: string
	/**
	 * @minimum 1
	 * @maximum 50
	 * @nullable
	 */
	limit?: number | null
}

export type SearchAllDefaultOneStatus =
	(typeof SearchAllDefaultOneStatus)[keyof typeof SearchAllDefaultOneStatus]

export const SearchAllDefaultOneStatus = {
	Err: "Err",
} as const

export type SearchAllDefaultOne = {
	status: SearchAllDefaultOneStatus
	message: string
}

export type SearchArtistParams = {
	search_term: string
	/**
	 * @minimum 1
	 * @maximum 50
	 * @nullable
	 */
	limit?: number | null
	/**
	 * Cursor is an offset for stable pagination in relevance ordering.
	 * @nullable
	 */
	cursor?: number | null
}

export type SearchArtistDefaultOneStatus =
	(typeof SearchArtistDefaultOneStatus)[keyof typeof SearchArtistDefaultOneStatus]

export const SearchArtistDefaultOneStatus = {
	Err: "Err",
} as const

export type SearchArtistDefaultOne = {
	status: SearchArtistDefaultOneStatus
	message: string
}

export type SearchEventParams = {
	search_term: string
	/**
	 * @minimum 1
	 * @maximum 50
	 * @nullable
	 */
	limit?: number | null
	/**
	 * Cursor is an offset for stable pagination in relevance ordering.
	 * @nullable
	 */
	cursor?: number | null
}

export type SearchEventDefaultOneStatus =
	(typeof SearchEventDefaultOneStatus)[keyof typeof SearchEventDefaultOneStatus]

export const SearchEventDefaultOneStatus = {
	Err: "Err",
} as const

export type SearchEventDefaultOne = {
	status: SearchEventDefaultOneStatus
	message: string
}

export type SearchLabelParams = {
	search_term: string
	/**
	 * @minimum 1
	 * @maximum 50
	 * @nullable
	 */
	limit?: number | null
	/**
	 * Cursor is an offset for stable pagination in relevance ordering.
	 * @nullable
	 */
	cursor?: number | null
}

export type SearchLabelDefaultOneStatus =
	(typeof SearchLabelDefaultOneStatus)[keyof typeof SearchLabelDefaultOneStatus]

export const SearchLabelDefaultOneStatus = {
	Err: "Err",
} as const

export type SearchLabelDefaultOne = {
	status: SearchLabelDefaultOneStatus
	message: string
}

export type SearchReleaseParams = {
	search_term: string
	/**
	 * @minimum 1
	 * @maximum 50
	 * @nullable
	 */
	limit?: number | null
	/**
	 * Cursor is an offset for stable pagination in relevance ordering.
	 * @nullable
	 */
	cursor?: number | null
}

export type SearchReleaseDefaultOneStatus =
	(typeof SearchReleaseDefaultOneStatus)[keyof typeof SearchReleaseDefaultOneStatus]

export const SearchReleaseDefaultOneStatus = {
	Err: "Err",
} as const

export type SearchReleaseDefaultOne = {
	status: SearchReleaseDefaultOneStatus
	message: string
}

export type SearchSongParams = {
	search_term: string
	/**
	 * @minimum 1
	 * @maximum 50
	 * @nullable
	 */
	limit?: number | null
	/**
	 * Cursor is an offset for stable pagination in relevance ordering.
	 * @nullable
	 */
	cursor?: number | null
}

export type SearchSongDefaultOneStatus =
	(typeof SearchSongDefaultOneStatus)[keyof typeof SearchSongDefaultOneStatus]

export const SearchSongDefaultOneStatus = {
	Err: "Err",
} as const

export type SearchSongDefaultOne = {
	status: SearchSongDefaultOneStatus
	message: string
}

export type SearchTagParams = {
	search_term: string
	/**
	 * @minimum 1
	 * @maximum 50
	 * @nullable
	 */
	limit?: number | null
	/**
	 * Cursor is an offset for stable pagination in relevance ordering.
	 * @nullable
	 */
	cursor?: number | null
}

export type SearchTagDefaultOneStatus =
	(typeof SearchTagDefaultOneStatus)[keyof typeof SearchTagDefaultOneStatus]

export const SearchTagDefaultOneStatus = {
	Err: "Err",
} as const

export type SearchTagDefaultOne = {
	status: SearchTagDefaultOneStatus
	message: string
}

export type SignInDefaultOneStatus =
	(typeof SignInDefaultOneStatus)[keyof typeof SignInDefaultOneStatus]

export const SignInDefaultOneStatus = {
	Err: "Err",
} as const

export type SignInDefaultOne = {
	status: SignInDefaultOneStatus
	message: string
}

export type SignOutDefaultOneStatus =
	(typeof SignOutDefaultOneStatus)[keyof typeof SignOutDefaultOneStatus]

export const SignOutDefaultOneStatus = {
	Err: "Err",
} as const

export type SignOutDefaultOne = {
	status: SignOutDefaultOneStatus
	message: string
}

export type SignUpDefaultOneStatus =
	(typeof SignUpDefaultOneStatus)[keyof typeof SignUpDefaultOneStatus]

export const SignUpDefaultOneStatus = {
	Err: "Err",
} as const

export type SignUpDefaultOne = {
	status: SignUpDefaultOneStatus
	message: string
}

export type FindSongByKeywordParams = {
	keyword: string
}

export type FindSongByKeywordDefaultOneStatus =
	(typeof FindSongByKeywordDefaultOneStatus)[keyof typeof FindSongByKeywordDefaultOneStatus]

export const FindSongByKeywordDefaultOneStatus = {
	Err: "Err",
} as const

export type FindSongByKeywordDefaultOne = {
	status: FindSongByKeywordDefaultOneStatus
	message: string
}

export type CreateSongDefaultOneStatus =
	(typeof CreateSongDefaultOneStatus)[keyof typeof CreateSongDefaultOneStatus]

export const CreateSongDefaultOneStatus = {
	Err: "Err",
} as const

export type CreateSongDefaultOne = {
	status: CreateSongDefaultOneStatus
	message: string
}

export type FindOneSongLyricsParams = {
	song_id: number
	language_id: number
}

export type FindOneSongLyricsDefaultOneStatus =
	(typeof FindOneSongLyricsDefaultOneStatus)[keyof typeof FindOneSongLyricsDefaultOneStatus]

export const FindOneSongLyricsDefaultOneStatus = {
	Err: "Err",
} as const

export type FindOneSongLyricsDefaultOne = {
	status: FindOneSongLyricsDefaultOneStatus
	message: string
}

export type CreateSongLyricsDefaultOneStatus =
	(typeof CreateSongLyricsDefaultOneStatus)[keyof typeof CreateSongLyricsDefaultOneStatus]

export const CreateSongLyricsDefaultOneStatus = {
	Err: "Err",
} as const

export type CreateSongLyricsDefaultOne = {
	status: CreateSongLyricsDefaultOneStatus
	message: string
}

export type FindManySongLyricsParams = {
	song_id: number
}

export type FindManySongLyricsDefaultOneStatus =
	(typeof FindManySongLyricsDefaultOneStatus)[keyof typeof FindManySongLyricsDefaultOneStatus]

export const FindManySongLyricsDefaultOneStatus = {
	Err: "Err",
} as const

export type FindManySongLyricsDefaultOne = {
	status: FindManySongLyricsDefaultOneStatus
	message: string
}

export type UpdateSongLyricsDefaultOneStatus =
	(typeof UpdateSongLyricsDefaultOneStatus)[keyof typeof UpdateSongLyricsDefaultOneStatus]

export const UpdateSongLyricsDefaultOneStatus = {
	Err: "Err",
} as const

export type UpdateSongLyricsDefaultOne = {
	status: UpdateSongLyricsDefaultOneStatus
	message: string
}

export type ExploreSongParams = {
	/**
	 * @nullable
	 */
	language_id?: number[] | null
	sort_field?: null | CorrectionSortField
	sort_direction?: null | SortDirection
	/**
	 * @minimum 1
	 * @maximum 100
	 * @nullable
	 */
	limit?: number | null
	/**
	 * @minimum 1
	 * @nullable
	 */
	page?: number | null
}

export type ExploreSong400Status =
	(typeof ExploreSong400Status)[keyof typeof ExploreSong400Status]

export const ExploreSong400Status = {
	Err: "Err",
} as const

export type ExploreSong400 = {
	status: ExploreSong400Status
	message: string
}

export type ExploreSong500Status =
	(typeof ExploreSong500Status)[keyof typeof ExploreSong500Status]

export const ExploreSong500Status = {
	Err: "Err",
} as const

export type ExploreSong500 = {
	status: ExploreSong500Status
	message: string
}

export type ExploreSongDefaultOneStatus =
	(typeof ExploreSongDefaultOneStatus)[keyof typeof ExploreSongDefaultOneStatus]

export const ExploreSongDefaultOneStatus = {
	Err: "Err",
} as const

export type ExploreSongDefaultOne = {
	status: ExploreSongDefaultOneStatus
	message: string
}

export type FindSongByIdDefaultOneStatus =
	(typeof FindSongByIdDefaultOneStatus)[keyof typeof FindSongByIdDefaultOneStatus]

export const FindSongByIdDefaultOneStatus = {
	Err: "Err",
} as const

export type FindSongByIdDefaultOne = {
	status: FindSongByIdDefaultOneStatus
	message: string
}

export type UpdateSongDefaultOneStatus =
	(typeof UpdateSongDefaultOneStatus)[keyof typeof UpdateSongDefaultOneStatus]

export const UpdateSongDefaultOneStatus = {
	Err: "Err",
} as const

export type UpdateSongDefaultOne = {
	status: UpdateSongDefaultOneStatus
	message: string
}

export type FindTagByKeywordParams = {
	keyword: string
}

export type FindTagByKeywordDefaultOneStatus =
	(typeof FindTagByKeywordDefaultOneStatus)[keyof typeof FindTagByKeywordDefaultOneStatus]

export const FindTagByKeywordDefaultOneStatus = {
	Err: "Err",
} as const

export type FindTagByKeywordDefaultOne = {
	status: FindTagByKeywordDefaultOneStatus
	message: string
}

export type CreateTagDefaultOneStatus =
	(typeof CreateTagDefaultOneStatus)[keyof typeof CreateTagDefaultOneStatus]

export const CreateTagDefaultOneStatus = {
	Err: "Err",
} as const

export type CreateTagDefaultOne = {
	status: CreateTagDefaultOneStatus
	message: string
}

export type ExploreTagParams = {
	/**
	 * @nullable
	 */
	tag_type?: TagType[] | null
	sort_field?: null | CorrectionSortField
	sort_direction?: null | SortDirection
	/**
	 * @minimum 1
	 * @maximum 100
	 * @nullable
	 */
	limit?: number | null
	/**
	 * @minimum 1
	 * @nullable
	 */
	page?: number | null
}

export type ExploreTag400Status =
	(typeof ExploreTag400Status)[keyof typeof ExploreTag400Status]

export const ExploreTag400Status = {
	Err: "Err",
} as const

export type ExploreTag400 = {
	status: ExploreTag400Status
	message: string
}

export type ExploreTag500Status =
	(typeof ExploreTag500Status)[keyof typeof ExploreTag500Status]

export const ExploreTag500Status = {
	Err: "Err",
} as const

export type ExploreTag500 = {
	status: ExploreTag500Status
	message: string
}

export type ExploreTagDefaultOneStatus =
	(typeof ExploreTagDefaultOneStatus)[keyof typeof ExploreTagDefaultOneStatus]

export const ExploreTagDefaultOneStatus = {
	Err: "Err",
} as const

export type ExploreTagDefaultOne = {
	status: ExploreTagDefaultOneStatus
	message: string
}

export type FindTagByIdDefaultOneStatus =
	(typeof FindTagByIdDefaultOneStatus)[keyof typeof FindTagByIdDefaultOneStatus]

export const FindTagByIdDefaultOneStatus = {
	Err: "Err",
} as const

export type FindTagByIdDefaultOne = {
	status: FindTagByIdDefaultOneStatus
	message: string
}

export type UpsertTagCorrectionDefaultOneStatus =
	(typeof UpsertTagCorrectionDefaultOneStatus)[keyof typeof UpsertTagCorrectionDefaultOneStatus]

export const UpsertTagCorrectionDefaultOneStatus = {
	Err: "Err",
} as const

export type UpsertTagCorrectionDefaultOne = {
	status: UpsertTagCorrectionDefaultOneStatus
	message: string
}

export type UserRolesDefaultOneStatus =
	(typeof UserRolesDefaultOneStatus)[keyof typeof UserRolesDefaultOneStatus]

export const UserRolesDefaultOneStatus = {
	Err: "Err",
} as const

export type UserRolesDefaultOne = {
	status: UserRolesDefaultOneStatus
	message: string
}

export type FollowUserDefaultOneStatus =
	(typeof FollowUserDefaultOneStatus)[keyof typeof FollowUserDefaultOneStatus]

export const FollowUserDefaultOneStatus = {
	Err: "Err",
} as const

export type FollowUserDefaultOne = {
	status: FollowUserDefaultOneStatus
	message: string
}

export type UnfollowUserDefaultOneStatus =
	(typeof UnfollowUserDefaultOneStatus)[keyof typeof UnfollowUserDefaultOneStatus]

export const UnfollowUserDefaultOneStatus = {
	Err: "Err",
} as const

export type UnfollowUserDefaultOne = {
	status: UnfollowUserDefaultOneStatus
	message: string
}

export type UserImageQueueParams = {
	/**
	 * @minimum 1
	 * @maximum 100
	 * @nullable
	 */
	limit?: number | null
	/**
	 * @nullable
	 */
	cursor?: number | null
}

export type UserImageQueueDefaultOneStatus =
	(typeof UserImageQueueDefaultOneStatus)[keyof typeof UserImageQueueDefaultOneStatus]

export const UserImageQueueDefaultOneStatus = {
	Err: "Err",
} as const

export type UserImageQueueDefaultOne = {
	status: UserImageQueueDefaultOneStatus
	message: string
}

export type VerifyEmailDefaultOneStatus =
	(typeof VerifyEmailDefaultOneStatus)[keyof typeof VerifyEmailDefaultOneStatus]

export const VerifyEmailDefaultOneStatus = {
	Err: "Err",
} as const

export type VerifyEmailDefaultOne = {
	status: VerifyEmailDefaultOneStatus
	message: string
}

export type VerifyResetCodeDefaultOneStatus =
	(typeof VerifyResetCodeDefaultOneStatus)[keyof typeof VerifyResetCodeDefaultOneStatus]

export const VerifyResetCodeDefaultOneStatus = {
	Err: "Err",
} as const

export type VerifyResetCodeDefaultOne = {
	status: VerifyResetCodeDefaultOneStatus
	message: string
}

export type NotificationWsDefaultOneStatus =
	(typeof NotificationWsDefaultOneStatus)[keyof typeof NotificationWsDefaultOneStatus]

export const NotificationWsDefaultOneStatus = {
	Err: "Err",
} as const

export type NotificationWsDefaultOne = {
	status: NotificationWsDefaultOneStatus
	message: string
}

export type EntityCorrectionsDefaultOneStatus =
	(typeof EntityCorrectionsDefaultOneStatus)[keyof typeof EntityCorrectionsDefaultOneStatus]

export const EntityCorrectionsDefaultOneStatus = {
	Err: "Err",
} as const

export type EntityCorrectionsDefaultOne = {
	status: EntityCorrectionsDefaultOneStatus
	message: string
}

export type PendingCorrectionDefaultOneStatus =
	(typeof PendingCorrectionDefaultOneStatus)[keyof typeof PendingCorrectionDefaultOneStatus]

export const PendingCorrectionDefaultOneStatus = {
	Err: "Err",
} as const

export type PendingCorrectionDefaultOne = {
	status: PendingCorrectionDefaultOneStatus
	message: string
}

export type VoteTagDefaultOneStatus =
	(typeof VoteTagDefaultOneStatus)[keyof typeof VoteTagDefaultOneStatus]

export const VoteTagDefaultOneStatus = {
	Err: "Err",
} as const

export type VoteTagDefaultOne = {
	status: VoteTagDefaultOneStatus
	message: string
}

export type DeleteVoteDefaultOneStatus =
	(typeof DeleteVoteDefaultOneStatus)[keyof typeof DeleteVoteDefaultOneStatus]

export const DeleteVoteDefaultOneStatus = {
	Err: "Err",
} as const

export type DeleteVoteDefaultOne = {
	status: DeleteVoteDefaultOneStatus
	message: string
}

export type GetTagsParams = {
	/**
	 * @minimum 1
	 * @maximum 100
	 * @nullable
	 */
	limit?: number | null
	/**
	 * @nullable
	 */
	cursor?: number | null
}

export type GetTagsDefaultOneStatus =
	(typeof GetTagsDefaultOneStatus)[keyof typeof GetTagsDefaultOneStatus]

export const GetTagsDefaultOneStatus = {
	Err: "Err",
} as const

export type GetTagsDefaultOne = {
	status: GetTagsDefaultOneStatus
	message: string
}
