[package]
edition = "2024"
name    = "thcdb-feature-image-queue-notification"
publish = false
version = "0.1.0"

[lints]
workspace = true

[lib]
name = "image_queue_notification"
path = "src/lib.rs"

[dependencies]
entity.workspace            = true
infra_db.workspace          = true
notification_core.workspace = true
sea-orm.workspace           = true
