[package]
edition = "2024"
name    = "thcdb-feature-notification-worker"
publish = false
version = "0.1.0"

[lints]
workspace = true

[lib]
name = "notification_worker"
path = "src/lib.rs"

[dependencies]
infra_db.workspace             = true
infra_worker.workspace         = true
notification_cleanup.workspace = true
