// This file is auto-generated by @hey-api/openapi-ts
import * as v from "valibot"

export const AlternativeNameSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	name: v.string(),
})

export const ArtistImageTypeSchema = v.picklist(["Profile"])

export const ArtistImageQueueTargetSchema = v.object({
	artist_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	type: ArtistImageTypeSchema,
})

export const ArtistReleaseArtistSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	name: v.string(),
})

export const ArtistTypeSchema = v.picklist(["Solo", "Multiple", "Unknown"])

export const ArtistCommonFilterSchema = v.object({
	artist_type: v.optional(v.array(ArtistTypeSchema)),
	exclusion: v.optional(
		v.array(
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
		),
	),
})

export const AuthCredentialSchema = v.object({
	username: v.string(),
	password: v.string(),
})

export const CorrectionDiffEntrySchema = v.object({
	path: v.string(),
	before: v.optional(v.union([v.string(), v.null()])),
	after: v.optional(v.union([v.string(), v.null()])),
})

export const CorrectionSortFieldSchema = v.picklist([
	"created_at",
	"handled_at",
])

export const CorrectionStatusSchema = v.picklist([
	"Pending",
	"Approved",
	"Rejected",
])

export const CorrectionSubmissionResultSchema = v.object({
	correction_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	entity_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
})

export const CorrectionTypeSchema = v.picklist(["Create", "Update", "Delete"])

export const CorrectionUserSummarySchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	name: v.string(),
})

export const CorrectionHistoryItemSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	type: CorrectionTypeSchema,
	created_at: v.pipe(v.string(), v.isoTimestamp()),
	handled_at: v.optional(
		v.union([v.pipe(v.string(), v.isoTimestamp()), v.null()]),
	),
	author: CorrectionUserSummarySchema,
	description: v.string(),
})

export const CorrectionRevisionSummarySchema = v.object({
	entity_history_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	author: CorrectionUserSummarySchema,
	description: v.string(),
})

export const CreditRoleSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	name: v.string(),
	short_description: v.string(),
	description: v.string(),
})

export const CreditRoleRefSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	name: v.string(),
})

export const CreditRoleSummarySchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	name: v.string(),
	short_description: v.string(),
})

export const CursorResponseNotificationItemSchema = v.object({
	items: v.array(
		v.object({
			id: v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			notification_kind: v.string(),
			target_type: v.string(),
			target_id: v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			payload: v.unknown(),
			is_read: v.boolean(),
			created_at: v.pipe(v.string(), v.isoTimestamp()),
		}),
	),
	next_cursor: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
})

export const CursorResponseSimpleArtistSchema = v.object({
	items: v.array(
		v.object({
			id: v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			name: v.string(),
		}),
	),
	next_cursor: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
})

export const CursorResponseSimpleEventSchema = v.object({
	items: v.array(
		v.object({
			id: v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			name: v.string(),
		}),
	),
	next_cursor: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
})

export const CursorResponseSimpleLabelSchema = v.object({
	items: v.array(
		v.object({
			id: v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			name: v.string(),
		}),
	),
	next_cursor: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
})

export const CursorResponseSimpleReleaseSchema = v.object({
	items: v.array(
		v.object({
			id: v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			title: v.string(),
			cover_art_url: v.optional(v.union([v.string(), v.null()])),
		}),
	),
	next_cursor: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
})

export const CursorResponseSongRefSchema = v.object({
	items: v.array(
		v.object({
			id: v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			title: v.string(),
		}),
	),
	next_cursor: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
})

export const CursorResponseTagAggregateSchema = v.object({
	items: v.array(
		v.object({
			id: v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			name: v.string(),
			count: v.pipe(
				v.union([v.number(), v.string(), v.bigint()]),
				v.transform((x) => BigInt(x)),
				v.minValue(
					BigInt("-9223372036854775808"),
					"Invalid value: Expected int64 to be >= -9223372036854775808",
				),
				v.maxValue(
					BigInt("9223372036854775807"),
					"Invalid value: Expected int64 to be <= 9223372036854775807",
				),
			),
			relevance: v.number(),
			user_vote: v.optional(
				v.union([
					v.pipe(
						v.number(),
						v.integer(),
						v.minValue(
							-2147483648,
							"Invalid value: Expected int32 to be >= -2147483648",
						),
						v.maxValue(
							2147483647,
							"Invalid value: Expected int32 to be <= 2147483647",
						),
					),
					v.null(),
				]),
			),
		}),
	),
	next_cursor: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
})

export const DataOptionCreditRoleSchema = v.object({
	status: v.string(),
	data: v.union([v.null(), CreditRoleSchema]),
})

export const DataPaginatedNotificationItemSchema = v.object({
	status: v.string(),
	data: CursorResponseNotificationItemSchema,
})

export const DataPaginatedSimpleArtistSchema = v.object({
	status: v.string(),
	data: CursorResponseSimpleArtistSchema,
})

export const DataPaginatedSimpleEventSchema = v.object({
	status: v.string(),
	data: CursorResponseSimpleEventSchema,
})

export const DataPaginatedSimpleLabelSchema = v.object({
	status: v.string(),
	data: CursorResponseSimpleLabelSchema,
})

export const DataPaginatedSimpleReleaseSchema = v.object({
	status: v.string(),
	data: CursorResponseSimpleReleaseSchema,
})

export const DataPaginatedSongRefSchema = v.object({
	status: v.string(),
	data: CursorResponseSongRefSchema,
})

export const DataPaginatedTagAggregateSchema = v.object({
	status: v.string(),
	data: CursorResponseTagAggregateSchema,
})

export const DataPendingImageQueueCountSchema = v.object({
	status: v.string(),
	data: v.pipe(
		v.union([v.number(), v.string(), v.bigint()]),
		v.transform((x) => BigInt(x)),
		v.minValue(BigInt(0)),
		v.maxValue(
			BigInt("9223372036854775807"),
			"Invalid value: Expected int64 to be <= 9223372036854775807",
		),
	),
})

export const DataUnreadCountSchema = v.object({
	status: v.string(),
	data: v.pipe(
		v.union([v.number(), v.string(), v.bigint()]),
		v.transform((x) => BigInt(x)),
		v.minValue(BigInt(0)),
		v.maxValue(
			BigInt("9223372036854775807"),
			"Invalid value: Expected int64 to be <= 9223372036854775807",
		),
	),
})

export const DataVecCreditRoleSummarySchema = v.object({
	status: v.string(),
	data: v.array(CreditRoleSummarySchema),
})

export const DataCorrectionSubmissionResultSchema = v.object({
	status: v.picklist(["Ok"]),
	data: v.object({
		correction_id: v.pipe(
			v.number(),
			v.integer(),
			v.minValue(
				-2147483648,
				"Invalid value: Expected int32 to be >= -2147483648",
			),
			v.maxValue(
				2147483647,
				"Invalid value: Expected int32 to be <= 2147483647",
			),
		),
		entity_id: v.pipe(
			v.number(),
			v.integer(),
			v.minValue(
				-2147483648,
				"Invalid value: Expected int32 to be >= -2147483648",
			),
			v.maxValue(
				2147483647,
				"Invalid value: Expected int32 to be <= 2147483647",
			),
		),
	}),
})

export const DataOptionI32Schema = v.object({
	status: v.picklist(["Ok"]),
	data: v.union([
		v.null(),
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(
				-2147483648,
				"Invalid value: Expected int32 to be >= -2147483648",
			),
			v.maxValue(
				2147483647,
				"Invalid value: Expected int32 to be <= 2147483647",
			),
		),
	]),
})

export const DataVecCorrectionHistoryItemSchema = v.object({
	status: v.picklist(["Ok"]),
	data: v.array(
		v.object({
			id: v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			type: CorrectionTypeSchema,
			created_at: v.pipe(v.string(), v.isoTimestamp()),
			handled_at: v.optional(
				v.union([v.pipe(v.string(), v.isoTimestamp()), v.null()]),
			),
			author: CorrectionUserSummarySchema,
			description: v.string(),
		}),
	),
})

export const DataVecCorrectionRevisionSummarySchema = v.object({
	status: v.picklist(["Ok"]),
	data: v.array(
		v.object({
			entity_history_id: v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			author: CorrectionUserSummarySchema,
			description: v.string(),
		}),
	),
})

export const DatePrecisionSchema = v.picklist(["Day", "Month", "Year"])

export const DateWithPrecisionSchema = v.object({
	value: v.pipe(v.string(), v.isoDate()),
	precision: DatePrecisionSchema,
})

export const DeleteVoteBodySchema = v.object({
	tag_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
})

export const EntityIdentSchema = v.string()

export const EntityTypeSchema = v.picklist([
	"Artist",
	"Label",
	"Release",
	"Song",
	"Tag",
	"Event",
	"SongLyrics",
	"CreditRole",
])

export const CorrectionSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	status: CorrectionStatusSchema,
	type: CorrectionTypeSchema,
	entity_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	entity_type: EntityTypeSchema,
	created_at: v.pipe(v.string(), v.isoTimestamp()),
	handled_at: v.optional(
		v.union([v.pipe(v.string(), v.isoTimestamp()), v.null()]),
	),
})

export const CorrectionDiffSchema = v.object({
	entity_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	entity_type: EntityTypeSchema,
	base_correction_id: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
	base_history_id: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
	target_correction_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	target_history_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	changes: v.array(CorrectionDiffEntrySchema),
})

export const DataCorrectionSchema = v.object({
	status: v.picklist(["Ok"]),
	data: v.object({
		id: v.pipe(
			v.number(),
			v.integer(),
			v.minValue(
				-2147483648,
				"Invalid value: Expected int32 to be >= -2147483648",
			),
			v.maxValue(
				2147483647,
				"Invalid value: Expected int32 to be <= 2147483647",
			),
		),
		status: CorrectionStatusSchema,
		type: CorrectionTypeSchema,
		entity_id: v.pipe(
			v.number(),
			v.integer(),
			v.minValue(
				-2147483648,
				"Invalid value: Expected int32 to be >= -2147483648",
			),
			v.maxValue(
				2147483647,
				"Invalid value: Expected int32 to be <= 2147483647",
			),
		),
		entity_type: EntityTypeSchema,
		created_at: v.pipe(v.string(), v.isoTimestamp()),
		handled_at: v.optional(
			v.union([v.pipe(v.string(), v.isoTimestamp()), v.null()]),
		),
	}),
})

export const DataCorrectionDiffSchema = v.object({
	status: v.picklist(["Ok"]),
	data: v.object({
		entity_id: v.pipe(
			v.number(),
			v.integer(),
			v.minValue(
				-2147483648,
				"Invalid value: Expected int32 to be >= -2147483648",
			),
			v.maxValue(
				2147483647,
				"Invalid value: Expected int32 to be <= 2147483647",
			),
		),
		entity_type: EntityTypeSchema,
		base_correction_id: v.optional(
			v.union([
				v.pipe(
					v.number(),
					v.integer(),
					v.minValue(
						-2147483648,
						"Invalid value: Expected int32 to be >= -2147483648",
					),
					v.maxValue(
						2147483647,
						"Invalid value: Expected int32 to be <= 2147483647",
					),
				),
				v.null(),
			]),
		),
		base_history_id: v.optional(
			v.union([
				v.pipe(
					v.number(),
					v.integer(),
					v.minValue(
						-2147483648,
						"Invalid value: Expected int32 to be >= -2147483648",
					),
					v.maxValue(
						2147483647,
						"Invalid value: Expected int32 to be <= 2147483647",
					),
				),
				v.null(),
			]),
		),
		target_correction_id: v.pipe(
			v.number(),
			v.integer(),
			v.minValue(
				-2147483648,
				"Invalid value: Expected int32 to be >= -2147483648",
			),
			v.maxValue(
				2147483647,
				"Invalid value: Expected int32 to be <= 2147483647",
			),
		),
		target_history_id: v.pipe(
			v.number(),
			v.integer(),
			v.minValue(
				-2147483648,
				"Invalid value: Expected int32 to be >= -2147483648",
			),
			v.maxValue(
				2147483647,
				"Invalid value: Expected int32 to be <= 2147483647",
			),
		),
		changes: v.array(CorrectionDiffEntrySchema),
	}),
})

export const ErrorSchema = v.object({
	status: v.picklist(["Err"]),
	message: v.string(),
})

export const HandleCorrectionMethodSchema = v.picklist(["Approve", "Reject"])

export const HandleImageQueueMethodSchema = v.picklist([
	"Approve",
	"Reject",
	"Revert",
])

export const HomeMetadataSchema = v.object({
	artists_count: v.pipe(
		v.union([v.number(), v.string(), v.bigint()]),
		v.transform((x) => BigInt(x)),
		v.minValue(BigInt(0)),
		v.maxValue(
			BigInt("9223372036854775807"),
			"Invalid value: Expected int64 to be <= 9223372036854775807",
		),
	),
	releases_count: v.pipe(
		v.union([v.number(), v.string(), v.bigint()]),
		v.transform((x) => BigInt(x)),
		v.minValue(BigInt(0)),
		v.maxValue(
			BigInt("9223372036854775807"),
			"Invalid value: Expected int64 to be <= 9223372036854775807",
		),
	),
	songs_count: v.pipe(
		v.union([v.number(), v.string(), v.bigint()]),
		v.transform((x) => BigInt(x)),
		v.minValue(BigInt(0)),
		v.maxValue(
			BigInt("9223372036854775807"),
			"Invalid value: Expected int64 to be <= 9223372036854775807",
		),
	),
	tags_count: v.pipe(
		v.union([v.number(), v.string(), v.bigint()]),
		v.transform((x) => BigInt(x)),
		v.minValue(BigInt(0)),
		v.maxValue(
			BigInt("9223372036854775807"),
			"Invalid value: Expected int64 to be <= 9223372036854775807",
		),
	),
})

export const DataHomeMetadataSchema = v.object({
	status: v.string(),
	data: HomeMetadataSchema,
})

export const ImageQueueStatusSchema = v.picklist([
	"Pending",
	"Approved",
	"Rejected",
	"Cancelled",
	"Reverted",
])

export const ImageQueueTypeSchema = v.picklist(["artist", "release"])

export const LanguageSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	code: v.string(),
	name: v.string(),
})

export const DataVecLanguageSchema = v.object({
	status: v.string(),
	data: v.array(LanguageSchema),
})

export const LocalizedNameSchema = v.object({
	language: LanguageSchema,
	name: v.string(),
})

export const LabelSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	name: v.string(),
	founded_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
	dissolved_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
	founders: v.array(
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(
				-2147483648,
				"Invalid value: Expected int32 to be >= -2147483648",
			),
			v.maxValue(
				2147483647,
				"Invalid value: Expected int32 to be <= 2147483647",
			),
		),
	),
	localized_names: v.array(LocalizedNameSchema),
})

export const DataOptionLabelSchema = v.object({
	status: v.string(),
	data: v.union([v.null(), LabelSchema]),
})

export const DataVecLabelSchema = v.object({
	status: v.string(),
	data: v.array(LabelSchema),
})

export const LocalizedTitleSchema = v.object({
	language: LanguageSchema,
	title: v.string(),
})

export const LocationSchema = v.object({
	country: v.optional(v.union([v.string(), v.null()])),
	province: v.optional(v.union([v.string(), v.null()])),
	city: v.optional(v.union([v.string(), v.null()])),
})

export const EventSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	name: v.string(),
	short_description: v.optional(v.string()),
	description: v.optional(v.string()),
	location: v.optional(LocationSchema),
	start_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
	end_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
	alternative_names: v.optional(v.array(AlternativeNameSchema)),
})

export const DataOptionEventSchema = v.object({
	status: v.string(),
	data: v.union([v.null(), EventSchema]),
})

export const DataVecEventSchema = v.object({
	status: v.string(),
	data: v.array(EventSchema),
})

export const MessageSchema = v.object({
	status: v.picklist(["Ok"]),
	message: v.string(),
})

export const NewCatalogNumberSchema = v.object({
	catalog_number: v.string(),
	label_id: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
})

export const NewCorrectionNewCreditRoleSchema = v.object({
	data: v.object({
		name: EntityIdentSchema,
		short_description: v.optional(v.union([v.string(), v.null()])),
		description: v.optional(v.union([v.string(), v.null()])),
		super_roles: v.optional(
			v.union([
				v.array(
					v.pipe(
						v.number(),
						v.integer(),
						v.minValue(
							-2147483648,
							"Invalid value: Expected int32 to be >= -2147483648",
						),
						v.maxValue(
							2147483647,
							"Invalid value: Expected int32 to be <= 2147483647",
						),
					),
				),
				v.null(),
			]),
		),
	}),
	description: v.string(),
	type: CorrectionTypeSchema,
})

export const NewCorrectionNewEventSchema = v.object({
	data: v.object({
		name: EntityIdentSchema,
		short_description: v.optional(v.union([v.string(), v.null()])),
		description: v.optional(v.union([v.string(), v.null()])),
		location: v.optional(v.union([v.null(), LocationSchema])),
		start_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
		end_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
		alternative_names: v.optional(v.union([v.array(v.string()), v.null()])),
	}),
	description: v.string(),
	type: CorrectionTypeSchema,
})

export const NewCorrectionNewSongLyricsSchema = v.object({
	data: v.object({
		song_id: v.pipe(
			v.number(),
			v.integer(),
			v.minValue(
				-2147483648,
				"Invalid value: Expected int32 to be >= -2147483648",
			),
			v.maxValue(
				2147483647,
				"Invalid value: Expected int32 to be <= 2147483647",
			),
		),
		language_id: v.pipe(
			v.number(),
			v.integer(),
			v.minValue(
				-2147483648,
				"Invalid value: Expected int32 to be >= -2147483648",
			),
			v.maxValue(
				2147483647,
				"Invalid value: Expected int32 to be <= 2147483647",
			),
		),
		content: v.string(),
		is_main: v.boolean(),
	}),
	description: v.string(),
	type: CorrectionTypeSchema,
})

export const NewCreditSchema = v.object({
	artist_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	role_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	on: v.optional(
		v.union([
			v.array(
				v.pipe(
					v.number(),
					v.integer(),
					v.minValue(
						-2147483648,
						"Invalid value: Expected int32 to be >= -2147483648",
					),
					v.maxValue(
						2147483647,
						"Invalid value: Expected int32 to be <= 2147483647",
					),
				),
			),
			v.null(),
		]),
	),
})

export const NewCreditRoleSchema = v.object({
	name: EntityIdentSchema,
	short_description: v.optional(v.union([v.string(), v.null()])),
	description: v.optional(v.union([v.string(), v.null()])),
	super_roles: v.optional(
		v.union([
			v.array(
				v.pipe(
					v.number(),
					v.integer(),
					v.minValue(
						-2147483648,
						"Invalid value: Expected int32 to be >= -2147483648",
					),
					v.maxValue(
						2147483647,
						"Invalid value: Expected int32 to be <= 2147483647",
					),
				),
			),
			v.null(),
		]),
	),
})

export const NewDiscSchema = v.object({
	name: v.optional(v.union([v.string(), v.null()])),
})

export const NewEventSchema = v.object({
	name: EntityIdentSchema,
	short_description: v.optional(v.union([v.string(), v.null()])),
	description: v.optional(v.union([v.string(), v.null()])),
	location: v.optional(v.union([v.null(), LocationSchema])),
	start_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
	end_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
	alternative_names: v.optional(v.union([v.array(v.string()), v.null()])),
})

export const NewLocalizedNameSchema = v.object({
	language_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	name: v.string(),
})

export const NewCorrectionNewLabelSchema = v.object({
	data: v.object({
		name: EntityIdentSchema,
		founded_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
		dissolved_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
		founders: v.optional(
			v.union([
				v.array(
					v.pipe(
						v.number(),
						v.integer(),
						v.minValue(
							-2147483648,
							"Invalid value: Expected int32 to be >= -2147483648",
						),
						v.maxValue(
							2147483647,
							"Invalid value: Expected int32 to be <= 2147483647",
						),
					),
				),
				v.null(),
			]),
		),
		localized_names: v.optional(
			v.union([v.array(NewLocalizedNameSchema), v.null()]),
		),
	}),
	description: v.string(),
	type: CorrectionTypeSchema,
})

export const NewLabelSchema = v.object({
	name: EntityIdentSchema,
	founded_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
	dissolved_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
	founders: v.optional(
		v.union([
			v.array(
				v.pipe(
					v.number(),
					v.integer(),
					v.minValue(
						-2147483648,
						"Invalid value: Expected int32 to be >= -2147483648",
					),
					v.maxValue(
						2147483647,
						"Invalid value: Expected int32 to be <= 2147483647",
					),
				),
			),
			v.null(),
		]),
	),
	localized_names: v.optional(
		v.union([v.array(NewLocalizedNameSchema), v.null()]),
	),
})

export const NewLocalizedTitleSchema = v.object({
	language_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	title: v.string(),
})

export const NewSongCreditSchema = v.object({
	artist_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	role_id: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
})

export const NewCorrectionNewSongSchema = v.object({
	data: v.object({
		title: EntityIdentSchema,
		artists: v.optional(
			v.union([
				v.array(
					v.pipe(
						v.number(),
						v.integer(),
						v.minValue(
							-2147483648,
							"Invalid value: Expected int32 to be >= -2147483648",
						),
						v.maxValue(
							2147483647,
							"Invalid value: Expected int32 to be <= 2147483647",
						),
					),
				),
				v.null(),
			]),
		),
		credits: v.optional(v.union([v.array(NewSongCreditSchema), v.null()])),
		languages: v.optional(
			v.union([
				v.array(
					v.pipe(
						v.number(),
						v.integer(),
						v.minValue(
							-2147483648,
							"Invalid value: Expected int32 to be >= -2147483648",
						),
						v.maxValue(
							2147483647,
							"Invalid value: Expected int32 to be <= 2147483647",
						),
					),
				),
				v.null(),
			]),
		),
		localized_titles: v.optional(
			v.union([v.array(NewLocalizedNameSchema), v.null()]),
		),
	}),
	description: v.string(),
	type: CorrectionTypeSchema,
})

export const NewSongSchema = v.object({
	title: EntityIdentSchema,
	artists: v.optional(
		v.union([
			v.array(
				v.pipe(
					v.number(),
					v.integer(),
					v.minValue(
						-2147483648,
						"Invalid value: Expected int32 to be >= -2147483648",
					),
					v.maxValue(
						2147483647,
						"Invalid value: Expected int32 to be <= 2147483647",
					),
				),
			),
			v.null(),
		]),
	),
	credits: v.optional(v.union([v.array(NewSongCreditSchema), v.null()])),
	languages: v.optional(
		v.union([
			v.array(
				v.pipe(
					v.number(),
					v.integer(),
					v.minValue(
						-2147483648,
						"Invalid value: Expected int32 to be >= -2147483648",
					),
					v.maxValue(
						2147483647,
						"Invalid value: Expected int32 to be <= 2147483647",
					),
				),
			),
			v.null(),
		]),
	),
	localized_titles: v.optional(
		v.union([v.array(NewLocalizedNameSchema), v.null()]),
	),
})

export const NewSongLyricsSchema = v.object({
	song_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	language_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	content: v.string(),
	is_main: v.boolean(),
})

export const NewTrackSchema = v.object({
	song_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	track_number: v.optional(v.union([v.string(), v.null()])),
	display_title: v.optional(v.union([v.string(), v.null()])),
	duration: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
	disc_index: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(0),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	artists: v.array(
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(
				-2147483648,
				"Invalid value: Expected int32 to be >= -2147483648",
			),
			v.maxValue(
				2147483647,
				"Invalid value: Expected int32 to be <= 2147483647",
			),
		),
	),
})

export const PageResponseEventSchema = v.object({
	items: v.array(
		v.object({
			id: v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			name: v.string(),
			short_description: v.optional(v.string()),
			description: v.optional(v.string()),
			location: v.optional(LocationSchema),
			start_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
			end_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
			alternative_names: v.optional(v.array(AlternativeNameSchema)),
		}),
	),
	page: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(0),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	page_size: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(0),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	total_items: v.pipe(
		v.union([v.number(), v.string(), v.bigint()]),
		v.transform((x) => BigInt(x)),
		v.minValue(BigInt(0)),
		v.maxValue(
			BigInt("9223372036854775807"),
			"Invalid value: Expected int64 to be <= 9223372036854775807",
		),
	),
	total_pages: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(0),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
})

export const DataPageEventSchema = v.object({
	status: v.string(),
	data: PageResponseEventSchema,
})

export const PageResponseLabelSchema = v.object({
	items: v.array(
		v.object({
			id: v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			name: v.string(),
			founded_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
			dissolved_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
			founders: v.array(
				v.pipe(
					v.number(),
					v.integer(),
					v.minValue(
						-2147483648,
						"Invalid value: Expected int32 to be >= -2147483648",
					),
					v.maxValue(
						2147483647,
						"Invalid value: Expected int32 to be <= 2147483647",
					),
				),
			),
			localized_names: v.array(LocalizedNameSchema),
		}),
	),
	page: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(0),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	page_size: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(0),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	total_items: v.pipe(
		v.union([v.number(), v.string(), v.bigint()]),
		v.transform((x) => BigInt(x)),
		v.minValue(BigInt(0)),
		v.maxValue(
			BigInt("9223372036854775807"),
			"Invalid value: Expected int64 to be <= 9223372036854775807",
		),
	),
	total_pages: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(0),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
})

export const DataPageLabelSchema = v.object({
	status: v.string(),
	data: PageResponseLabelSchema,
})

export const ReleaseArtistSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	name: v.string(),
})

export const ReleaseCoverArtFormDataSchema = v.object({
	data: v.string(),
})

export const ReleaseCreditSchema = v.object({
	artist: ReleaseArtistSchema,
	role: CreditRoleRefSchema,
	on: v.optional(
		v.union([
			v.array(
				v.pipe(
					v.number(),
					v.integer(),
					v.minValue(
						-2147483648,
						"Invalid value: Expected int32 to be >= -2147483648",
					),
					v.maxValue(
						2147483647,
						"Invalid value: Expected int32 to be <= 2147483647",
					),
				),
			),
			v.null(),
		]),
	),
})

export const ReleaseDiscSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	name: v.optional(v.union([v.string(), v.null()])),
})

export const ReleaseImageTypeSchema = v.picklist(["Cover"])

export const ReleaseImageQueueTargetSchema = v.object({
	release_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	type: ReleaseImageTypeSchema,
})

export const ReleaseTypeSchema = v.picklist([
	"Album",
	"Ep",
	"Single",
	"Compilation",
	"Demo",
	"Other",
])

export const CursorResponseCreditSchema = v.object({
	items: v.array(
		v.object({
			title: v.string(),
			artist: v.array(ArtistReleaseArtistSchema),
			cover_url: v.optional(v.union([v.string(), v.null()])),
			release_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
			release_type: ReleaseTypeSchema,
			roles: v.array(CreditRoleRefSchema),
		}),
	),
	next_cursor: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
})

export const CursorResponseDiscographySchema = v.object({
	items: v.array(
		v.object({
			title: v.string(),
			cover_url: v.optional(v.union([v.string(), v.null()])),
			artist: v.array(ArtistReleaseArtistSchema),
			release_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
			release_type: ReleaseTypeSchema,
		}),
	),
	next_cursor: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
})

export const DataPaginatedAppearanceSchema = v.object({
	status: v.string(),
	data: CursorResponseDiscographySchema,
})

export const DataPaginatedCreditSchema = v.object({
	status: v.string(),
	data: CursorResponseCreditSchema,
})

export const DataPaginatedDiscographySchema = v.object({
	status: v.string(),
	data: CursorResponseDiscographySchema,
})

export const InitDiscographySchema = v.object({
	album: CursorResponseDiscographySchema,
	ep: CursorResponseDiscographySchema,
	compilation: CursorResponseDiscographySchema,
	single: CursorResponseDiscographySchema,
	demo: CursorResponseDiscographySchema,
	other: CursorResponseDiscographySchema,
})

export const DataInitDiscographySchema = v.object({
	status: v.string(),
	data: InitDiscographySchema,
})

export const NewCorrectionNewReleaseSchema = v.object({
	data: v.object({
		title: v.string(),
		release_type: ReleaseTypeSchema,
		release_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
		recording_date_start: v.optional(
			v.union([v.null(), DateWithPrecisionSchema]),
		),
		recording_date_end: v.optional(
			v.union([v.null(), DateWithPrecisionSchema]),
		),
		artists: v.array(
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
		),
		catalog_nums: v.array(NewCatalogNumberSchema),
		credits: v.array(NewCreditSchema),
		discs: v.array(NewDiscSchema),
		events: v.array(
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
		),
		localized_titles: v.array(NewLocalizedTitleSchema),
		tracks: v.array(NewTrackSchema),
	}),
	description: v.string(),
	type: CorrectionTypeSchema,
})

export const NewReleaseSchema = v.object({
	title: v.string(),
	release_type: ReleaseTypeSchema,
	release_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
	recording_date_start: v.optional(
		v.union([v.null(), DateWithPrecisionSchema]),
	),
	recording_date_end: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
	artists: v.array(
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(
				-2147483648,
				"Invalid value: Expected int32 to be >= -2147483648",
			),
			v.maxValue(
				2147483647,
				"Invalid value: Expected int32 to be <= 2147483647",
			),
		),
	),
	catalog_nums: v.array(NewCatalogNumberSchema),
	credits: v.array(NewCreditSchema),
	discs: v.array(NewDiscSchema),
	events: v.array(
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(
				-2147483648,
				"Invalid value: Expected int32 to be >= -2147483648",
			),
			v.maxValue(
				2147483647,
				"Invalid value: Expected int32 to be <= 2147483647",
			),
		),
	),
	localized_titles: v.array(NewLocalizedTitleSchema),
	tracks: v.array(NewTrackSchema),
})

export const SetUserRolesRequestSchema = v.object({
	roles: v.array(v.string()),
})

export const SimpleArtistSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	name: v.string(),
})

export const SimpleEventSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	name: v.string(),
})

export const SimpleLabelSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	name: v.string(),
})

export const CatalogNumberSchema = v.object({
	catalog_number: v.string(),
	label: v.optional(v.union([v.null(), SimpleLabelSchema])),
})

export const SimpleReleaseSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	title: v.string(),
	cover_art_url: v.optional(v.union([v.string(), v.null()])),
})

export const SongCreditSchema = v.object({
	artist: SimpleArtistSchema,
	role: v.optional(v.union([v.null(), CreditRoleRefSchema])),
})

export const SongLyricsSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	song_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	content: v.string(),
	is_main: v.boolean(),
	language: LanguageSchema,
})

export const DataOptionSongLyricsSchema = v.object({
	status: v.string(),
	data: v.union([v.null(), SongLyricsSchema]),
})

export const DataVecSongLyricsSchema = v.object({
	status: v.string(),
	data: v.array(SongLyricsSchema),
})

export const PageResponseSongSchema = v.object({
	items: v.array(
		v.object({
			id: v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			title: v.string(),
			artists: v.optional(v.array(SimpleArtistSchema)),
			releases: v.optional(v.array(SimpleReleaseSchema)),
			credits: v.optional(v.array(SongCreditSchema)),
			languages: v.optional(v.array(LanguageSchema)),
			localized_titles: v.optional(v.array(LocalizedTitleSchema)),
			lyrics: v.optional(v.array(SongLyricsSchema)),
		}),
	),
	page: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(0),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	page_size: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(0),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	total_items: v.pipe(
		v.union([v.number(), v.string(), v.bigint()]),
		v.transform((x) => BigInt(x)),
		v.minValue(BigInt(0)),
		v.maxValue(
			BigInt("9223372036854775807"),
			"Invalid value: Expected int64 to be <= 9223372036854775807",
		),
	),
	total_pages: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(0),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
})

export const DataPageSongSchema = v.object({
	status: v.string(),
	data: PageResponseSongSchema,
})

export const SongSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	title: v.string(),
	artists: v.optional(v.array(SimpleArtistSchema)),
	releases: v.optional(v.array(SimpleReleaseSchema)),
	credits: v.optional(v.array(SongCreditSchema)),
	languages: v.optional(v.array(LanguageSchema)),
	localized_titles: v.optional(v.array(LocalizedTitleSchema)),
	lyrics: v.optional(v.array(SongLyricsSchema)),
})

export const DataOptionSongSchema = v.object({
	status: v.string(),
	data: v.union([v.null(), SongSchema]),
})

export const DataVecSongSchema = v.object({
	status: v.string(),
	data: v.array(SongSchema),
})

export const SongRefSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	title: v.string(),
})

export const ReleaseTrackSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	track_number: v.optional(v.union([v.string(), v.null()])),
	disc_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	display_title: v.optional(v.union([v.string(), v.null()])),
	duration: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
	song: SongRefSchema,
	artists: v.optional(v.array(ReleaseArtistSchema)),
})

export const PageResponseReleaseSchema = v.object({
	items: v.array(
		v.object({
			id: v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			title: v.string(),
			release_type: ReleaseTypeSchema,
			release_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
			recording_date_start: v.optional(
				v.union([v.null(), DateWithPrecisionSchema]),
			),
			recording_date_end: v.optional(
				v.union([v.null(), DateWithPrecisionSchema]),
			),
			cover_art_url: v.optional(v.union([v.string(), v.null()])),
			artists: v.optional(v.array(ReleaseArtistSchema)),
			credits: v.optional(v.array(ReleaseCreditSchema)),
			catalog_nums: v.optional(v.array(CatalogNumberSchema)),
			localized_titles: v.optional(v.array(LocalizedTitleSchema)),
			discs: v.optional(v.array(ReleaseDiscSchema)),
			tracks: v.optional(v.array(ReleaseTrackSchema)),
			events: v.optional(v.array(SimpleEventSchema)),
		}),
	),
	page: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(0),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	page_size: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(0),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	total_items: v.pipe(
		v.union([v.number(), v.string(), v.bigint()]),
		v.transform((x) => BigInt(x)),
		v.minValue(BigInt(0)),
		v.maxValue(
			BigInt("9223372036854775807"),
			"Invalid value: Expected int64 to be <= 9223372036854775807",
		),
	),
	total_pages: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(0),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
})

export const DataPageReleaseSchema = v.object({
	status: v.string(),
	data: PageResponseReleaseSchema,
})

export const ReleaseSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	title: v.string(),
	release_type: ReleaseTypeSchema,
	release_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
	recording_date_start: v.optional(
		v.union([v.null(), DateWithPrecisionSchema]),
	),
	recording_date_end: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
	cover_art_url: v.optional(v.union([v.string(), v.null()])),
	artists: v.optional(v.array(ReleaseArtistSchema)),
	credits: v.optional(v.array(ReleaseCreditSchema)),
	catalog_nums: v.optional(v.array(CatalogNumberSchema)),
	localized_titles: v.optional(v.array(LocalizedTitleSchema)),
	discs: v.optional(v.array(ReleaseDiscSchema)),
	tracks: v.optional(v.array(ReleaseTrackSchema)),
	events: v.optional(v.array(SimpleEventSchema)),
})

export const DataOptionReleaseSchema = v.object({
	status: v.string(),
	data: v.union([v.null(), ReleaseSchema]),
})

export const DataVecReleaseSchema = v.object({
	status: v.string(),
	data: v.array(ReleaseSchema),
})

export const SortDirectionSchema = v.picklist(["asc", "desc"])

export const TagRelationTypeSchema = v.picklist(["Inherit", "Derive"])

export const NewTagRelationSchema = v.object({
	related_tag_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	type: TagRelationTypeSchema,
})

export const TagTypeSchema = v.picklist([
	"Descriptor",
	"Genre",
	"Movement",
	"Scene",
])

export const CursorResponseTagRefSchema = v.object({
	items: v.array(
		v.object({
			id: v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			name: v.string(),
			type: TagTypeSchema,
		}),
	),
	next_cursor: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
})

export const DataPaginatedTagRefSchema = v.object({
	status: v.string(),
	data: CursorResponseTagRefSchema,
})

export const NewCorrectionNewTagSchema = v.object({
	data: v.object({
		name: EntityIdentSchema,
		type: TagTypeSchema,
		short_description: v.optional(v.union([v.string(), v.null()])),
		description: v.optional(v.union([v.string(), v.null()])),
		alt_names: v.optional(v.union([v.array(v.string()), v.null()])),
		relations: v.optional(v.union([v.array(NewTagRelationSchema), v.null()])),
	}),
	description: v.string(),
	type: CorrectionTypeSchema,
})

export const NewTagSchema = v.object({
	name: EntityIdentSchema,
	type: TagTypeSchema,
	short_description: v.optional(v.union([v.string(), v.null()])),
	description: v.optional(v.union([v.string(), v.null()])),
	alt_names: v.optional(v.union([v.array(v.string()), v.null()])),
	relations: v.optional(v.union([v.array(NewTagRelationSchema), v.null()])),
})

export const SearchResponseSchema = v.object({
	artists: CursorResponseSimpleArtistSchema,
	releases: CursorResponseSimpleReleaseSchema,
	songs: CursorResponseSongRefSchema,
	events: CursorResponseSimpleEventSchema,
	labels: CursorResponseSimpleLabelSchema,
	tags: CursorResponseTagRefSchema,
})

export const DataSearchResponseSchema = v.object({
	status: v.string(),
	data: SearchResponseSchema,
})

export const TagRefSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	name: v.string(),
	type: TagTypeSchema,
})

export const TagRelationSchema = v.object({
	tag: TagRefSchema,
	type: TagRelationTypeSchema,
})

export const PageResponseTagSchema = v.object({
	items: v.array(
		v.object({
			id: v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			name: v.string(),
			type: TagTypeSchema,
			short_description: v.string(),
			description: v.string(),
			alt_names: v.optional(v.array(AlternativeNameSchema)),
			relations: v.optional(v.array(TagRelationSchema)),
		}),
	),
	page: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(0),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	page_size: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(0),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	total_items: v.pipe(
		v.union([v.number(), v.string(), v.bigint()]),
		v.transform((x) => BigInt(x)),
		v.minValue(BigInt(0)),
		v.maxValue(
			BigInt("9223372036854775807"),
			"Invalid value: Expected int64 to be <= 9223372036854775807",
		),
	),
	total_pages: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(0),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
})

export const DataPageTagSchema = v.object({
	status: v.string(),
	data: PageResponseTagSchema,
})

export const TagSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	name: v.string(),
	type: TagTypeSchema,
	short_description: v.string(),
	description: v.string(),
	alt_names: v.optional(v.array(AlternativeNameSchema)),
	relations: v.optional(v.array(TagRelationSchema)),
})

export const DataOptionTagSchema = v.object({
	status: v.string(),
	data: v.union([v.null(), TagSchema]),
})

export const DataVecTagSchema = v.object({
	status: v.string(),
	data: v.array(TagSchema),
})

export const TenureSchema = v.object({
	join_year: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
	leave_year: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
})

export const MembershipSchema = v.object({
	artist_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	roles: v.optional(v.array(CreditRoleRefSchema)),
	tenure: v.optional(v.array(TenureSchema)),
})

export const ArtistSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	name: v.string(),
	artist_type: ArtistTypeSchema,
	text_aliases: v.optional(v.union([v.array(v.string()), v.null()])),
	start_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
	end_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
	profile_image_url: v.optional(v.union([v.string(), v.null()])),
	aliases: v.optional(
		v.array(
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
		),
	),
	links: v.optional(v.array(v.string())),
	localized_names: v.optional(v.array(LocalizedNameSchema)),
	start_location: v.optional(LocationSchema),
	current_location: v.optional(LocationSchema),
	memberships: v.optional(v.array(MembershipSchema)),
})

export const DataOptionArtistSchema = v.object({
	status: v.string(),
	data: v.union([v.null(), ArtistSchema]),
})

export const DataVecArtistSchema = v.object({
	status: v.string(),
	data: v.array(ArtistSchema),
})

export const NewMembershipSchema = v.object({
	artist_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	roles: v.array(
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(
				-2147483648,
				"Invalid value: Expected int32 to be >= -2147483648",
			),
			v.maxValue(
				2147483647,
				"Invalid value: Expected int32 to be <= 2147483647",
			),
		),
	),
	tenure: v.array(TenureSchema),
})

export const NewArtistSchema = v.object({
	name: EntityIdentSchema,
	artist_type: ArtistTypeSchema,
	aliases: v.optional(
		v.union([
			v.array(
				v.pipe(
					v.number(),
					v.integer(),
					v.minValue(
						-2147483648,
						"Invalid value: Expected int32 to be >= -2147483648",
					),
					v.maxValue(
						2147483647,
						"Invalid value: Expected int32 to be <= 2147483647",
					),
				),
			),
			v.null(),
		]),
	),
	text_aliases: v.optional(v.union([v.array(EntityIdentSchema), v.null()])),
	start_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
	end_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
	links: v.optional(v.union([v.array(v.pipe(v.string(), v.url())), v.null()])),
	localized_names: v.optional(
		v.union([v.array(NewLocalizedNameSchema), v.null()]),
	),
	start_location: v.optional(v.union([v.null(), LocationSchema])),
	current_location: v.optional(v.union([v.null(), LocationSchema])),
	memberships: v.optional(v.union([v.array(NewMembershipSchema), v.null()])),
})

export const NewCorrectionNewArtistSchema = v.object({
	data: v.object({
		name: EntityIdentSchema,
		artist_type: ArtistTypeSchema,
		aliases: v.optional(
			v.union([
				v.array(
					v.pipe(
						v.number(),
						v.integer(),
						v.minValue(
							-2147483648,
							"Invalid value: Expected int32 to be >= -2147483648",
						),
						v.maxValue(
							2147483647,
							"Invalid value: Expected int32 to be <= 2147483647",
						),
					),
				),
				v.null(),
			]),
		),
		text_aliases: v.optional(v.union([v.array(EntityIdentSchema), v.null()])),
		start_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
		end_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
		links: v.optional(
			v.union([v.array(v.pipe(v.string(), v.url())), v.null()]),
		),
		localized_names: v.optional(
			v.union([v.array(NewLocalizedNameSchema), v.null()]),
		),
		start_location: v.optional(v.union([v.null(), LocationSchema])),
		current_location: v.optional(v.union([v.null(), LocationSchema])),
		memberships: v.optional(v.union([v.array(NewMembershipSchema), v.null()])),
	}),
	description: v.string(),
	type: CorrectionTypeSchema,
})

export const PageResponseArtistSchema = v.object({
	items: v.array(
		v.object({
			id: v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			name: v.string(),
			artist_type: ArtistTypeSchema,
			text_aliases: v.optional(v.union([v.array(v.string()), v.null()])),
			start_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
			end_date: v.optional(v.union([v.null(), DateWithPrecisionSchema])),
			profile_image_url: v.optional(v.union([v.string(), v.null()])),
			aliases: v.optional(
				v.array(
					v.pipe(
						v.number(),
						v.integer(),
						v.minValue(
							-2147483648,
							"Invalid value: Expected int32 to be >= -2147483648",
						),
						v.maxValue(
							2147483647,
							"Invalid value: Expected int32 to be <= 2147483647",
						),
					),
				),
			),
			links: v.optional(v.array(v.string())),
			localized_names: v.optional(v.array(LocalizedNameSchema)),
			start_location: v.optional(LocationSchema),
			current_location: v.optional(LocationSchema),
			memberships: v.optional(v.array(MembershipSchema)),
		}),
	),
	page: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(0),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	page_size: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(0),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	total_items: v.pipe(
		v.union([v.number(), v.string(), v.bigint()]),
		v.transform((x) => BigInt(x)),
		v.minValue(BigInt(0)),
		v.maxValue(
			BigInt("9223372036854775807"),
			"Invalid value: Expected int64 to be <= 9223372036854775807",
		),
	),
	total_pages: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(0),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
})

export const DataPageArtistSchema = v.object({
	status: v.string(),
	data: PageResponseArtistSchema,
})

export const UploadAvatarSchema = v.object({
	data: v.string(),
})

export const UploadProfileBannerSchema = v.object({
	data: v.string(),
})

export const UserRoleEnumSchema = v.picklist(["Admin", "Moderator", "User"])

export const DataVecUserRoleSchema = v.object({
	status: v.string(),
	data: v.array(UserRoleEnumSchema),
})

export const UserRoleSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	name: UserRoleEnumSchema,
})

export const CursorResponseUserSummarySchema = v.object({
	items: v.array(
		v.object({
			id: v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			name: v.string(),
			roles: v.array(UserRoleSchema),
		}),
	),
	next_cursor: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
})

export const DataPaginatedUserSummarySchema = v.object({
	status: v.string(),
	data: CursorResponseUserSummarySchema,
})

export const DataUserRolesSchema = v.object({
	status: v.string(),
	data: v.array(UserRoleSchema),
})

export const UserProfileSchema = v.object({
	name: v.string(),
	avatar_url: v.optional(v.union([v.string(), v.null()])),
	banner_url: v.optional(v.union([v.string(), v.null()])),
	last_login: v.pipe(v.string(), v.isoTimestamp()),
	roles: v.optional(v.array(UserRoleSchema)),
	is_following: v.optional(v.union([v.boolean(), v.null()])),
	bio: v.optional(v.union([v.string(), v.null()])),
	settings: v.optional(v.unknown()),
})

export const DataUserProfileSchema = v.object({
	status: v.string(),
	data: UserProfileSchema,
})

export const UserSummarySchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	name: v.string(),
})

export const CursorResponsePendingImageQueueItemSchema = v.object({
	items: v.array(
		v.object({
			id: v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			image_id: v.optional(
				v.union([
					v.pipe(
						v.number(),
						v.integer(),
						v.minValue(
							-2147483648,
							"Invalid value: Expected int32 to be >= -2147483648",
						),
						v.maxValue(
							2147483647,
							"Invalid value: Expected int32 to be <= 2147483647",
						),
					),
					v.null(),
				]),
			),
			status: ImageQueueStatusSchema,
			created_at: v.pipe(v.string(), v.isoTimestamp()),
			created_by: UserSummarySchema,
		}),
	),
	next_cursor: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
})

export const CursorResponseUserImageQueueItemSchema = v.object({
	items: v.array(
		v.object({
			id: v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			image_id: v.optional(
				v.union([
					v.pipe(
						v.number(),
						v.integer(),
						v.minValue(
							-2147483648,
							"Invalid value: Expected int32 to be >= -2147483648",
						),
						v.maxValue(
							2147483647,
							"Invalid value: Expected int32 to be <= 2147483647",
						),
					),
					v.null(),
				]),
			),
			status: ImageQueueStatusSchema,
			created_at: v.pipe(v.string(), v.isoTimestamp()),
			handled_at: v.optional(
				v.union([v.pipe(v.string(), v.isoTimestamp()), v.null()]),
			),
			handled_by: v.optional(v.union([v.null(), UserSummarySchema])),
			reverted_at: v.optional(
				v.union([v.pipe(v.string(), v.isoTimestamp()), v.null()]),
			),
			reverted_by: v.optional(v.union([v.null(), UserSummarySchema])),
		}),
	),
	next_cursor: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
})

export const DataPaginatedPendingImageQueueItemSchema = v.object({
	status: v.string(),
	data: CursorResponsePendingImageQueueItemSchema,
})

export const DataPaginatedUserImageQueueItemSchema = v.object({
	status: v.string(),
	data: CursorResponseUserImageQueueItemSchema,
})

export const ImageSummarySchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	filename: v.string(),
	directory: v.string(),
	uploaded_at: v.pipe(v.string(), v.isoTimestamp()),
	uploaded_by: UserSummarySchema,
})

export const ImageQueueDetailSchema = v.object({
	id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	image_id: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(
					-2147483648,
					"Invalid value: Expected int32 to be >= -2147483648",
				),
				v.maxValue(
					2147483647,
					"Invalid value: Expected int32 to be <= 2147483647",
				),
			),
			v.null(),
		]),
	),
	status: ImageQueueStatusSchema,
	created_at: v.pipe(v.string(), v.isoTimestamp()),
	created_by: UserSummarySchema,
	handled_at: v.optional(
		v.union([v.pipe(v.string(), v.isoTimestamp()), v.null()]),
	),
	handled_by: v.optional(v.union([v.null(), UserSummarySchema])),
	reverted_at: v.optional(
		v.union([v.pipe(v.string(), v.isoTimestamp()), v.null()]),
	),
	reverted_by: v.optional(v.union([v.null(), UserSummarySchema])),
	image: v.optional(v.union([v.null(), ImageSummarySchema])),
	artist: v.optional(v.union([v.null(), ArtistImageQueueTargetSchema])),
	release: v.optional(v.union([v.null(), ReleaseImageQueueTargetSchema])),
})

export const DataImageQueueDetailSchema = v.object({
	status: v.string(),
	data: ImageQueueDetailSchema,
})

export const I16Schema = v.picklist(["Veto", "Low", "Medium", "High"])

export const VoteBodySchema = v.object({
	tag_id: v.pipe(
		v.number(),
		v.integer(),
		v.minValue(
			-2147483648,
			"Invalid value: Expected int32 to be >= -2147483648",
		),
		v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
	),
	score: I16Schema,
})
