DELETE FROM "public"."artist_link" AS duplicate
USING "public"."artist_link" AS retained
WHERE duplicate."id" > retained."id"
  AND duplicate."artist_id" = retained."artist_id"
  AND duplicate."url" = retained."url";

DELETE FROM "public"."artist_link_history" AS duplicate
USING "public"."artist_link_history" AS retained
WHERE duplicate."id" > retained."id"
  AND duplicate."history_id" = retained."history_id"
  AND duplicate."url" = retained."url";

ALTER TABLE "public"."artist_link"
  ADD CONSTRAINT "uq_artist_link_artist_id_url" UNIQUE ("artist_id", "url");

ALTER TABLE "public"."artist_link_history"
  ADD CONSTRAINT "uq_artist_link_history_history_id_url" UNIQUE ("history_id", "url");

CREATE TABLE "public"."release_link" (
  "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "release_id" INTEGER NOT NULL REFERENCES "public"."release" ("id"),
  "url" TEXT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_release_link_release_id_url" UNIQUE ("release_id", "url")
);

CREATE TABLE "public"."release_link_history" (
  "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "history_id" INTEGER NOT NULL REFERENCES "public"."release_history" ("id"),
  "url" TEXT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_release_link_history_history_id_url" UNIQUE ("history_id", "url")
);

CREATE TABLE "public"."song_link" (
  "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "song_id" INTEGER NOT NULL REFERENCES "public"."song" ("id"),
  "url" TEXT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_song_link_song_id_url" UNIQUE ("song_id", "url")
);

CREATE TABLE "public"."song_link_history" (
  "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "history_id" INTEGER NOT NULL REFERENCES "public"."song_history" ("id"),
  "url" TEXT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_song_link_history_history_id_url" UNIQUE ("history_id", "url")
);

CREATE TABLE "public"."event_link" (
  "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "event_id" INTEGER NOT NULL REFERENCES "public"."event" ("id"),
  "url" TEXT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_event_link_event_id_url" UNIQUE ("event_id", "url")
);

CREATE TABLE "public"."event_link_history" (
  "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "history_id" INTEGER NOT NULL REFERENCES "public"."event_history" ("id"),
  "url" TEXT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_event_link_history_history_id_url" UNIQUE ("history_id", "url")
);

CREATE TABLE "public"."label_link" (
  "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "label_id" INTEGER NOT NULL REFERENCES "public"."label" ("id"),
  "url" TEXT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_label_link_label_id_url" UNIQUE ("label_id", "url")
);

CREATE TABLE "public"."label_link_history" (
  "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "history_id" INTEGER NOT NULL REFERENCES "public"."label_history" ("id"),
  "url" TEXT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_label_link_history_history_id_url" UNIQUE ("history_id", "url")
);
