CREATE TABLE "public"."notification_kind" (
  "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" TEXT NOT NULL UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE "public"."entity_type" (
  "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" TEXT NOT NULL UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE "public"."notification" (
  "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "recipient_user_id" INTEGER NOT NULL REFERENCES "public"."user" ("id"),
  "notification_kind_id" INTEGER NOT NULL REFERENCES "public"."notification_kind" ("id"),
  "target_type_id" INTEGER NOT NULL REFERENCES "public"."entity_type" ("id"),
  "target_id" INTEGER NOT NULL,
  "payload" TEXT NOT NULL DEFAULT '{}',
  "is_read" BOOLEAN NOT NULL DEFAULT FALSE,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id")
);

CREATE INDEX "idx_notification_recipient_created_at" ON "public"."notification" ("recipient_user_id", "created_at");

CREATE INDEX "idx_notification_recipient_is_read" ON "public"."notification" ("recipient_user_id", "is_read");

CREATE INDEX "idx_notification_kind_id" ON "public"."notification" ("notification_kind_id");

CREATE INDEX "idx_notification_target" ON "public"."notification" ("target_type_id", "target_id");
