[workspace]
members = [
    ".",
    "crates/collection_ext",
    "crates/constants",
    "crates/domain",
    "crates/entity",
    "crates/features/user/core",
    "crates/features/auth/core",
    "crates/features/auth/worker",
    "crates/features/account/notification",
    "crates/features/comment/notification",
    "crates/features/comment/repo",
    "crates/features/comment/service",
    "crates/features/correction/subscription",
    "crates/features/correction/notification",
    "crates/features/image_queue/core",
    "crates/features/image_queue/notification",
    "crates/features/notification/core",
    "crates/features/notification/service",
    "crates/features/notification/use_case/cleanup",
    "crates/features/notification/worker",
    "crates/features/user_collection/notification",
    "crates/features/user_profile/notification",
    "crates/flow",
    "crates/infra/db",
    "crates/infra/email",
    "crates/infra/testing",
    "crates/infra/storage",
    "crates/infra/storage/worker",
    "crates/infra/worker",
    "crates/libfp",
    "crates/macros",
    "crates/migration",
    "crates/proc_macros",
    "crates/fast_lrc",
]

[workspace.dependencies]
collection_ext               = { path = "crates/collection_ext" }
constants                    = { package = "thcdb-constants", path = "crates/constants" }
domain                       = { package = "thcdb-domain", path = "crates/domain" }
entity                       = { path = "crates/entity" }
fast-lrc                     = { path = "crates/fast_lrc" }
flow                         = { path = "crates/flow" }
infra_db                     = { package = "thcdb-infra-db", path = "crates/infra/db" }
infra_email                  = { package = "thcdb-infra-email", path = "crates/infra/email" }
infra_testing                = { package = "thcdb-infra-testing", path = "crates/infra/testing" }
infra_storage                = { package = "thcdb-infra-storage", path = "crates/infra/storage" }
infra_storage_worker         = { package = "thcdb-infra-storage-worker", path = "crates/infra/storage/worker" }
infra_worker                 = { package = "thcdb-infra-worker", path = "crates/infra/worker" }
libfp                        = { path = "crates/libfp" }
macros                       = { path = "crates/macros" }
migration                    = { path = "crates/migration" }
user_core                    = { package = "thcdb-feature-user-core", path = "crates/features/user/core" }
auth_core                    = { package = "thcdb-feature-auth-core", path = "crates/features/auth/core" }
auth_worker                  = { package = "thcdb-feature-auth-worker", path = "crates/features/auth/worker" }
account_notification         = { package = "thcdb-feature-account-notification", path = "crates/features/account/notification" }
comment_notification         = { package = "thcdb-feature-comment-notification", path = "crates/features/comment/notification" }
comment_repo                 = { package = "thcdb-feature-comment-repo", path = "crates/features/comment/repo" }
comment_service              = { package = "thcdb-feature-comment-service", path = "crates/features/comment/service" }
correction_subscription      = { package = "thcdb-feature-correction-subscription", path = "crates/features/correction/subscription" }
correction_notification      = { package = "thcdb-feature-correction-notification", path = "crates/features/correction/notification" }
image_queue_core             = { package = "thcdb-feature-image-queue-core", path = "crates/features/image_queue/core" }
image_queue_notification     = { package = "thcdb-feature-image-queue-notification", path = "crates/features/image_queue/notification" }
notification_core            = { package = "thcdb-feature-notification-core", path = "crates/features/notification/core" }
notification_service         = { package = "thcdb-feature-notification-service", path = "crates/features/notification/service" }
notification_cleanup         = { package = "thcdb-feature-notification-use-case-cleanup", path = "crates/features/notification/use_case/cleanup" }
notification_worker          = { package = "thcdb-feature-notification-worker", path = "crates/features/notification/worker" }
user_collection_notification = { package = "thcdb-feature-user-collection-notification", path = "crates/features/user_collection/notification" }
user_profile_notification    = { package = "thcdb-feature-user-profile-notification", path = "crates/features/user_profile/notification" }
proc_macros                  = { path = "crates/proc_macros" }
# external
anyhow = "1.0.104"
apalis = { version = "0.7.4", features = [
    "limit",
    "retry",
    "tracing",
], default-features = false }
apalis-cron = "0.7.4"
apalis-redis = "0.7.4"
argon2 = "0.5"
async-stream = "0.3"
axum = { version = "0.8", features = [
    "macros",
    "multipart",
    "ws",
] }
axum-login = { version = "0.18" }
bon = { version = "3.0", features = [
    "implied-bounds",
] }
chrono = "0.4"
derive_more = { version = "2.0.1", features = [
    "display",
    "error",
    "from",
    "into",
] }
dotenvy = "0.15"
enumset = { version = "1.1.7", features = [
    "alloc",
    "serde",
] }
fred = { version = "10.0", features = [ "i-scripts" ] }
garde = { version = "0.22.0", features = [ "full" ] }
itertools = "0.14"
lettre = { version = "0.11.14", default-features = false, features = [
    "builder",
    "hostname",
    "pool",
    "smtp-transport",
    "tokio1-rustls-tls",
] }
log = "0.4"
macroweave = "0.1.0"
quote = "1.0.38"
rand = "0.9.0"
fastrace = { version = "0.7", features = [ "enable" ] }
fastrace-axum = "0.2.0"
fastrace-opentelemetry = "0.16.0"
fastrace-tracing = "0.1.1"
logforth = { version = "0.29.1", features = [
    "bridge-log",
    "append-fastrace",
    "append-file",
    "append-opentelemetry",
    "diagnostic-fastrace",
    "layout-text",
] }
opentelemetry = { version = "0.31.0", default-features = false, features = [
    "trace",
] }
opentelemetry-otlp = { version = "0.31.0", features = [
    "http-proto",
    "logs",
    "trace",
], default-features = false }
opentelemetry_sdk = { version = "0.31.0", default-features = false, features = [
    "trace",
] }
sea-orm = { version = "1.1.10", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "debug-print",
] }
sea-orm-migration = { features = [
    "runtime-tokio-rustls",
    "sqlx-postgres",
], version = "1.1.10" }
sea-query = "0.32.6"
serde = { version = "1", features = [
    "derive",
] }
serde_json = "1.0"
serde_with = { version = "3.12.0", features = [
    "chrono_0_4",
] }
snafu = "0.8"
sorted-vec = { version = "0.8.11", default-features = false }
syn = { version = "2.0.98", features = [
    "full",
] }
tokio = { version = "1", features = [
    "full",
] }
tracing = { version = "0.1", features = [ "log" ] }
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "registry",
] }
strum = { version = "0.27", features = [
    "derive",
] }
utoipa = { version = "5", features = [
    "axum_extras",
    "chrono",
    "preserve_order",
    "url",
] }
url = { version = "2.5.4", features = [
    "serde",
] }

[workspace.lints.rust]
async_fn_in_trait       = "allow"
dead_code               = "allow"
unconditional_recursion = "deny"
unused_must_use         = "deny"

[workspace.lints.clippy]
allow_attributes              = "warn"
cargo                         = { level = "warn", priority = -1 }
cargo_common_metadata         = "allow"
clone_on_copy                 = "deny"
cognitive_complexity          = "allow"
enum_glob_use                 = "allow"
implicit_hasher               = "allow"
iter_on_single_items          = "allow"
missing_docs_in_private_items = "allow"
missing_errors_doc            = "allow"
missing_panics_doc            = "allow"
must_use_candidate            = "allow"
multiple_crate_versions       = "allow"
nursery                       = { level = "warn", priority = -1 }
pedantic                      = { level = "warn", priority = -1 }
redundant_pub_crate           = "allow"
single_call_fn                = "allow"
unreadable_literal            = "allow"
use_self                      = "allow"
wildcard_imports              = "allow"

[build-dependencies]
constants.workspace = true
snafu.workspace     = true

[package]
edition = "2024"
name    = "thcdb_rs"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
user_core.workspace                    = true
auth_core.workspace                    = true
account_notification.workspace         = true
collection_ext.workspace               = true
constants.workspace                    = true
domain.workspace                       = true
entity.workspace                       = true
flow.workspace                         = true
libfp.workspace                        = true
infra_db.workspace                     = true
infra_email.workspace                  = true
infra_storage.workspace                = true
infra_storage_worker.workspace         = true
infra_worker.workspace                 = true
macros.workspace                       = true
migration.workspace                    = true
notification_core.workspace            = true
notification_service.workspace         = true
notification_worker.workspace          = true
comment_notification.workspace         = true
comment_service.workspace              = true
correction_subscription.workspace      = true
correction_notification.workspace      = true
image_queue_core.workspace             = true
image_queue_notification.workspace     = true
user_collection_notification.workspace = true
user_profile_notification.workspace    = true
auth_worker.workspace                  = true
#
ammonia = "4.0.0"
argon2.features = [
    "std",
]
argon2.workspace = true
async-stream.workspace = true
async-trait = { version = "0.1" }
axum.workspace = true
axum-extra = { version = "0.12.0", features = [
    "cookie",
    "query",
    "typed-header",
] }
axum-login.workspace = true
axum_typed_multipart = "0.16"
base64 = "0.22"
bon.workspace = true
bytes = "1.10.1"
bytesize = { version = "2.0.1", features = [
    "serde",
] }
chrono.workspace = true
cookie = "0.18"
config = { version = "0.15.8", features = [
    "ron",
    "toml",
    "convert-case",
], default-features = false }
dashmap = "6.1.0"
derive_more.workspace = true
dotenvy.workspace = true
enumset.workspace = true
fastrace.workspace = true
fastrace-axum.workspace = true
fastrace-opentelemetry.workspace = true
fastrace-tracing.workspace = true
fred.workspace = true
futures-util = "0.3"
garde.workspace = true
governor = "0.10.0"
headers = "0.4"
image = "0.25"
inventory = "0.3.19"
iso8601-duration = { version = "0.2", features = [
    "chrono",
] }
itertools.workspace = true
lettre.workspace = true
maud = { version = "0.27.0", features = [
    "axum",
] }
moka = { version = "0.12", features = [
    "future",
] }
nestify = "0.3.3"
log.workspace = true
logforth.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
pico-args = { version = "0.5.0", features = [
    "eq-separator",
] }
pulldown-cmark = { version = "0.13.0", default-features = false, features = [
    "html",
    "simd",
] }
rand.workspace = true
rapidhash = "4"
regex = "1.11"
sea-orm.workspace = true
sea-orm-migration.workspace = true
sea-query.workspace = true
serde.workspace = true
serde_json.workspace = true
blake3 = "1"
serde_repr = "0.1"
serde_with.workspace = true
smart-default = "0.7.1"
snafu.workspace = true
sorted-vec.workspace = true
strum.workspace = true
mimalloc = { version = "0.1.50", optional = true }
tokio.workspace = true
tower = { version = "0.5.2", features = [
    "limit",
] }
tower-http = { version = "0.6.2", features = [
    "fs",
    "cors",
] }
tower-sessions-redis-store = "0.16.0"
tower_governor = "0.8.0"
tracing.workspace = true
tracing-subscriber.workspace = true
trait-variant = "0.1.2"
utoipa.workspace = true
utoipa-axum = "0.2"
utoipa-scalar = { version = "0.3", features = [
    "axum",
] }
vecmap-rs = "0.2.3"
xxhash-rust = { version = "0.8", features = [
    "std",
    "xxh3",
] }
zxcvbn = "3.1"
exn = "0.3.0"

[patch.crates-io]
apalis-core  = { git = "https://github.com/Huliiiiii/apalis.git", rev = "5866341937123ab1e1eee57aeeef23fd8fc10119" }
apalis-redis = { git = "https://github.com/Huliiiiii/apalis.git", rev = "5866341937123ab1e1eee57aeeef23fd8fc10119" }

[dev-dependencies]
anyhow.workspace        = true
fake                    = { version = "5.1.0", features = [ "derive" ] }
infra_testing.workspace = true
proptest                = "1"

# https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev]
debug     = 0
opt-level = 1
strip     = "debuginfo"
# If you get incremental compilation ICE, disable it
# incremental     = false

[profile.dev.build-override]
opt-level = 3

[profile.ra]
# incremental = false
inherits = "dev"
[profile.debug-mode]
debug     = 2
inherits  = "dev"
opt-level = 0
strip     = "none"

[profile.release]
codegen-units   = 1
debug           = false
lto             = "thin"
opt-level       = 3
overflow-checks = true
panic           = "abort"

[features]
release = [
    "mimalloc",
]
integration-test = [  ]
