[app]
port = 12345

[notification]
retention_days = 90

[email]
from     = "noreply@thcloud.switchsystem.eu.org"
host     = "smtp.resend.com"
port     = 587
security = "starttls"

[email.creds]
username = "resend"
# password = "" # example: "re_xxxxxxxxxxxxxxxxx"

[middleware.limit]
burst_size  = 8
req_per_sec = 5
