[app]
port = 12345

[notification]
retention_days = 90

[email]
from     = "admin@switchsystem.eu.org"
host     = "smtp.resend.com"
port     = 587
security = "starttls"

[email.creds]
username = "resend"
# password = "" # example: "re_xxxxxxxxxxxxxxxxx"

[middleware.limit]
burst_size  = 8
req_per_sec = 5

[middleware.limit.pre_auth]
burst_size  = 32
req_per_sec = 20
