CREATE TYPE "public"."NotificationAggregateKind" AS ENUM (
  'CorrectionReviewRequested',
  'CorrectionUpdated',
  'CorrectionModerated',
  'CommentReplied',
  'CommentThreadUpdated',
  'UserFollowed',
  'CollectionFollowed',
  'CollectionItemAdded',
  'ImageQueueModerated',
  'AccountRoleChanged'
);

CREATE TYPE "public"."NotificationEventType" AS ENUM (
  'CorrectionReviewRequested',
  'CorrectionUpdated',
  'CorrectionApproved',
  'CorrectionRejected',
  'CommentCreated',
  'UserFollowed',
  'CollectionFollowed',
  'CollectionItemAdded',
  'ImageQueueApproved',
  'ImageQueueRejected',
  'ImageQueueReverted',
  'AccountRoleChanged'
);

CREATE TABLE public.notification_inbox_state (
  recipient_user_id integer NOT NULL REFERENCES public.user (id) ON DELETE CASCADE,
  last_inbox_seq bigint NOT NULL,
  PRIMARY KEY (recipient_user_id),
  CONSTRAINT ck_notification_inbox_state_last_seq_nonnegative CHECK (last_inbox_seq >= 0)
);

CREATE TABLE public.notification (
  id uuid NOT NULL DEFAULT uuidv7(),
  recipient_user_id integer NOT NULL REFERENCES public.user (id) ON DELETE CASCADE,
  kind "public"."NotificationAggregateKind" NOT NULL,
  last_seq bigint NOT NULL DEFAULT 0,
  read_through_seq bigint NOT NULL DEFAULT 0,
  purged_through_seq bigint NOT NULL DEFAULT 0,
  saved_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  last_activity_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  PRIMARY KEY (id),
  CONSTRAINT uq_notification_id_recipient UNIQUE (id, recipient_user_id),
  CONSTRAINT ck_notification_read_through_seq_bounds CHECK (
    read_through_seq >= 0
    AND read_through_seq <= last_seq
  ),
  CONSTRAINT ck_notification_purged_through_seq_bounds CHECK (
    purged_through_seq >= 0
    AND purged_through_seq <= last_seq
    AND (
      last_seq = 0
      OR purged_through_seq < last_seq
    )
  )
);

CREATE INDEX idx_notification_recipient_id
ON public.notification (
  recipient_user_id,
  id
);

CREATE INDEX idx_notification_unsaved_retention_candidates
ON public.notification (
  last_activity_at
)
WHERE saved_at IS NULL;

CREATE TABLE public.notification_event (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  event_type "public"."NotificationEventType" NOT NULL,
  idempotency_key text NULL,
  actor_user_id integer NOT NULL REFERENCES public.user (id),
  occurred_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  correction_id integer NULL REFERENCES public.correction (id),
  image_queue_id integer NULL REFERENCES public.image_queue (id),
  comment_thread_id integer NULL REFERENCES public.comment_thread (id) ON DELETE SET NULL,
  comment_id integer NULL REFERENCES public.comment (id) ON DELETE SET NULL,
  target_user_id integer NULL REFERENCES public.user (id),
  user_collection_id integer NULL REFERENCES public.user_collection (id) ON DELETE SET NULL,
  PRIMARY KEY (id),
  CONSTRAINT uq_notification_event_comment UNIQUE (comment_id),
  CONSTRAINT ck_notification_event_reference_shape CHECK (
    (
      event_type IN (
        'CorrectionReviewRequested',
        'CorrectionUpdated',
        'CorrectionApproved',
        'CorrectionRejected'
      )
      AND correction_id IS NOT NULL
      AND image_queue_id IS NULL
      AND comment_thread_id IS NULL
      AND comment_id IS NULL
      AND target_user_id IS NULL
      AND user_collection_id IS NULL
    )
    OR (
      event_type = 'CommentCreated'
      AND correction_id IS NULL
      AND image_queue_id IS NULL
      AND target_user_id IS NULL
      AND user_collection_id IS NULL
    )
    OR (
      event_type IN ('UserFollowed', 'AccountRoleChanged')
      AND correction_id IS NULL
      AND image_queue_id IS NULL
      AND comment_thread_id IS NULL
      AND comment_id IS NULL
      AND target_user_id IS NOT NULL
      AND user_collection_id IS NULL
    )
    OR (
      event_type IN ('CollectionFollowed', 'CollectionItemAdded')
      AND correction_id IS NULL
      AND image_queue_id IS NULL
      AND comment_thread_id IS NULL
      AND comment_id IS NULL
      AND target_user_id IS NULL
    )
    OR (
      event_type IN (
        'ImageQueueApproved',
        'ImageQueueRejected',
        'ImageQueueReverted'
      )
      AND correction_id IS NULL
      AND image_queue_id IS NOT NULL
      AND comment_thread_id IS NULL
      AND comment_id IS NULL
      AND target_user_id IS NULL
      AND user_collection_id IS NULL
    )
  )
);

CREATE UNIQUE INDEX uq_notification_event_idempotency_key
ON public.notification_event (
  idempotency_key
)
WHERE idempotency_key IS NOT NULL;

CREATE INDEX idx_notification_event_comment_thread_id
ON public.notification_event (
  comment_thread_id
)
WHERE comment_thread_id IS NOT NULL;

CREATE INDEX idx_notification_event_user_collection_id
ON public.notification_event (
  user_collection_id
)
WHERE user_collection_id IS NOT NULL;

CREATE TABLE public.account_role_changed_notification_event (
  notification_event_id bigint NOT NULL REFERENCES public.notification_event (id) ON DELETE CASCADE,
  role_id integer NOT NULL REFERENCES public.role (id),
  PRIMARY KEY (notification_event_id, role_id)
);

CREATE TABLE public.comment_created_notification_event (
  notification_event_id bigint NOT NULL REFERENCES public.notification_event (id) ON DELETE CASCADE,
  content text NOT NULL,
  PRIMARY KEY (notification_event_id)
);

CREATE TABLE public.notification_entry (
  notification_id uuid NOT NULL,
  recipient_user_id integer NOT NULL,
  event_id bigint NOT NULL REFERENCES public.notification_event (id) ON DELETE RESTRICT,
  seq bigint NOT NULL,
  inbox_seq bigint NOT NULL,
  created_at timestamptz NOT NULL,
  PRIMARY KEY (notification_id, seq),
  CONSTRAINT fk_notification_entry_notification_recipient FOREIGN KEY (notification_id, recipient_user_id) REFERENCES public.notification (id, recipient_user_id) ON DELETE CASCADE,
  CONSTRAINT uq_notification_entry_event UNIQUE (notification_id, event_id),
  CONSTRAINT uq_notification_entry_recipient_inbox_seq UNIQUE (recipient_user_id, inbox_seq),
  CONSTRAINT ck_notification_entry_seq_positive CHECK (seq > 0),
  CONSTRAINT ck_notification_entry_inbox_seq_positive CHECK (inbox_seq > 0)
);

CREATE INDEX idx_notification_entry_event_id
ON public.notification_entry (
  event_id
);

CREATE INDEX idx_notification_entry_notification_inbox_seq
ON public.notification_entry (
  notification_id,
  inbox_seq
);

CREATE TABLE public.comment_thread_notification (
  notification_id uuid NOT NULL,
  recipient_user_id integer NOT NULL,
  comment_thread_id integer NULL REFERENCES public.comment_thread (id) ON DELETE SET NULL,
  PRIMARY KEY (notification_id),
  CONSTRAINT uq_comment_thread_notification_recipient_thread UNIQUE (recipient_user_id, comment_thread_id),
  CONSTRAINT fk_comment_thread_notification_notification_recipient FOREIGN KEY (notification_id, recipient_user_id) REFERENCES public.notification (id, recipient_user_id) ON DELETE CASCADE
);

CREATE INDEX idx_comment_thread_notification_comment_thread_id
ON public.comment_thread_notification (
  comment_thread_id
)
WHERE comment_thread_id IS NOT NULL;
