name: GitHub Actions
run-name: web

on:
  push:
    branches:
      - main
    paths:
      - "web/**"
  workflow_dispatch:

jobs:
  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: web/pnpm-lock.yaml

      - uses: extractions/setup-just@v3

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prettier check
        run: just fmt-check

      - name: Type check
        run: just check
        
      - name: Lint check
        run: just lint

      - name: Run Test
        run: just test

      - name: Build app
        run: pnpm run build
