# syntax=docker/dockerfile:1.20

ARG NODE_VERSION=24
ARG DEBIAN_VERSION=bookworm

FROM node:${NODE_VERSION}-${DEBIAN_VERSION}-slim AS builder
WORKDIR /app

COPY . ./

ENV CI=true

RUN corepack enable \
  && corepack prepare pnpm@11.1.2 --activate \
  && pnpm install --frozen-lockfile \
  && pnpm build

FROM nginx:1.29-alpine AS runtime
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/ /usr/share/nginx/html/

EXPOSE 80
