# syntax=docker/dockerfile:1.20

ARG NODE_VERSION=24
ARG DEBIAN_VERSION=bookworm

FROM node:${NODE_VERSION}-${DEBIAN_VERSION}-slim AS builder
WORKDIR /app

COPY .npmrc pnpm-lock.yaml pnpm-workspace.yaml ./

ENV CI=true

RUN npm install --global --no-audit --no-fund pnpm@11.1.2 \
  && pnpm fetch

COPY . ./

RUN pnpm install --offline --frozen-lockfile \
  && pnpm build

FROM nginx:1.29-alpine AS runtime
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/ /usr/share/nginx/html/

EXPOSE 80
